brigadecore/brigade

chart/brigade/templates/controller-role.yaml

controller need rule to create/list ... pods resource, which  is missed in controller-role.yaml

add pod rule for controler role

---

brigade-worker/src/job.ts
brigade-worker/test/job.ts
brigade-worker/test/k8s.ts
docs/topics/examples/brigade-15.js
docs/topics/javascript.md
docs/topics/scripting.md

Leaving this enabled adds a pretty serious performance hit on at least
some systems. And it is not typically used by containers out of the box.
That is, most of the time it is used, usage is already manually
configured by the script author. So it makes sense to go with
performance as the default metric.

fix(worker): disable shared storage by default

---

brigade-client/cmd/brig/commands/app.go
glide.lock
glide.yaml

The `client-go` package doesn't directly import the GCP auth backend. This PR adds an import to the brig command to use all the client-go supported providers.
Without these changes you would get an message saying  `Error: No Auth Provider found for name "gcp"`

add support for gcp auth in brig command

---

chart/brigade/values.yaml

This prevents the (insecure) API server from being exposed to the
world by default.

fix(chart): set API svc default type to ClusterIP

---

brigade-worker/test/k8s.ts

A recent change to the annotations on the pod broke tests. This fixes
the test to check the init container object instead of the annotation.

fix(worker): fix error in unit test

---

brigade-client/cmd/brig/commands/run.go

During some merges, we lost the proper handling of the -f flag.
Fixed.

fix(brig): read the file

---

chart/brigade/Chart.yaml
chart/brigade/templates/api-deployment.yaml
chart/brigade/templates/api-service.yaml
chart/brigade/templates/controller-deployment.yaml
chart/brigade/templates/gateway-deployment.yaml
chart/brigade/templates/gateway-service.yaml
chart/brigade/values.yaml

This is part of a bigger effort to make version handling in Brigade
better.
This changes the charts to use the `appVersion` field in `Chart.yaml` to
set the image tag. The `tag` field still exists for overrides, but it
simplifies the chart to assume that each component of the chart should
use the master version number to pull its tag.
Along the way, I improved documentation, and made it trivially possible
to disable API and Gateway.

ref(chart): make chart smart about versions

---

docs/topics/javascript.md

Event and Job objects did not have the same highlighting as other headings, which caused me some visual confusion.

Add missing highlights to object names

---

README.md

This condenses down the content of the README and adds more pointers to
the documentation. Just trying to cut down some redundancy. It fixes the
confusion with the Brig example.
Closes #70

docs(README): fix examples in README

---

README.md

The directions weren't clear that the chart was inside the chart/ subdirectories, like the brigade chart itself.

Update location of brigade-project helm chart

---

brigade-worker/src/group.ts
brigade-worker/test/brigadier.ts
brigade-worker/test/group.ts
docs/topics/javascript.md

Changed the method to return a list of results for the job. 
Also rewrote the tests to reflect the change. 
I made a simple implementation. I hope it is what was wanted.
This should resolve #100

Make runEach return JobResult of all Jobs

---

brigade-controller/cmd/brigade-controller/controller/controller_test.go
brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-worker/src/app.ts
brigade-worker/src/events.ts
brigade-worker/src/index.ts
brigade-worker/src/k8s.ts
brigade-worker/test/app.ts
brigade-worker/test/k8s.ts
brigade-worker/test/mock.ts
pkg/storage/kube/build.go
pkg/storage/kube/job.go
pkg/storage/kube/project.go

There were a few places where instead of using the ULID as an ID, the
system was using project + commit as an ID. That, however, is not
unique. This was resulting in incorrect data being returned by the API
server.
One of the reasons for the above was that job pods were not being
labeled with the ULID (or with the worker ID). So there was no way to
correlated a job with its worker parent or build. So this adds two new
labels on a job pod: worker and build. The build ID is also added to the
PVC for build storage.
Finally, the API server has been fixed to use the build ID instead of
the commit for finding associated jobs.
Closes #121

fix(api,controller,worker): use ULID for ID

---

pkg/brigade/project.go
pkg/brigade/project_test.go

The API server now shows the names of the secrets, but not
their values. This allows user interfaces to show which secrets are
present, but not be able to show their values.
The returned value for secrets is still a map, to accurately reflect the
structure of a secret. But the value is always "REDACTED".

fix(api): show secret names, but not values

---

README.md
docs/topics/developers.md
docs/topics/install.md

This changes our recommendation from source build to using the Helm repo
for Brigade install. It should ease the process for first-time users.

docs(*): switch recommendation to helm repo

---

brigade-worker/src/app.ts

This stops the 'after' event from firing in the event that there is no
target event handler for the given event.
There's a little bit of extra clean-up logic to make sure that PVCs and
other things are torn down properly.
Closes #21

fix(worker): stop after from firing when no hook was executed.

---

brigade-controller/cmd/brigade-controller/controller/handler.go

This sets the correct service account on the worker pod.
Closes #155

fix(controller): set service account on worker pod

---

git-sidecar/Dockerfile

Hi there,
At ApiPlatform we want to use Brigade to run some of our tests that require more power then a limit travis instance. 
We have an issue with `git@2.13.5` while executing:
```
+ git fetch origin VCS_REVISION
error: Server does not allow request for unadvertised object VCS_REVISION
```
where VCS_REVISION is a given `sha1` from github servers.
Link to the brigade PR on our repository: https://github.com/api-platform/core/pull/1507
This command does work with `git@2.15.0` which is only available with `alpine:edge` version.

Use alpine edge to get git@2.15.0

---

pkg/webhook/github.go

At present, we have no way to determine in the controller that the build created by the controller succeeded or failed. In the interim, setting the GitHub status on the PR to pending after kicking off the job will allow the build to be set up properly, then the user can implement a plugin similar to [slack-notify](https://github.com/technosophos/slack-notify) to update the build status after it's finished.
references discussion ongoing at #125

set github status to pending after creating build secret

---

brigade-api/cmd/brigade-api/main.go
pkg/api/project.go

This adds a new endpoint:
/v1/projects-build
This returns a list of projects together with the latest build for each
project. It is notably heavier processing than /v1/projects. The
returned data structure is also substantially different: It's an array
of project/build pairs represented as a map.
```json
[
{
"project": {
"id": "brigade-635e505c74ad679bb9144d19950504fbe86b136ac3770bcff51ac6",
"name": "technosophos/brigade-trello",
"repo": {
"name": "github.com/technosophos/brigade-trello",
"cloneURL": "https://github.com/technosophos/brigade-trello.git"
},
"kubernetes": {
"namespace": "default",
"vcsSidecar": ""
},
"github": {},
"secrets": {
"SLACK_WEBHOOK": "REDACTED",
"cosmosKey": "REDACTED",
"cosmosName": "REDACTED",
"trelloKey": "REDACTED",
"trelloModel": "REDACTED",
"trelloToken": …
```

feat(api): list projects with latest builds

---

charts/brigade/templates/worker-role.yaml

Annoying RBAC quirk; the PVC resource is `persistentvolumeclaims`, not `persistentVolumeClaims`.
This PR fixes worker PVC creation on Kubernetes v1.7.x and v1.8.x:
Kubernetes 1.7.x:
```
$ brig run -f brigade.js deis/empty-testbed
Started brigade-worker-01bzggaa605r80cdvg6gym49mf-master
yarn run v1.3.2
$ node prestart.js
prestart: src/brigade.js written
$ node --no-deprecation ./dist/src/index.js
Creating PVC named brigade-worker-01bzggaa605r80cdvg6gym49mf-master
FATAL: [object Object] (rejection)
error handler is cleaning up
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Kubernetes 1.8.x:
```
$ brig run -f brigade.js deis/empty-testbed
Started brigade-worker-01bzgenb74g976gj1c7zbj4cep-master
yarn run v1.3.2
$ …
```

fix(worker): fix PVC RBAC resource

---

brigade-worker/src/events.ts
brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts
brigade-worker/test/mock.ts
charts/brigade-project/templates/secret.yaml
charts/brigade-project/values.yaml

This makes it possible to disable the ability of a job to enter
privileged mode. A project can now disable the feature for all jobs.

feat(worker): allow disabling privileged mode at project level

---

brigade-worker/src/job.ts
brigade-worker/src/k8s.ts
brigade-worker/test/job.ts

When we use a container image with the `latest` tag for a job and when we run this one, then we should be able to force a pull.

feat(worker): add the ability to configure the image pull policy of a job

---

git-sidecar/rootfs/clone.sh

It prevents downloading the full repository's history. This trick speeds up builds when repos are old and big.
Travis uses the same strategy.

Limit the clone depth at 50 to speed up builds

---

git-sidecar/Dockerfile

When we switched from debian:jessie-slim to alpine:3.6, openssh was no
longer included by default. That broke git SSH support.
Closes #175

fix(git-sidecar): add openssh back in

---

charts/brigade/templates/api-deployment.yaml
charts/brigade/templates/api-service.yaml
charts/brigade/templates/controller-deployment.yaml
charts/brigade/templates/gateway-cr-service.yaml
charts/brigade/templates/gateway-service.yaml

This adds the role label to several chart members, and cleans up some of
the other labels.
Closes #167

fix(charts): add roles to services, deployments, pods

---

charts/brigade/templates/gateway-cr-deployment.yaml
charts/brigade/templates/gateway-cr-service.yaml
charts/brigade/templates/gateway-deployment.yaml
charts/brigade/templates/gateway-service.yaml

without this, both the dockerhub and github gateway services will be load balancing all gateways.

differentiate between github and dockerhub gateways

---

docs/topics/scripting.md

Currently we reference having introduced the brig tool:
Using the `brig` tool introduced above, we can see how this works.
but no such introduction currently exists.  Add an introduction to reduce
confusion.

docs(scripting): Actually introduce `brig`

---

brig/README.md

In order to successfully build `brig`, you need to clone the brigade source
into your `$GOPATH`.  Mention this in the docs to avoid confusion for folks
that are less familiar with the idiosyncrasies of building go packages.

docs(brig): Mention where the brigade source needs to be cloned

---

docs/intro/tutorial03.md

It's actually labelled "Active" not "Activate" in the GitHub UI.

tutorial03: Fix checkbox label

---

README.md

Currently you're dropped into a directory listing with a bunch of tarballs.
Dropping into index.md would be much more user friendly.

docs(README): Link to index.md instead of /docs/

---

docs/intro/tutorial04.md

Noticed the intro snippets don't work against the current build as-is; the `require` statement is necessary.

docs(intro): require `brigadier` in examples.

---

docs/topics/dockerhub.md

I think this inconsistency comes from the breakout of the cr-gateway with the latest release.
I saw that the brigade-cr gateway wasn't listening on 7744, and it also didn't use the `dockerhub` event, rather the actual string `webhook`:
https://github.com/Azure/brigade/blob/7b2f3836620ac13862e5cee4793a86cfac6b8a2e/brigade-cr-gateway/cmd/brigade-cr-gateway/server.go#L55

Correct ports and path for CR documentation

---

.gitignore
Makefile
brigade-vacuum/Dockerfile
brigade-vacuum/cmd/brigade-vacuum/commands/app.go
brigade-vacuum/cmd/brigade-vacuum/main.go
brigade-vacuum/cmd/brigade-vacuum/vacuum/vacuum.go
brigade-vacuum/cmd/brigade-vacuum/vacuum/vacuum_test.go
charts/brigade/templates/vacuum-cronjob.yaml
charts/brigade/values.yaml

This cleans old builds.
A new CronJob is added that runs the brigade-vacuum every hour. By default, the vacuum cleans up any builds older than 30 days. It removes all of the pods and secrets associated with expired builds.

feat(vacuum): add brigade-vacuum

---

brigade-api/cmd/brigade-api/main.go
brigade-gateway/cmd/brigade-gateway/server.go
charts/brigade/templates/api-deployment.yaml
charts/brigade/templates/gateway-deployment.yaml
charts/brigade/values.yaml

Discovered while fixing the default api/gateway port values in the chart that the corresponding binaries were hard-coded and thus would ignore the overrides, leaving the pods in a crash backoff loop.
```
kubectl get svc | egrep "api|gw"
NAME                         TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)          AGE
brigade-server-brigade-api   ClusterIP      10.0.148.241   <none>          7744/TCP         45m
brigade-server-brigade-gw    LoadBalancer   10.0.31.107    52.161.94.103   7745:31857/TCP   45m
$ kubectl get po | egrep "api|gw"
NAME                                             READY     STATUS             RESTARTS   AGE
brigade-server-brigade-api-c758d8756-zt6pn       0/1       Running            17         44m
brigade-server-brigade-gw-757d586dbd-crtdx       0/1 …
```

Allow API and gateway to respect port values

---

brigade-cr-gateway/cmd/brigade-cr-gateway/server.go
brigade-cr-gateway/cmd/brigade-cr-gateway/server_test.go
docs/topics/dockerhub.md
pkg/webhook/dockerhub.go

This adds support for a commit=? query param. It also adds support for
specifying project by its long (hashed) name instead of org/project.
Closes #229

fix(cr-gateway): support branch names with slashes

---

brig/README.md

As far as I have tested with 0.7.0:
- There seems like `brig run my-org/my-project` but not `brig my-org/my-project`
- There seems like `--namespace` option but not `--ns` for the `brig run` command

docs(readme): Feedbacks on README for the brig command

---

charts/brigade/templates/ingress.yaml

The ingress name was incorrect, as was the app label. Brought these back
into line with the Brigade GW.

fix(chart): fix ingress name and app label.

---

docs/topics/examples/brigade-18.js
docs/topics/examples/brigade-19.js
docs/topics/examples/brigade-20.js
docs/topics/examples/brigade-21.js
docs/topics/scripting.md

This adds a section that covers advanced event handling, like nesting
events, firing events, and declaring multiple event handlers.
It also adds information on using DinD instead of the Docker socket.

docs(scripting): add advanced events section

---

brig/cmd/brig/commands/run.go

Fixed a regression that I introduced when trimming the branch name.
Closes #254

fix(brig): don't trim short git references

---

brigade-controller/cmd/brigade-controller/controller/controller_test.go
brigade-controller/cmd/brigade-controller/controller/handler.go

On mixed clusters, this will make sure that worker nodes are only
deployed to Linux nodes in the cluster.
Closes #253

fix(controller): Label worker pods with os=linux label.

---

brigade-worker/prestart.js
charts/brigade-project/values.yaml
pkg/webhook/dockerhub.go
pkg/webhook/dockerhub_test.go

fix(cr-gateway): Remove GitHub API requirement from CR server.

---

charts/brigade/templates/api-role.yaml

In order to be able to retrieve logs througth API its needed access to `pods/logs` resource

Add pods/log resource to api role

---

brigade-worker/src/brigadier.ts
charts/brigade/templates/worker-role.yaml

pods/log permission is needed to allow the worker to clean up jobs. It
was missing in the 0.8.0 and earlier charts, and the result is a very
unhelpful error message.
Closes #186
Closes #247

fix(chart): the pod/log permission is needed on the worker's role

---

brigade-worker/src/job.ts
brigade-worker/src/k8s.ts
brigade-worker/test/job.ts
brigade-worker/test/k8s.ts
docs/topics/javascript.md

This allows you to set a `job.serviceAccount` that Kubernetes will use
to run the job.
Closes #251

feat(worker): allow overriding of the job's service account.

---

charts/brigade-project/templates/secret.yaml
charts/brigade-project/values.yaml

This removes a few curly braces from the config, and fixes the template
to not require an empty map.

ref(chart): remove curly braces

---

brigade-controller/cmd/brigade-controller/controller/informer.go
brigade-worker/src/k8s.ts
charts/brigade-project/templates/secret.yaml
docs/topics/examples/simple-event/cron/cron-event.sh
docs/topics/examples/simple-event/simple-event.sh
docs/topics/gateways.md
pkg/storage/kube/build.go
pkg/storage/kube/project_test.go
scripts/functional-test-secret.sh

Assign a type to kubernetes secrets storing configuration for projects,
builds, and jobs.
This will simplify queries and provide distinction for debugging.
```
$ kubectl get secrets
NAME                                                             TYPE                                  DATA      AGE
brigade-830c16d4aaf6f5490937ad719afd8490a5bcbef064d397411043ac   brigade.sh/project                    8         1h
brigade-brigade-api-token-t4vw8                                  kubernetes.io/service-account-token   3         1h
brigade-brigade-cr-gw-token-m8sss                                kubernetes.io/service-account-token   3         1h
brigade-brigade-ctrl-token-2z5zz                                 kubernetes.io/service-account-token   3         1h …
```

feat(*): use typed secrets for projects, builds, and jobs

---

brigade-worker/src/app.ts
brigade-worker/src/k8s.ts

Resolves Issue https://github.com/Azure/brigade/issues/287
Resolves Issue https://github.com/Azure/brigade/issues/293
Do not set the storage class to "default" by default. 
Do not set the kube storage class if it is not specified.
Destroy Build Storage PVC on error

Do not set the storage class to "default" by default ; Destroy Build Storage PVC on error

---

brigade-controller/cmd/brigade-controller/controller/handler.go
charts/brigade-project/values.yaml

This enables the vcsSidecar param by default in values.yaml. This will
cause the worker to use the vcsSidecar as an init container. Omiting it
prevents the worker from declaring a sidecar pod, which means passing
the brigade.js file is incumbent upon the gateways.
Closes #305

fix(chart): turn vcsSidecar on by  default

---

brigade-worker/src/k8s.ts

A recent PR merge broke one of the unit tests, and the root of the
problem was that a value wasn't being tested for existence.

fix(worker): fix broken unit test

---

brigade-controller/cmd/brigade-controller/controller/controller.go
brigade-controller/cmd/brigade-controller/controller/controller_test.go
brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-controller/cmd/brigade-controller/main.go
charts/brigade/templates/controller-deployment.yaml
charts/brigade/templates/worker-role.yaml
charts/brigade/values.yaml
pkg/storage/kube/project_test.go

This makes it possible to configure the service account used by the
worker. The main change is to the controller, which now accepts a worker
service account.
Closes #157

fix(chart): make worker service account configurable

---

charts/brigade-project/values.yaml
pkg/brigade/project.go
pkg/storage/kube/project.go
pkg/storage/kube/project_test.go
pkg/webhook/client.go
pkg/webhook/client_test.go

This adds support for specifying the API endpoint URL for GitHub
Enterprise. If none is set, it defaults to regular GitHub API.
Closes #241

fix(github): support using GitHub Enterprise

---

charts/brigade/templates/vacuum-cronjob.yaml

- adds successfulJobsHistoryLimit to the template
- adds failedJobsHistoryLimit to the template

charts/brigade: add job limits for vacuum

---

brigade-controller/cmd/brigade-controller/controller/controller_test.go
brigade-controller/cmd/brigade-controller/controller/handler.go

This PR fixes the worker image name creation on the controller.
At this moment the worker image name creation assumes some fixed naming that makes other possible image names fail.
For example, if we use an image like `dist.custom.registry.io:5000/brigade/worker:d454e0a8cfd92deaad893a39c2ad5243d97dc7fd` the current way will not parse correctly because it doesn't assume that there is a port on the registry, so when it splits by `:` and takes the second splitted substring, it's not taking the real tag.
Appart from that I think there it's not a real or correct way (or at least I can't imagine one) to split registry and name. Examples:
* azure/brigade-worker:1234
* myregisitry.com/azure/brigade-worker:1234
* myregistry/brigade-worker:1234
I could not say in the first and the last one what is a …

Fix worker image name creation on controller

---

charts/brigade/templates/gateway-cr-role.yaml
charts/brigade/templates/gateway-github-role.yaml

- cr.enable was being ignored in the service and role
- gw.enable was being ignored in the role

charts/gateway: use enable flag on all resources

---

charts/brigade-project/templates/secret.yaml

This fixes the issue https://github.com/Azure/brigade/issues/345
The values on a secret have to be base64 encoded.

Create the worker options on base64

---

docs/topics/install.md

This documents how to use nfs-provisioner to back storage and cache to
an NFS instance.

docs(install): document using NFS for volume storage

---

brig/cmd/brig/commands/proxy.go
pkg/portforwarder/portforwarder.go

WIP implementation of `brig proxy` that currently starts tunnels to the API and Kashti.
This way, you don't have to expose the dashboard publicly, and connecting is done through a single command.

Add brig proxy command to start tunnels to api and kashti

---

brigade-controller/cmd/brigade-controller/controller/controller_test.go
brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-worker/src/k8s.ts

This fixes the issue https://github.com/Azure/brigade/issues/355
Firstly, on the controller, when creating the worker, it adds an environmental variable called `BRIGADE_SERVICE_ACCOUNT`, so the worker knows how to launch the job pods.
Secondly, the worker reads that environmental variable when it creates the job pods. Regarding this, I don't know if it's correct or if this env should be read on `index.ts` (with the rest of the envs) and pass it somehow  to the JobRunner.

Create worker with sa env

---

charts/brigade-project/templates/secret.yaml
charts/brigade-project/values.yaml

Previously, this always used `:latest` for the vcs sidecar tag. Now it
uses .Chart.Version. In order to not use any vcsSidecar, you now have
to set the version to NONE, which is breaking, but probably an unused
feature anyway.

fix(chart): BREAKING set vcsSidecar tag to version

---

docs/topics/developers.md

When I was setting this up, I had to copy/paste each line which took a bit more time. It's nice to be able to spot-check the commands and then run them all at once.

Make clone instructions more copy/paste-able

---

brig/cmd/brig/commands/run.go

After the change made on 0.10.0 that the revision is not the commit but the commit and the ref, brig no longer could set the specific commit. This PR allows specifying both.

Add the ability to set the commit and ref on brig run command

---

pkg/webhook/github.go

GitHub gateway now only sets a GitHub status _if the hook fails to
trigger_. Before, we would trigger a status message for any event that
is successfully received. But this was resulting in spurious status
messages triggered on events that were not actually building anything.

fix(github-gateway): reduce status messages

---

brigade-worker/src/app.ts
brigade-worker/src/index.ts
brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts

This is a minor refactor to move an env var reference to the top.

ref(worker): move env var processing to the top

---

brig/cmd/brig/commands/run.go

One of the common Brig problems occurs when Brig creates an event, but
the controller does not start the worker. This adds a single line of
verbose output indicating (a) when Brig starts waiting for the worker,
and (b) what pod it expects to start as a worker.
Partially addresses #368

fix(brig): add verbose output for waiting

---

brig/cmd/brig/commands/proxy.go

Remove hardcoded default namespace for proxy cmd

---

brigade-worker/package.json
brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts
brigade-worker/yarn.lock

This moves us from the typescript-node to client-node Kubernetes
packages. The package was renamed to better reflect its use for both TS
and JS.
Closes #362

ref(worker): use client-node

---

docs/topics/workers.md

It appears that the documentation for custom workers (`docs/topics/workers.md`) instructs users to `COPY` their custom files to the wrong location.  The location should be `/home/src/dist` rather than `/home/dist`.

Correct non-npm JS installation instructions in custom workers

---

brig/cmd/brig/commands/build_list.go
brig/cmd/brig/commands/build_logs.go
brig/cmd/brig/commands/run.go
pkg/brigade/build.go
pkg/brigade/job.go
pkg/storage/kube/build_test.go
pkg/storage/kube/job_test.go
pkg/storage/kube/project_test.go
pkg/storage/kube/store_test.go
pkg/storage/kube/worker.go
pkg/storage/kube/worker_test.go

This gives Brig a new `build logs` subcommand for dumping logs.
Along the way, I backfilled a bunch of tests, too.

feat(brig): add 'brig build logs'

---

Gopkg.lock
Gopkg.toml
brig/cmd/brig/commands/run.go

This adds a progress indicator on 'brig run' output by collapsing repeat
entries.

feat(brig): add progress meter to run output

---

brigade-worker/src/job.ts
brigade-worker/test/job.ts

The regexp for job names was wrong. This fixes it and fixes the tests.
Closes #402

fix(worker): report error if job name is not DNS name

---

.gitignore
Makefile
brig/Dockerfile
brig/rootfs/README.md

This adds the necessary Dockerfile and Makefile changes so that we can
also build a containerized Brig, which is necessary for our CronJob
gateway.

feat(brig): add brig container

---

brigade-worker/src/job.ts
brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts
docs/topics/javascript.md
docs/topics/secrets.md

Currently, `Job`s in `brigade.js` files can only have key/value pairs in the `env` object. This means that accessing any secrets either needs to dynamically pulled from a storage system like Vault inside the container, or needs to be saved directly in the project in a `values.yaml` file that can't be committed to git due to containing secrets.  Many clusters will already contain a set of secrets for use across a number of deployments, especially if Brigade is being used for CI--many CI pipelines will reuse the same set of secrets.
This PR allows `secretKeyRef`, `configMapKeyRef`, and the other Kubernetes value references to be used in a job's `env` object.  This also comes with documentation updates and passing tests.  We are using this code right now internally and it works fine.
Note: …

fix(worker): Allow secretKeyRef and configMapKeyRef as Job env vars

---

README.md

This adds a link to Brigade-Cron.
(Submitted via GitHub editor)

docs(README): add brigade-cron gateway

---

Gopkg.lock
brig/cmd/brig/commands/app.go
brig/cmd/brig/commands/run.go
brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-worker/src/app.ts
brigade-worker/src/events.ts
brigade-worker/src/index.ts
brigade-worker/src/k8s.ts
brigade-worker/src/logger.ts
brigade-worker/test/k8s.ts
pkg/brigade/build.go
pkg/storage/kube/build.go
pkg/storage/kube/build_test.go

The `brig` CLI is very verbose in its logging.  While this is helpful for developers, it makes Brigade tough to integrate into other systems that need to offer more limited and meaningful output to users.
This PR adds an `-l` option to `brig`, letting the caller specify the log levels to print to stdout.  The permitted log levels are `ALL`, `LOG`, `INFO`, `WARN`, `ERROR`, or `NONE`, and all logs at levels equal to or above the level specified are printed.  The log level specified by the CLI is passed from the CLI to the controller, is added to the build's `Secret`, and is passed to the worker container.
I ran all of the Go and Typescript unit tests and ran a live build with a specified log level against our staging Kubernetes cluster.
Edit: Turns out this is slightly less necessary after …

feat(brig): Allow selection of log level to print (-l)

---

docs/topics/javascript.md

The Javascript docs say that `timeout` on `Job` is in seconds.  It appears to actually be in milliseconds, from looking at the code and my own experience adding timeouts.

fix(docs): Update "timeout" documentation

---

docs/topics/storage.md

I didn't realize that I couldn't rely on PVC in my cluster (AWS EBS backed). This documentation change links out to the k8s support table and warns people that, unless you use NFS or are on Azure, you probably will have a bad time.

Link to PVC Access Mode Table

---

brigade-worker/src/app.ts
brigade-worker/src/index.ts
brigade-worker/src/job.ts
brigade-worker/src/k8s.ts
brigade-worker/src/logger.ts
brigade-worker/test/job.ts
brigade-worker/test/k8s.ts

The error handler was not waiting for other events to finish. This
removes the process error code handling to the "exit" event, and allows
the "error" event to schedule jobs and other things that will require a
next-tick. It also intentionally bypasses the "after" event once an
error code is set. This ensures that if "error" triggers, "after" won't.
Closes #364

fix(worker): allow jobs during error handler

---

brig/cmd/brig/commands/run.go
brigade-controller/cmd/brigade-controller/controller/controller_test.go
brigade-worker/src/job.ts
brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts
docs/topics/javascript.md

Adds `Job.args: []string` so that users can set `args` on a container directly, bypassing the `tasks` scripting behavior.
Also fixes a few test errors. 
Closes #411

feat(worker): support passing args through jobs

---

brigade-worker/src/brigadier.ts
brigade-worker/src/job.ts
brigade-worker/src/k8s.ts
brigade-worker/test/brigadier.ts
brigade-worker/test/mock.ts

We needed a way to output the logs of a Job after the fact&mdash;in particular, for reporting on failed jobs.  This adds a `logs()` method to the Typescript `Job`.
Note that this does not seem to be fully working, even though the tests pass.  When I run this code:
```javascript
let slack = new Job("slack-notify", "technosophos/slack-notify:latest", ["/slack-notify"]);
slack.storage.enabled = false;
slack.useSource = false;
slack.env = {
SLACK_WEBHOOK: project.secrets.SLACK_WEBHOOK,
SLACK_COLOR: "red",
SLACK_CHANNEL: "brigade-failures",
SLACK_TITLE: `Build failure`,
SLACK_MESSAGE: `Build ${event.buildID} failed to build.`
};
await slack.run()
let logs = await slack.logs();
console.info(`This is a test: ${logs}`);
```
I get this output:
```
Event created. Waiting for worker pod named …
```

feat(brigade.js): Retrieve logs from Job run

---

brigade.js

An earlier commit accidentally masked the event object on error. This
fixes that bug.
Closes #424

fix(brigade.js): unmask the event object

---

charts/brigade-project/templates/secret.yaml
charts/brigade-project/values.yaml

Related to https://github.com/Azure/brigade/issues/419.
Using `.stringData` makes working with Secret data simpler because clients don't need to base64 encode values back-and-forth when editing.
As a Brigade user using Helm, this improves readability of the templated Helm chart.
As a Brigade user not using Helm, I can copy templates/secret.yaml to create a new project and easily edit my project configuration in plain text.
Tested by uncommenting most variables in the default values.yaml and running:
```
helm template charts/brigade-project -n myProject | kubectl apply --dry-run --validate -f -
```

Use .stringData to avoid base64 encoding & decoding.

---

brigade-worker/src/job.ts
brigade-worker/src/k8s.ts
brigade-worker/test/job.ts
brigade-worker/test/k8s.ts

This adds the ability to add annotations to brigade job pods from the brigade.js brigade-worker.
We ran across the need for this to be able to run workloads in ec2 and take advantage of [kube2iam](https://github.com/jtblin/kube2iam#kubernetes-annotation), which needs an annotation.
I tested this in minikube, adding a dummy annotation to my brigade pod:
```javascript
// Create a new job
var node = new Job("copy-staging-db");
// snip
node.tasks = [
'env',
'hostname'
];
node.annotations = {
'test/annotation': "annotations/go/here"
};
// We're done configuring, so we run the job
node.run(); 
```
and saw the annotation applied on the pod via the dashboard
I'm not currently sure this adversely affects anything else - it doesnt seem like it does, the tests were testing to ensure that annotations …

Add job annotations

---

charts/brigade-project/templates/secret.yaml

This causes massive breakage on:
- bools
- numeric strings
- anything with a reserved character in YAML
So we quote all of the values that could be problematic.

When base64 was removed, no escaping was done on any values.

---

pkg/api/project.go
pkg/merge/channels.go
pkg/merge/channels_test.go
pkg/storage/kube/apicache/cache.go
pkg/storage/kube/apicache/cache_test.go
pkg/storage/kube/apicache/liststore.go
pkg/storage/kube/apicache/liststore_test.go
pkg/storage/kube/apicache/pods.go
pkg/storage/kube/apicache/pods_test.go
pkg/storage/kube/apicache/secrets.go
pkg/storage/kube/apicache/secrets_test.go
pkg/storage/kube/build.go
pkg/storage/kube/build_test.go
pkg/storage/kube/store.go
pkg/storage/kube/store_test.go
pkg/storage/mock/storage.go
pkg/storage/mock/storage_test.go
pkg/storage/storage.go

This PR introduces api caching using the "k8s.io/client-go/tools/cache" package.
As a result of #433 I saw the necessity to optimize the route "/projects-build".
After not seeing any improvements via the "naive" implementation I've setup some benchmarks to analyse the problem.
I figured out that there were way too many requests towards the kubernetes api to fetch secrets, each of these was taking about 200ms.
The solution I'd like to introduce is caching all secrets of the brigade namespace for some reasonable time. This way there are zero network requests left during the invocation of "projects-build".
All in all this reduces the response time for our environment with a dozen pipelines from 10 seconds to 100ms.
Everything I touched is 100% covered.
I'm looking forward to getting this PR …

Improve brig api performance as seen in #433 by introducing caching

---

brigade-controller/cmd/brigade-controller/controller/controller_test.go
brigade-controller/cmd/brigade-controller/controller/handler.go
charts/brigade-project/templates/secret.yaml
charts/brigade-project/values.yaml

This adds a parameter to the project that allows projects to declare
image pull secrets for the vcsSidecar (and worker)
Closes #445

feat(controller): allow per-project image pull secrets for worker

---

docs/topics/github.md

Update the `github.md` file to include the `closed` event that was added in this commit: https://github.com/Azure/brigade/commit/3c9db0676ef3d832ab68df427339a220f1991143

Docs update: `pull_request` fires `closed` event

---

brig/cmd/brig/commands/build.go
brig/cmd/brig/commands/project.go
brig/cmd/brig/commands/proxy.go
brig/cmd/brig/commands/rerun.go
brig/cmd/brig/commands/run.go
brig/cmd/brig/commands/version.go

This adds `brig rerun BUILD_ID`, which allows a replay of an older
build.
Closes #463

feat(brig): add rerun command

---

brigade-worker/prestart.js

It appears to be a bug in `prestart.js` that only returns the script if the file is empty.

Fix the check for data in prestart.js

---

pkg/storage/kube/job.go
pkg/storage/kube/worker.go
pkg/storage/mock/storage.go
pkg/storage/mock/storage_test.go
pkg/storage/storage.go

Hi!
This PR adds 2 new methods to the `Storage` interface API. `Storage.GetJobLogStreamFollow` and `storage.GetWorkerLogStreamFollow`. Just adds the `follow` flag to Kubernetes so we retrieve an `io.ReadCloser` that will follow the logs.
I created 2 new methods instead of adding a flag on the `Get(Worker|Job)LogStream` methods so the API continues being compatible with the current users and doesn't break current usage.
I don't think that requires testing this part, just uses the client-go (that it's very well tested :heart:), without domain logic at all.

Add log follows on worker and job Storage API

---

brigade-worker/package.json
brigade-worker/prestart.js
brigade-worker/yarn.lock

This PR enables adding custom dependencies you can `require` and use from `brigade.js`, without [creating a custom Brigade worker](https://github.com/Azure/brigade/blob/master/docs/topics/workers.md).
This works by adding your dependencies in a `brigade.json` file (similar to a `package.json` file). The file will be parsed by the pre-start script and its dependencies will be added to the worker's dependency tree.
To test this:
- build the worker image and use it as the `BRIGADE_WORKER_IMAGE` in your Brigade deployment (to quickly test this, you can directly `kubectl edit deployment` the Brigade controller and change the environment variable `BRIGADE_WORKER_IMAGE`. New workers created will be based on this image)
- create a new project with the following minimum (you can use [this …

Enable custom dependencies for the brigade worker

---

brigade-worker/prestart.js

A recent change altered the precedence. This sets it back to the
correct precedence

fix(worker): fix the precedence order

---

docs/topics/javascript.md

The documentation stated that `imagePullSecrets` type is `string`, but it is `string[]` (array of strings).

fix(docs): Job imagePullSecrets is a string array, not string

---

charts/brigade/templates/gateway-github-role.yaml

Github GW shoud have permissions to watch and list pods
I had a next errors in logs
- for list:
```
E0608 23:58:24.777474       5 reflector.go:205] github.com/Azure/brigade/pkg/storage/kube/apicache/liststore.go:36: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:brigade:brigade-brigade-github-gw" cannot list pods in the namespace "brigade": Unknown user "system:serviceaccount:brigade:brigade-brigade-github-gw"
```
- for watch:
```
E0608 23:59:39.707864       5 reflector.go:315] github.com/Azure/brigade/pkg/storage/kube/apicache/liststore.go:36: Failed to watch *v1.Pod: unknown (get pods)
```

fix(github): rolebinding resources

---

Gopkg.lock
brig/cmd/brig/commands/rerun.go
brigade-cr-gateway/cmd/brigade-cr-gateway/server_test.go
brigade-worker/yarn.lock
pkg/brigade/project.go
pkg/storage/kube/project.go
pkg/storage/kube/project_test.go
pkg/storage/mock/storage.go
pkg/storage/mock/storage_test.go
pkg/storage/storage.go

Previously, storage did not need to know much about projects. This adds
better support for projects to the storage layer, and adds a
CreateProject function.

fix(storage): Improve storage layer for projects

---

brig/README.md
docs/index.md
docs/intro/install.md
docs/intro/overview.md
docs/intro/tutorial01.md
docs/intro/tutorial02.md
docs/intro/tutorial03.md
docs/intro/tutorial04.md
docs/readme.md

Suggesting a few edits to the docs, based on problems I ran into when running through the Intro and Brig guides:
* use of Index vs Readmes makes browsing harder - hence links to the [readable version](https://azure.github.io/brigade/) should be prominent
* navigational flow through docs is confusing, so I added more Prev/Next links to the intro pages
* I couldn't find the Brig docs, so I referenced them from the Install Guide
* when `make bootstrap brig` failed, I wasn't sure how to resolve. [this issue helped](https://github.com/Azure/brigade/issues/447), so I referenced it from the Brig docs

docs(ux): navigation and installer help

---

README.md
docs/intro/install.md

Small follow up to #509 - to highlight the site at [https://azure.github.io/brigade](https://azure.github.io/brigade)
---
That site is  more navigable and user-friendly, so this updates the root README to use that as the
primary docs URL.

docs(README) update main docs link

---

README.md

Point all README.md documentation links to the site https://azure.github.io/brigade.
Also fix markup in the first link. This was initially the main point, but I went a bit overboard with this: please let me know if I did.
This is related to #510

docs(README) Point all docs links to azure.github.io/brigade

---

brigade-worker/src/job.ts

This is a fix for issue #517. I opted to directly set the name to lowercase for the user rather than allow them to make a mistake

517: fix for job name error cause by mixed case job names

---

brigade-worker/src/job.ts
brigade-worker/test/job.ts
brigade-worker/test/k8s.ts
docs/topics/javascript.md

This allows `job.storage.path` and `job.cache.path` to be written in
scripts, rather than be hard coded.
I marked this as experimental in case we have to back this out. The main reason it was read-only at the beginning was to prevent confusion as to where things were mounted. But as #515 point out, the benefits of making this easily specifiable outweigh the risks, I think.
Closes #515

feat(worker): allow setting storage and cache paths

---

brig/cmd/brig/commands/proxy.go

This breaks backwards compatibility, but the convention for feature flags has been to use kebab-case, so I figured we should probably bring this in line with the rest of the feature flags.

use kebab case for --kashti-namespace

---

brigade-worker/prestart.js

Using fallback script in configmap will always fail as prestart.js assumes /etc/brigade-default-script to be a file, but it is a directory (since the configmap is mounted as a volume).
Simple fix: assume the file inside the configmap is named brigade.js (to follow naming from repo script) and update the path to /etc/brigade-default-script/brigade.js
Closes #528

updated fallback script path to look for brigade.js instead of directory

---

docs/topics/scripting.md
docs/topics/workers.md

This PR adds documentation around using a `brigade.json` file to add custom dependencies to a Brigade worker.
closes #497

Add docs on brigade.json

---

Gopkg.lock
Gopkg.toml
brigade-api/cmd/brigade-api/filter.go
brigade-api/cmd/brigade-api/main.go
pkg/api/build.go
pkg/api/build_test.go
pkg/api/healthz.go
pkg/api/job.go
pkg/api/job_test.go
pkg/api/project.go

This PR ports the API framework to a set of libraries that will generate Swagger/OpenAPI spec for consumers of the API. 
This addresses Issues #353 and #354, adding support and making the methods more discoverable.

Add Swagger support to API

---

brigade.js

This adds the build ID to the GitHub status message so that we can debug
builds more effectively.

fix(brigade.js): add build ID for debugging broken builds.

---

brig/cmd/brig/commands/dashboard.go

for{} causes the main loop to constantly claim clock cycles, whereas
select{} causes the goroutine to block and puts it to sleep, which is
the intention.

use select{} instead of for{}

---

charts/brigade/Chart.yaml
charts/brigade/templates/controller-deployment.yaml
charts/brigade/templates/vacuum-cronjob.yaml
charts/brigade/templates/vacuum-role.yaml
charts/brigade/templates/worker-role.yaml
charts/brigade/values.yaml

In some situations a user may want to create the service accounts outside
of the helm process.
Currently, this isn't possible with brigade as brigade will always attempt
to create the service accounts.
This update introduces new values to conditionally enable/disable the
creation of the service accounts for worker nodes and the vacuum.
Signed-off-by: Ian Duffy <ian@ianduffy.ie>

Make service account creation conditional

---

brig/cmd/brig/commands/dashboard.go

Fixes this:
```
gometalinter --config ./gometalinter.json ./...
brig/cmd/brig/commands/dashboard.go:1::warning: file is not goimported (goimports)
make: *** [test-style] Error 1
```

fix(style): change import formatting to satisfy goimport fails

---

brigade.js

GitHub was failing to update builds on error because the error message
was too long.
Closes #555

fix(brigade.js): shorten the error message

---

Gopkg.lock
Gopkg.toml
README.md
brig/cmd/brig/commands/project_create.go
brig/cmd/brig/commands/project_create_test.go
brig/cmd/brig/commands/testdata/project_secret.json
brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-controller/cmd/brigade-controller/controller/handler_test.go
docs/topics/projects.md

This adds `brig project create` to create projects from interactive
prompts or from an existing secret.
See #504

feat(brig): Interactive prompt for creating projects 

---

brig/cmd/brig/commands/build_list.go
brig/cmd/brig/commands/project_get.go

This add `brig build list PROJECT_ID`.
It also modifies `brig project get` to return a Secret, which is the
default format we work with, rather than a one-off representation.

feat(brig): list builds by project

---

brig/cmd/brig/commands/project_get.go

This returns a formatted JSON secret instead of a dump of an internal
struct.
See #541

feat(brig): return JSON from 'brig project get'

---

docs/topics/examples/advanced-01.js
docs/topics/examples/advanced-02.js
docs/topics/examples/advanced-03.js
docs/topics/examples/advanced-04.js
docs/topics/examples/advanced-05.js
docs/topics/scripting_advanced.md

This provides a place for advanced JS examples and ideas.
See #480

docs(javascript_advanced): create an advanced JS guide

---

brigade-vacuum/cmd/brigade-vacuum/commands/app.go
brigade-vacuum/cmd/brigade-vacuum/vacuum/vacuum.go
brigade-vacuum/cmd/brigade-vacuum/vacuum/vacuum_test.go

There was a discrepancy between whether the default value for max builds was -1 or 0. As a result, `VACUUM_MAX_BUILDS` was always overridden by the default `-m` value.
Closes #576

fix(vacuum): set default max builds to -1

---

brigade.js

Adds a link to the official Kashti to show the status of the build.

feat(brigade.js): Add link to Kashti

---

docs/intro/tutorial01.md

Sent it to the [official pip docs](https://pip.pypa.io/en/stable/installing/) instead.

Fixed pip install link

---

brigade-worker/src/events.ts
brigade.js

Newer typescripts (3+) complain if the `on` method isn't overridden.
Also, the windows binary was not correctly given the exe extension,
which is causing failed brig prod builds.

fix(brigade, worker): fixing a few minor nits

---

brig/cmd/brig/commands/rerun.go

This provides a way to rerun a payload, but replace the script file.
This ought to greatly improve the debugging experience when a script
fails.

feat(brig): add -f flag to rerun command

---

charts/brigade/values.yaml

A recent fix standardized on maxBuilds=0 meaning no builds are kept. But the chart sets maxBuilds=0 by default. This changes the default to -1.

fix(chart): set max builds to -1 by default

---

brig/cmd/brig/commands/project_create.go
brigade-worker/prestart.js

In the course of debugging this, I noticed a case in the worker where the error data was getting lost.
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

fix(brig): set a default sidecar

---

brig/cmd/brig/commands/project_create.go

This fixes a bug in the shared secret generation logic.
Closes #574
Closes #597

fix(brig): generate shared secret when none exists

---

brigade-vacuum/cmd/brigade-vacuum/commands/app.go
brigade-vacuum/cmd/brigade-vacuum/vacuum/vacuum.go
brigade-vacuum/cmd/brigade-vacuum/vacuum/vacuum_test.go
charts/brigade/templates/vacuum-cronjob.yaml

vacuum skips deleting currently running builds if skipRunningBuilds is true (false by default).
Previously, vacuum deletes all builds regardless of their phase even if running or pending.

vacuum skips deleting currently running builds if skipRunningBuilds is true

---

docs/topics/github.md

This adds some clarity around `kube-lego` and `cert-manager` and points to docs for AKS and GKE.
Let me know if the wording is clear enough.
closes #607

Add more info on kube-lego and cert-manager

---

README.md

[Brigade-exporter](https://github.com/slok/brigade-exporter) adds [Prometheus](https://prometheus.io) support to Brigade.

Add brigade-exporter to related projects section on the readme

---

brigade-worker/src/k8s.ts

Build storage class initializes its variables in BuildStorage.create() after loading project but when project does not exists or there is error in loading project, build storage is not created so variables are left uninitialized e.g (logger). Later when error is handled in app.ts , it tries to destroy build storage. In this case the storage wasn't initialized in the first place which terminates worker in the middle of exception.

fix BuildStorage in brigade worker to prevent crash when project load fails

---

brig/cmd/brig/commands/rerun.go
brig/cmd/brig/commands/run.go
pkg/script/delegated_runner.go

You can write any code that reuses `brig run`, to delegate running distributed scripts onto brigade, but with a more efficient and type-safe way.
This is a backward-compatible change, irrelevant to the feature of `brig run` and `brig rerun` commands.
This tweaks the original implementation of `brig run`, removing global variable references, extracting almost all the logics of it into the brand-new `brigade/script` go pkg.
So that it can be imported by other golang projects.
The script runner is now named `DelegatedRunner`, to make it extra clear to users, that the runner delegates a script to brigade, rather than running it in place.
The basic usage of this pkg, and how the body of `brig run` look like now, is:
```
runner, err := script.NewDelegatedRunner(kc, destination, ns, noProgress, …
```

feat(brig): `brig run` as a go library

---

brig/cmd/brig/commands/rerun.go
brig/cmd/brig/commands/run.go
pkg/script/delegated_runner.go

`ScriptRunner` now exposes `ScriptLogDestination` for woker pod logs, and `RunnerLogDestination` for logs of the script runner itself.
This is a follow-up for #623 that was started from #622

feat(lib): alternative destination for script runner logs

---

brig/Dockerfile
brigade-api/Dockerfile
brigade-controller/Dockerfile
brigade-cr-gateway/Dockerfile
brigade-github-gateway/Dockerfile
brigade-vacuum/Dockerfile
git-sidecar/Dockerfile

Alpine 3.8 contains an important security update which fixes a potential [remote execution](https://justi.cz/security/2018/09/13/alpine-apk-rce.html).

Update alpine images

---

git-sidecar/rootfs/gitssh.sh

Fixes #646 
Please see #646 for a detailed explanation of the problem. The TLDR is:
```
/home/src # echo ${BRIGADE_REPO_KEY} | sed 's/\$/\n/g'
-----BEGIN RSA PRIVATE KEY----- MIIJKQI <snip> l4UmoT/ -----END RSA PRIVATE KEY-----
/home/src # printf "%s" "$BRIGADE_REPO_KEY" | sed 's/\$/\n/g'
-----BEGIN RSA PRIVATE KEY-----
MIIJKQI
<snip>
l4UmoT/
-----END RSA PRIVATE KEY-----
```
Note how the `echo` doesn't properly show the newlines, but `printf` does.
This seemed like a good solution because it works when the secret has explicit `$` values, or if we allow k8s to insert the newlines for us.
In both cases, it produces a key with the proper newlines.

Fix invalid_format for Git SSH Keys.

---

brigade.js

Fixes bug wherein the last few Brigade releases didn't properly proceed, on account of referencing `e.event` (an Event object has no field `event`; rather, `type` is what we are after.)
Also, use `e.revision.ref` instead of parsing payload.

fix(brigade.js): change e.event to correct e.type

---

Makefile
brigade.js

Perhaps it would be valuable to append `.exe` at the build stage such that Windows developers don't have to rename when building locally, as opposed to renaming at the release stage.

ref(Makefile/brigade.js): append .exe to Windows binary at build stage

---

README.md

To make managing the version of `brig` easier, we @Ibotta created https://github.com/Ibotta/asdf-brig .
`asdf` if a pretty cool [project](https://github.com/asdf-vm/asdf) that takes a plugin-driven approach to replace tools like `nvm`, `rbenv`, `tfenv`, etc. with a single tool.

Reference asdf-brig in README

---

brigade-worker/src/k8s.ts

Fixes issue #469. 
Added a check for `null` which will set `value` in Kubernetes pod env section to an empty string, instead of the default behavior indicated in issue #469 which was invalid and would cause an error. 
Please note I had some problems getting the dev environment set up, and haven't been able to test this locally as of yet.

Kubernetes error caused by Job.env{} empty var

---

brig/cmd/brig/commands/project_create.go

Assigning the error and making a conditional if on it and returning nil in the end is more work than just returning the error and as the method `store.CreateProject(proj)` already returns the error we could avoid that.

Fix golint warning: redundant if ...; err != nil check, just return error instead.

---

brigade-worker/src/index.ts

This is more of a PR/proposal hybrid, seeking feedback.
I've encountered the case recently while handling the `check_suite`/`check_run` webhooks courtesy GitHub's Checks API (via the [brigade-github-app](https://github.com/Azure/brigade-github-app)) wherein the ref (or, `head_branch` for these particular webhooks) is `null`.  
Frequently, the check suite/run is for a PR from a fork, or at least a topic branch.  Therefore, although the initial `brigade-worker` pod runs fine with the ref as `null` (it simply defers to the commit SHA provided), it then passes a default of `refs/heads/master` to all Job pods.  Note that a provided ref currently takes precedence over the provided commit SHA, as seen in `git-sidecar`'s [clone.sh](https://github.com/Azure/brigade/blob/master/git-sidecar/rootfs/cl …

ref(brigade-worker): don't supply a default ref

---

brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-controller/cmd/brigade-controller/controller/handler_test.go

It exposes NewWorkerPod from controller, so that a custom controller can call it (related to #662 ).
We could have it in a separate repository under Azure in the future, if necessary though.
Please let me know your thoughts on this.

feat(controller): export NewWorkerPod

---

brigade-worker/src/job.ts
brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts
docs/topics/javascript.md

Now we can add also resource limits to the jobs:
```js
job.resourceRequests.memory = "3Gi";
job.resourceRequests.cpu = "1";
job.resourceLimits.memory = "6Gi";
job.resourceLimits.cpu = "3";
```
Also fixes the issue of only setting request resources on the container pod specif you set CPU **and** memory. Now if any of those two exist it sets the ones described.
Updated the docs to show how to add resources to the jobs

Add resource limits to job

---

Gopkg.lock
brig/cmd/brig/commands/build_delete.go
brig/cmd/brig/commands/build_delete_all.go
brigade-vacuum/cmd/brigade-vacuum/vacuum/vacuum.go
docs/topics/developers.md
pkg/storage/kube/build.go
pkg/storage/kube/build_test.go
pkg/storage/mock/storage.go
pkg/storage/storage.go

Implements #586 
Notes:
- `brig build delete` will delete the BuildID regardless of its state
- `brig build delete-all` will delete only non-running Builds from Project
- there was some code in vacuum about Build deletion - moved that to `pkg/storage/kube` so it can be used from both vacuum and brig
many thanks to @radu-matei for guidance and encouragement!

brig build delete BuildID and brig build delete-all ProjectID

---

brigade-vacuum/cmd/brigade-vacuum/commands/app.go
brigade-vacuum/cmd/brigade-vacuum/vacuum/vacuum.go
brigade-vacuum/cmd/brigade-vacuum/vacuum/vacuum_test.go

As per discussion on #698
- modified vacuum.Run to not return the number of deleted builds. #695  modified deleteBuild behavior and this led to test inconsistencies
- refactored tests to explicitly check for deleted/existent pods
- the only downside is that vacuum execution now does not report the number of deleted builds. However, relevant deletion messages are logged through deleteBuild, so I guess there's not much harm in that

Modify vacuum.Run to not return the number of deleted builds

---

charts/brigade/templates/api-deployment.yaml
charts/brigade/templates/controller-deployment.yaml

This avoids the following upgrade error due to the new label pattern introduced post-v0.18.0:
```
$ helm upgrade brigade-server charts/brigade
Error: UPGRADE FAILED: Deployment.apps "brigade-server-brigade-api" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"role":"api", "app.kubernetes.io/name":"brigade-server-brigade-api"}: `selector` does not match template `labels` && Deployment.apps "brigade-server-brigade-ctrl" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"role":"controller", "app.kubernetes.io/name":"brigade-server-brigade-ctrl"}: `selector` does not match template `labels`
```

fix(charts/brigade): add legacy label in for upgrades

---

brig/cmd/brig/commands/project_create.go
pkg/storage/kube/project.go
pkg/storage/kube/project_test.go
pkg/storage/mock/storage.go
pkg/storage/storage.go

Proposed fix for #667 
Need a second opinion [here](https://github.com/dgkanatsios/brigade/blob/fix/project-create-replace/brig/cmd/brig/commands/project_create.go#L157) and [here](https://github.com/dgkanatsios/brigade/blob/fix/project-create-replace/brig/cmd/brig/commands/project_create.go#L165)
If I return the errors themselves, cobra will display usage info, which should not happen. So, I'm returning nil error and displaying a message instead. Is this sufficient?

fixed brig project create --replace

---

Makefile
brigade.js
golangci.yml

We've had good success with [golangci-lint](https://github.com/golangci/golangci-lint) in other [projects](https://github.com/deislabs/duffle), so proposing the switch here as well.

ref(Makefile): switch to golangci for linting

---

brigade-worker/src/job.ts

This changes the error message that is shown when an invalid job name is entered so it mentions that only lowercase letters are allowed.

Update invalid job name error message.

---

charts/brigade/templates/api-deployment.yaml
charts/brigade/templates/api-role.yaml
charts/brigade/templates/controller-deployment.yaml
charts/brigade/templates/controller-role.yaml
charts/brigade/templates/gateway-cr-deployment.yaml
charts/brigade/templates/gateway-cr-role.yaml
charts/brigade/templates/gateway-github-deployment.yaml
charts/brigade/templates/gateway-github-role.yaml
charts/brigade/values.yaml

In my environment RBAC and service accounts cannot be created via helm so I have added the ability to not create the service accounts as well as set their name.

allow configuring the service account in the helm chart

---

docs/topics/index.md
docs/topics/scripting.md

As I was writing the doc for #721 noticed a couple of minor things that can be improved in the documentation
- first of all, scripting_advanced.md isn't linked from anywhere, so I added that on index
- same with storage.md
- workers.md is only mentioned on scripting.md and could get some love by getting an index link as well
WDYT?

small docs refactor

---

Gopkg.lock
Gopkg.toml

**What this PR does / why we need it**: Updates [`bacongobbler/browser` to version 1.1.0](https://github.com/bacongobbler/browser/releases/tag/v1.1.0), which includes a fix for WSL not being able to open the browser.
**Special notes for your reviewer**: This was tested on WSL and Powershell - didn't have a Mac nearby, but the fix from the package should have no impact to Darwin (yay conditional compilation).
closes #740

Update bacongobbler/browser to v1.1.0

---

brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts

**What this PR does / why we need it**: 
This PR uses the provided `job.shell` when defining the job command (description in #756)
**Special notes for your reviewer**: 
To test this, update the controller environment variable that defines what worker should be started, then test with the following `brigade.js` file:
```
const { events, Job } = require("brigadier")
events.on("exec", () => {
var sh = new Job("sh", "ubuntu:latest")
sh.shell = "/bin/sh"
sh.tasks = ["ps ax"];
var bash = new Job("bash", "ubuntu:latest")
bash.shell = "/bin/bash"
bash.tasks = ["ps ax"];
sh.run()
bash.run()
});
```
You should see the correct shells being started in the logs of the pods:
```
$ kubectl logs sh-01d0n5ad7warya7xthg9tda4w2
PID TTY      STAT   TIME COMMAND
1 ?        Ss     0:00 /bin/sh /hook/main.sh
6 …
```

Use the job shell when starting the container

---

brig/cmd/brig/commands/project_create.go
brigade-controller/cmd/brigade-controller/controller/controller_test.go
brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-worker/src/brigadier.ts
brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts
pkg/brigade/project.go
pkg/storage/kube/project.go

**What this PR does / why we need it**: Adds the ability to toggle usage of `secretKeyRef` in jobs. Fixes #750 
I am not too familiar with javascript so I am not sure if this is the correct way to do it.

add the ability to toggle usage of secretKeyRef in jobs

---

pkg/api/project.go
pkg/api/project_test.go
pkg/storage/mock/storage.go
pkg/storage/mock/storage_test.go

Fixes #780 
Currently ProjectBuildSummary does not contain the last Build from a chronological perspective but the last item return by K8s API Server. This PR sorts the returned slice by Worker.StartTime in order to fix that.
I had to modify existing mock code and tests in order to be able to test correct Build sorting.

fix LastBuild in ProjectBuildSummary

---

docs/topics/dockerhub.md
docs/topics/genericgateway.md
docs/topics/secrets.md

#762 did not contain proper docs navigation which was created in #782 
This PR adds proper navigation to genericgateway.md and relevant pages

Add index + navigation for Generic Gateway documentation

---

README.md
brigade-worker/package.json
docs/index.md
docs/topics/developers.md
docs/topics/projects.md
docs/topics/releasing.md

Adds a releasing doc.
Bumps release strings in docs in anticipation of next `v0.20.0` release.

docs(*): add releasing.md doc, bump strings in anticipation of v0.20.0

---

docs/topics/releasing.md

Updates the `releasing.md` doc to mention the Brigade Project chart as well.  (Ref https://github.com/Azure/brigade-charts/issues/20)

docs(releasing.md): note Brigade Project chart as well

---

brigade-worker/src/require.ts
brigade-worker/test/require.ts
docs/topics/dependencies.md
docs/topics/index.md
docs/topics/workers.md

This PR enabled pretty import paths for local JavaScript modules from the same repo as the Brigade project, without the user having to know about the destination in the Brigade worker pod of the source code.
Specifically, it intercepts all local path imports in `brigade.js` and overrides them to the absolute path in the worker pod (`/vcs/<rest-of-relative-path>`).
For more context, see https://github.com/Azure/brigade/issues/450#issuecomment-458365387.
This PR does _not_ contain the docs for this feature, as #450 takes the larger task of documenting that in detail.

 Enable pretty import paths for local imports (from repo) in brigade.js

---

brig/cmd/brig/commands/build_list.go
brig/cmd/brig/commands/build_list_test.go

Fixes #810 
`brig build list` used Pod EndTime to display `Age` of the build. This was an error because
- Failed Pods are not assigned a correct EndTime, so value displayed was way off
- `Age` should report the birth time of the Pod (i.e. StartTime)

StartTime instead of EndTime on `brig build list` AGE column

---

brigade-worker/package.json
brigade-worker/src/index.ts
brigade-worker/yarn.lock

This PR updates the service account regex check to use `RegExp.test` instead of `string.match`, and updates Brigadier to the latest version, v0.3.
Now the questions I've been going around for the last couple of days for this PR:
- whether the job object should actually expose the service account regex - I don't think it should ever be updated by `brigade.js`.
- would it be used elsewhere in the worker?
cc @vdice, @rmb938

Fix service account regex test

---

brigade-worker/package.json
brigade-worker/yarn.lock

This PR updates `mocha` -- thus also updating the `growl` and `debug` packages.

Update mocha to ^v4.0.1 to update the debug and growl packages

---

CODEOWNERS

This adds the CODEOWNERS file, which elaborates on who the core maintainers are, and also which people hold specific responsibilities.
For example, a change to `/brigade.js` ought to be reviewed by @vdice before being merged.
This adds a `CODEOWNERS` file to track ownership of (a) the code as a whole, and (b) specific parts of the codebase.
Related docs:
https://help.github.com/en/articles/about-code-owners

Add CODEOWNERS file as a record of core maintainers

---

docs/topics/releasing.md

Updates the `brigade-charts` section in the releasing doc now that CI handles building/indexing of charts.

docs(releasing.md): update brigade-charts section

---

README.md

Follow up to #814, this points to `docs.brigade.sh` instead of `azure.github.io/brigade`
---
Related to #3 for `brigade-www` which updates the project website with same link change.

docs: update docs links

---

docs/content/topics/genericgateway.md

Fixes #842 
Documentation for the types of events Generic Gateway can raise (`simpleevent` and `cloudevent`) was missing. This PR adds this.

add types of Generic Gateway events on documentation

---

docs/content/topics/design.md

Fixes broken images in the `topics/design.md` doc. As [reported here](https://github.com/brigadecore/brigade-www/issues/7).
Partially addresses [#7](https://github.com/brigadecore/brigade-www/issues/7).

[docs](#840) fix image paths

---

docs/content/topics/scripting.md
docs/content/topics/scripting_advanced.md

Fixes #884 
This PR includes fixes for the links in scripting/scripting_advanced pages in Brigade docs. 
Preview
- https://deploy-preview-885--brigade-docs.netlify.com/topics/scripting/
- https://deploy-preview-885--brigade-docs.netlify.com/topics/scripting_advanced/

fix code links on scripting-scripting advanced

---

docs/content/intro/install.md

Fixes #887 
correction of storage link on intro/install
link is rendered here
https://deploy-preview-889--brigade-docs.netlify.com/intro/install/
and correctly targets this page
https://deploy-preview-889--brigade-docs.netlify.com/topics/storage/#azure-file-setup

correct storage link

---

brig/cmd/brig/commands/check.go

Fixes #815 as per https://github.com/brigadecore/brigade/issues/815#issuecomment-466362299
It's a trivial PR that implements of `brig check` which offers a quick check on the health of the system by checking for
-  at least one active API Server Pods
-  at least one active Controller Pods
-  at least one active Kashti Pods
-  if Vacuum CronJob is not suspended and has a non-empty schedule
Do you think we can add anything else?

brig check initial implementation

---

docs/config.toml

#865 was merged during #851 review. #851 did not include the necessary changes to `config.toml` so that `Quickstart` documentation would appear in docs index. This PR fixes that.

fix config.toml to include quickstart link

---

brigade-worker/package.json
brigade-worker/prestart.js
brigade-worker/test/prestart.ts
brigade-worker/yarn.lock

`yarn` was previously invoked using via `child-process-promise` without
waiting for the promises to resolve, which led to a race between
multiple `yarn` instances attempting to update package.json, yarn.lock
and node_modules simultaneously.  This led to failed package
installation for brigade.json files with more than one dependency.
Now, `yarn` is invoked synchronously and in a single invocation, rather
than via multiple asynchronous execs.  This prevents the race condition
and makes package installation faster.
Signed-off-by: Chris Chambers <chris.chambers@peanutcode.com>
Closes #867 
I need some help assessing the "If applicable" section below. I didn't see any existing unit tests for this functionality, and …

Eliminates a yarn race condition when installing brigade.json deps

---

brigade-worker/src/k8s.ts

Proposed fix for https://github.com/brigadecore/brigade/issues/898
Previously, the entire error/response was being logged and/or supplied to `reject()`.  In doing so, the request headers to the k8s api server may be logged (including the auth token.)
This PR updates the code to extract/log only the error message itself.
For the repro mentioned in the corresponding issue, this is the result with the changes on this branch:
```
$ b run test -f test-project/brigade.js
Event created. Waiting for worker pod named "brigade-worker-01d989tg4b92y29x7mv4v0akg7".
Build: 01d989tg4b92y29x7mv4v0akg7, Worker: brigade-worker-01d989tg4b92y29x7mv4v0akg7
prestart: no dependencies file found
[brigade] brigade-worker version: 1.0.0
[brigade:k8s] Creating secret myjob-01d989tg4b92y29x7mv4v0akg7
[brigade:k8s] …
```

fix(k8s.ts): extract error message for log/reject

---

docs/config.toml

Fixes #883 
This is a better sorting of the articles presented on the `Topic Guides` of Brigade documentation. It highly resembles the order found [here](https://github.com/brigadecore/brigade/blob/6140dc7d2440a5efe94e3be9aedfaf9ae94e7024/docs/topics/index.md) (one of the last commits before the introduction of netlify).
Also weight numbering on `Topic Guides` starts with a higher number, in case we wish to add more articles in the `intro` section.
preview on https://deploy-preview-897--brigade-docs.netlify.com/

fix sorting on topics docs

---

docs/config.toml
docs/themes/techdoc-brigade/layouts/partials/head.html
docs/themes/techdoc-brigade/layouts/partials/menu.html

This PR fixes issue #909, by setting urls and import paths in the hugo theme to use relative rather than absolute urls. This resolves two issues with the current docs site:
* Left-hand menu: you can now properly browse and test the staging previews that netlify generates, instead of constantly being directed to the live site
* CSS stylesheets: are now relative, so updates to the site CSS will no longer be broken as per #909 
You can see these changes on the preview for this PR: [https://5cd47650e631c80008da00cd--brigade-docs.netlify.com/](https://5cd47650e631c80008da00cd--brigade-docs.netlify.com/)
---
Closes #909.

[docs] make deploy previews use rel paths

---

brigade-controller/cmd/brigade-controller/main.go

This is a follow-up to #906 because when I went to expose this through the Helm chart, I noticed that the chart passed other bits of worker configuration (such as image and pull policy) to the controller as environment variables. Rather than use a flag for that purpose where related attributes are managed as env vars, I figured it would be more consistent to circle back on what I did in #906 and make it configurable via flag or env var.

allow default worker command to also be set via env var

---

docs/content/intro/install.md

The `Installing Brigade` document says that you should run `helm upgrade -n brigade-server brigade/brigade` to upgrade it, but it doesn't work:
```
$ helm upgrade -n brigade brigade/brigade --set brigade-github-app.enabled=true
Error: unknown shorthand flag: 'n' in -n
```
I believe the correct command should be `helm upgrade brigade ...` without `-n`, assuming you want to upgrade the release `brigade-server` with the latest version of the chart `brigade/brigade`.

fix: wrong `helm upgrade` usage in "Installing Brigade"

---

brig/README.md
brig/cmd/brig/commands/project_create.go
brig/cmd/brig/commands/project_create_no_vcs.go
brig/cmd/brig/commands/project_create_test.go
brig/cmd/brig/commands/project_create_vcs.go
brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts
docs/content/intro/quickstart.md
docs/content/intro/tutorial03.md
docs/content/topics/projects.md
docs/content/topics/scripting.md
pkg/storage/kube/project.go

Fixes #816, #917 
This PR modifies `brig project create` so that
- User is asked whether they do want to create a VCS or a no-VCS project
- If a no-VCS project is selected, some defaults are set (based on [comment](https://github.com/brigadecore/brigade/issues/816#issue-413206378))
- repository information would not be configurable
- clone URL information would not be configurable
- the custom VCS sidecar would be automatically set to NONE
- Git submodules inforrmation would not be configurable
- a Brigade.js file would be mandatory (either config map, or local)
- a secret for the generic gateway would be required
This needs TONS of testing, so pinging @technosophos @radu-matei @vdice @adamreese  :) Happy to say that VS Code for Kubernetes extension is pretty awesome for that, since you …

brig project create templates

---

brigade.js

This definitely needs to get in before 1.1... it will ensure version information is set correctly when building the brig binaries for release.

make sure version is set correctly for brig binaries

---

brigade-api/cmd/brigade-api/main.go
brigade-worker/package.json
docs/content/intro/quickstart.md
docs/content/topics/design.md
docs/content/topics/developers.md
docs/content/topics/releasing.md

Updates docs to bump release string to forthcoming `v1.1.0` release, per https://docs.brigade.sh/topics/releasing/

docs(*): v1.1.0 release updates

---

brig/cmd/brig/commands/project_create_no_vcs.go
brig/cmd/brig/commands/project_create_test.go
brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts

This PR restores the legacy values for project name and repo name for a VCS project, albeit somewhat reluctantly.  The values were updated, logically so, in https://github.com/brigadecore/brigade/pull/892.  However, for users who may be relying on the the previous/legacy values for these two, say, in corresponding `brigade.js` files for a given project, breaking changes may result.
As a concrete example, if a URL in a `brigade.js` file is derived using `project.repo.name`, the legacy value of this interpolated string (restored in this PR) would have been `myorg/myrepo`, whereas in 892, it would be `github.com/myorg/myrepo`, thus invalidating the URL.  
If we feel strongly about following the (sane) precedent/updates of 892 at some point in the …

fix(brigade-worker): ensure backwards compatibility for project name and repo name values

---

Makefile
docs/content/topics/developers.md

This PR includes instructions for Brigade development with [kind](https://github.com/kubernetes-sigs/kind). Same commands will also be used in building [e2e tests for Brigade](https://github.com/brigadecore/brigade/issues/879).
I added a line on Makefile to `kind load` images, this should run only if kind is installed. Is there a better way to do that?

added instructions to develop with kind

---

brig/cmd/brig/commands/app.go

Proposed fix for https://github.com/brigadecore/brigade/issues/940
Here, we silence usage (on errors) by default for the root command (and hence, all sub-commands.)
Sample:
Before:
```
$ ./bin/brig run foo
Error: could not find the project "foo": secrets "brigade-2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e" not found
Usage:
brig run PROJECT [flags]
Aliases:
run, exec
Flags:
-b, --background       Trigger the event and exit. Let the job run in the background.
-c, --commit string    A VCS (git) commit
-e, --event string     The name of the event to fire (default "exec")
-f, --file string      The JavaScript file to execute
-h, --help             help for run
-l, --level string     Specified log level: log, info, warn, error (default "log")
--no-color         Remove color codes …
```

fix(brig): silence usage on errors by default for root command

---

docs/content/topics/scripting.md

Adds mention of the necessary project-level config for enabling docker.
Closes https://github.com/brigadecore/brigade/issues/934

docs(scripting.md): add project-level config needed for docker setups

---

brig/cmd/brig/commands/build_list_test.go
brig/cmd/brig/commands/rerun.go
brig/cmd/brig/commands/rerun_test.go
pkg/script/delegated_runner.go

Proposed implementation to address https://github.com/brigadecore/brigade/issues/941, including refactoring for unit testability.
**Special Notes for the Reviewer**:
I went the route of using the same set of flags for `run` and `rerun`, as I didn't see harm in enabling overriding any of the `run` flags/fields for `rerun`.  Open to suggestions/revisiting if others have feedback.
Closes https://github.com/brigadecore/brigade/issues/941

feat(brig): achieve flag parity for rerun command (to run); add unit tests

---

brig/cmd/brig/main.go

While working on https://github.com/brigadecore/brigade/pull/946, I noticed that we were usually double-logging error messages.
(Below I omit the bulk of the usage output, intended to be fixed in https://github.com/brigadecore/brigade/pull/946)
Before:
```
$ ./bin/brig build list foo
Error: secrets "brigade-2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e" not found
Usage:
brig build list [project] [flags]
...
secrets "brigade-2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e" not found
```
After:
```
$ ./bin/brig-darwin-amd64 build list foo
Error: secrets "brigade-2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e" not found
Usage:
brig build list [project] [flags]
...
```

fix(main.go): remove double print of error message

---

Makefile
docs/content/topics/developers.md
e2e/run.sh
e2e/test.js
e2e/testproject.yaml
e2e/wait-for-deployment.sh

Closes #879
PR towards implementing end to end testing (described in #879)
What it does
- installs kubectl, kind, helm 3 if not already installed
- builds docker images of Brigade components
- loads them into kind
- installs them onto the kind cluster
- confirm that all components are successfully deployed
- installs a test Brigade project (brig project create -f) and confirms that the corresponding k8s Secret is created
- runs a custom brigade.js and verifies some output from worker Pod
Usage: `make e2e`.
As agreed on the standup, we'll set a goal to evolve this e2e suite using more tests. 
Links for follow-up
- https://github.com/blimmer/brigade-project-integration-test
- https://github.com/sstephenson/bats

end to end testing for Brigade using kind

---

brig/cmd/brig/commands/build_logs.go
pkg/storage/kube/worker.go
pkg/storage/mock/storage.go
pkg/storage/storage.go

You can now add `--init` like `brig build logs --init BUILD_ID` to view logs from the init container of a worker(=vcs-sidecar).
When the init-container failed due to reasons like a wrong ssh key or invalid git repo reference,
`brig build logs` has been giving us nothing useful.
So you had to run `kubectl logs -c vcs-sidecar $BRIGADE_WORKER` to finally catch it.
The `--init` flag just makes this process simple.
If your build failed, you always run `brig build logs --init` (or perhaps `brig build logs --init --jobs`) to catch any issues regardless of in which container in the worker pod the fatal error happened.
Ref #938
Adds the `--init` flag to `brig`.
This is the MVP or a foundational work to fully address #938 …

feat(brig): option to show logs from vcs-sidecar

---

brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-worker/node_modules/.yarn-integrity
brigade-worker/node_modules/@brigadecore/brigadier/out/events.d.ts
brigade-worker/node_modules/@brigadecore/brigadier/package.json
brigade-worker/package.json
brigade-worker/src/index.ts
brigade-worker/src/k8s.ts
brigade-worker/yarn.lock
pkg/brigade/build.go
pkg/storage/kube/build.go

Fixes #973
This will give gateways the power to be more specific about where source code for a build is obtained from-- i.e. it creates the possibility of getting source code from forks. This isn't necessary for github (because of how github implements pull requests behind the scenes), but may be necessary for other VCS-- notably, bitbucket.

add support for optional build-level cloneURL field

---

brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts
docs/content/topics/javascript.md

Closes https://github.com/brigadecore/brigade/issues/802
Note that `-o pipefail` is not a valid option for `/bin/sh`, so we only currently add it for `/bin/bash` scripts.

fix(brigade-worker): ensure set -o pipefail is set if shell is /bin/bash

---

brigade-api/cmd/brigade-api/main.go
brigade-worker/package.json
docs/content/intro/quickstart.md
docs/content/topics/developers.md
docs/content/topics/releasing.md
docs/content/topics/workers.md

Updates documentation in anticipation of the forthcoming `v1.2.0` release, per https://docs.brigade.sh/topics/releasing/

docs(*): v1.2.0 release updates

---

.gitignore
docs/config.toml
docs/content/topics/_index.md
docs/content/topics/brig.md

closes #830 
closes #970
This simply migrates the content that was in the README of `brig` to its own docs page.

Move brig README to docs page

---

pkg/webhook/genericsimpleevent_test.go

Break just break the inner select clause, in this case the goroutine will run till main process exit. Use  return to immediately exit this goroutiine when it work is done.

return to break outer for loop instead of inner select loop

---

brigade-worker/src/k8s.ts

Checks if a message is present before logging it. Closes #969 

Check message before logging it

---

brigade-worker/src/k8s.ts
brigade-worker/test/k8s.ts

This adds a bit of logic to return early (resolve the js promise) on a job.logs() call if the job has been canceled while the pod itself is either unscheduled or still in Pending.  Otherwise, the call to the k8s api to get logs will hang and/or error out.

fix(brigade-worker): return no logs found if job canceled and pod undefined or pending

---

brigade-worker/package.json

Fixes CI (`yarn audit` failure on master) via a `handlebars` version bump.
Error from `make yarn-audit`:
```
sh -c 'cd brigade-worker && yarn audit'
yarn audit v1.16.0
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.4.5                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ …
```

fix(brigade-worker): bump handlebars resolution per yarn audit

---

brig/cmd/brig/commands/project_create.go
pkg/brigade/project.go
pkg/brigade/project_test.go
pkg/storage/kube/project.go
pkg/storage/kube/project_test.go
pkg/storage/mock/storage.go
pkg/storage/mock/storage_test.go
pkg/webhook/dockerhub_test.go
pkg/webhook/genericsimpleevent_test.go

Allows for more complex/non-string/nested secrets as mentioned in https://github.com/brigadecore/brigade/issues/486 and https://github.com/brigadecore/brigade/issues/470.
Closes https://github.com/brigadecore/brigade/issues/486
I tested this via `brig project get <project>` where `<project>` had secrets along the lines of:
```
secrets:
number: 9
deeply:
- deeply:
nested: "{\"foo\":\"bar\"}"
environments:
- name: dev
serverName: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
...
```
As well as running a build from a brigade.js file such as:
```
const { events, Job } = require("brigadier")
events.on("exec", (event, project) => {
var job = new Job("job", "alpine");
job.env = {
DEEPLY_NESTED: …
```

feat(project): enable complex secret values

---

brigade-controller/cmd/brigade-controller/controller/controller_test.go
brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-controller/cmd/brigade-controller/controller/handler_test.go
brigade-worker/Dockerfile
docs/content/topics/projects.md
pkg/brigade/project.go

This reverts #1019  because it has been determined to have caused a breaking change in cases where a custom worker might be extended from an older version of our default worker-- in which case its `CMD` remains `yarn run test`. In such cases, that will run unexpectedly since the controller will no longer be overriding it. All such builds will pass with no jobs being executed.
We should be sure to re-apply #1019 in the next major release.

Revert "take default command from image instead of controller"

---

pkg/brigade/build.go
pkg/storage/kube/build.go
pkg/storage/kube/build_test.go
pkg/storage/kube/store_test.go

Fixes #976 
This adds fields to the build that gateways can _optionally_ populate. Follow-up changes to the gateways and to Kashti can make good use of these fields.

add optional title fields to build type

---

docs/content/topics/storage.md

Updates the instructions around setting up a nfs provisioner for Brigade per the current/supported chart (https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner)
Closes https://github.com/brigadecore/brigade/issues/786

docs(storage.md): update nfs instructions

---

brigade-controller/cmd/brigade-controller/controller/controller.go
brigade-controller/cmd/brigade-controller/controller/handler.go
brigade-controller/cmd/brigade-controller/controller/handler_test.go
brigade-controller/cmd/brigade-controller/main.go

This fixes an issue wherein a service account override is provided at the project-level (as in the advanced options during `brig project create`) but the default service account regex isn't properly updated, causing the following error:
```
$ brig project create
? VCS or no-VCS project? VCS
? Project Name brigadecore/empty-testbed
...
? Project Service Account my-sa
...
$ brig run brigadecore/empty-testbed
Event created. Waiting for worker pod named "brigade-worker-01dzyr4zgsbw80hah4s5tdw1zd".
Build: 01dzyr4zgsbw80hah4s5tdw1zd, Worker: brigade-worker-01dzyr4zgsbw80hah4s5tdw1zd
prestart: no dependencies file found
[brigade] brigade-worker version: 1.2.1
[brigade] Service Account my-sa does not match regex brigade-worker
```
**Special notes for your …

fix(brigade-controller): update the service account regex if service account overridden

---

brigade.js
brigade.json

* bump the brigadecore/brigade-utils version to [0.4.1](https://github.com/brigadecore/brigade-utils/releases/tag/v0.4.1)
* update `KindJob` usage in our `brigade.js`

chore(brigade.js*): bump brigade-utils; update KindJob usage

---

brigade.js

Adds `git`, a necessary utility for running e2e, to the e2e job/pod.
(The KindJob base image updated and no longer contains `git` by default.)
See https://brigadecore.github.io/kashti/jobs/test-e2e-01e4ejkx1c1c0k2wqpawq0w8pb

fix(brigade.js): add git to e2e job

---

Makefile

* Fixes the `resolve-dependencies` Makefile target

fix(Makefile): fix typo for 'go mod vendor'

---

brig/cmd/brig/commands/check.go

`brig check` was printing the raw k8s deployment objects instead of using the pre-existing status printer helper.
The previous behavior can be seen in #1084 
With this fix, we appear to be back to normal/expected:
```
$ brig check
✔️ Brigade API Server replicas: Desired 1, Ready 1, Updated 1, Available 1, Unavailable 0
✔️ Brigade Controller replicas: Desired 1, Ready 1, Updated 1, Available 1, Unavailable 0
✔️ Kashti replicas: Desired 1, Ready 1, Updated 1, Available 1, Unavailable 0
Info: Vacuum is healthy (not suspended and its schedule is non-empty)
```
Or, if Brigade not installed:
```
$ brig check
Info: Brigade API Server Deployment not found
Error: Brigade Controller Deployment not found
Info: Kashti deployment not found
```
Fixes …

fix(brig): fix printing of deployment statuses in brig check

---

Makefile
brigade.js
docs/content/topics/developers.md

I propose here to update the `build-brig` Makefile target to only build brig for the local user's OS (and place into `bin/brig`).  This enables a quicker dev cycle when testing changes to the CLI.  Then, the `xbuild-brig` target will be for building all of the supported OSes.

ci(Makefile): allow for easily building local OS brig binary

---

docs/content/intro/install.md
docs/content/topics/brig.md

* Fixes the Brig guide link
Closes https://github.com/brigadecore/brigade/issues/1093

docs(install.md): fix brig guide link

---

docs/content/intro/quickstart.md

The quickstart document instructed users to use `kubectl` to manually port
forward  into the cluster in order to access Kashti. There is a `brig`
command that does this, `brig dashboard`, and this commit updates the
document to mention it.
The commit also mentions `brig term` as a terminal alternative.

Update brig dashboard and term in quickstart

---

sdk/README.md
sdk/v2/api_client.go
sdk/v2/authx/api_client.go
sdk/v2/authx/common_test.go
sdk/v2/authx/service_accounts.go
sdk/v2/authx/sessions.go
sdk/v2/authx/users.go
sdk/v2/core/api_client.go
sdk/v2/core/events.go
sdk/v2/core/jobs.go
sdk/v2/core/logs.go
sdk/v2/core/project_roles.go
sdk/v2/core/projects.go
sdk/v2/core/secrets.go
sdk/v2/core/workers.go
sdk/v2/internal/restmachinery/client.go
sdk/v2/restmachinery/client.go
sdk/v2/system/api_client.go
sdk/v2/system/roles.go

This is a follow=up to #1118 
One bit of refactoring that @vdice and I collaborated (the creation of the `APIClientOptions` type) accidentally put that type in a package that was only available for internal consumption-- meaning third-party users of the SDK are unable to instantiate instances of that type.
This PR corrects that.

move APIClientOptions out of package that was under internal

---

v2/apiserver/internal/lib/restmachinery/endpoints_test.go

This is just a vanity fix. Some code involved in testing the server-side `restmachinery` uses a fake JSON schema that was copied from another project of mine, and as a result of the careless copy/paste, the `$id` for that schema looks funky. This PR fixes that.

fix test schema uri

---

sdk/v2/core/jobs.go
sdk/v2/core/jobs_test.go

The API client was accidentally applying type metadata to outbound `JobSpec`s, but this is incorrect. `JobSpec`s are never sent directly from client to server, rather `Job`s _containing_ specs are sent. `Job` was lacking the correct application of that type metadata.
This mistake arose due to some refactoring that occurred as code was being imported from the prototype and cleaned up. It wasn't caught because job-related API server endpoints do not yet exist to integration test this part of the client against.

fix job marshaling issue in sdk

---

v2/apiserver/internal/authx/sessions.go

When creating a new session for a user who has authenticated using OpenID connect, there has been a discrepancy between the token returned to the client and the token that is hashed and stored in the database. This PR corrects that.

fix token issue in oidc auth

---

v2/apiserver/internal/core/events_test.go

@vdice previously called my attention to these, but they somehow slipped through the cracks.

fix some misleading assertions in test cases

---

v2/apiserver/internal/authx/mongodb/users_store.go
v2/apiserver/internal/core/mongodb/projects_store.go
v2/apiserver/internal/lib/mongodb/errors.go
v2/apiserver/internal/lib/mongodb/errors_test.go

This PR is in response to [this thread](https://github.com/brigadecore/brigade/pull/1142#discussion_r510449498) in #1142.
I'd like to get this in before #1142 so #1142 can be amended to use this.
Also, while working on this PR I noticed that we probably _shouldn't_ be checking for duplicate key errors in the first place when creating users. New users are created exclusively by the system so the possibility of a duplicate key error _should_ be non-existent and if it _were_ to occur, it should be treated as an internal server error instead of a conflict, since conflicts ultimately surface as _user errors_. I will address that in a follow-up PR...
That takes the number of locations in the code where this helper is currently useful down to just one-- two if you count pending work in #1142. …

add helper for detecting mongodb duplicate key errors

---

v2/apiserver/internal/authx/mongodb/common_test.go
v2/apiserver/internal/authx/mongodb/service_accounts_store.go
v2/apiserver/internal/authx/mongodb/service_accounts_store_test.go
v2/apiserver/internal/authx/rest/service_account_endpoints.go
v2/apiserver/internal/authx/service_accounts.go
v2/apiserver/internal/authx/service_accounts_test.go
v2/apiserver/main.go
v2/apiserver/schemas/service-account.json
v2/cli/flags.go
v2/cli/main.go
v2/cli/service_account_commands.go

This adds create, list, lock, and unlock for service accounts.
Note the tokens that get generated for service accounts won't be usable yet. To keep this PR on the smaller side, the modifications to authz required in order to honor those tokens will be in a separate PR.

service account management features

---

v2/apiserver/internal/authx/mongodb/service_accounts_store.go
v2/apiserver/internal/authx/mongodb/service_accounts_store_test.go
v2/apiserver/internal/authx/service_accounts.go
v2/apiserver/internal/authx/service_accounts_test.go
v2/apiserver/internal/lib/restmachinery/authn/token_auth.go
v2/apiserver/internal/lib/restmachinery/authn/token_auth_test.go
v2/apiserver/main.go

This is a follow-up to #1142, which added service accounts to Brigade v2. This PR amends the token auth filter to permit service accounts to authenticate.
Note, this PR also updates all tests for the auth filter to be table-driven since they weren't previously.

enable service accounts to authenticate

---

charts/brigade/templates/_helpers.tpl
charts/brigade/templates/apiserver/deployment.yaml
charts/brigade/templates/artemis/common-config.yaml
charts/brigade/templates/artemis/config.yaml
charts/brigade/templates/artemis/internal-service.yaml
charts/brigade/templates/artemis/primary-config.yaml
charts/brigade/templates/artemis/primary-service.yaml
charts/brigade/templates/artemis/primary-stateful-set.yaml
charts/brigade/templates/artemis/secondary-config.yaml
charts/brigade/templates/artemis/secondary-service.yaml
charts/brigade/templates/artemis/secondary-stateful-set.yaml
charts/brigade/templates/artemis/secrets.yaml
charts/brigade/templates/artemis/service.yaml
charts/brigade/templates/artemis/stateful-set.yaml
charts/brigade/values.yaml
v2/apiserver/internal/core/kubernetes/substrate.go
v2/apiserver/internal/core/kubernetes/substrate_test.go
v2/apiserver/internal/lib/amqp/client.go
v2/apiserver/internal/lib/amqp/sender.go
v2/apiserver/internal/lib/amqp/session.go
v2/apiserver/internal/lib/queue/amqp/writer.go
v2/apiserver/internal/lib/queue/amqp/writer_test.go
v2/apiserver/internal/lib/queue/writer.go
v2/apiserver/main.go
v2/go.mod
v2/go.sum
v2/internal/rand/seeded.go
v2/internal/rand/seeded_test.go
v2/internal/retries/retries.go
v2/internal/retries/retries_test.go

This will ultimately be what enables the substrate component to communicate asynchronously with the scheduler.
This PR stops just short of actually dropping messages onto the queue because more extensive substrate additions are required before that can be done. Expect those changes in my next PR.
As always, I've taken care to organize the commits in a way that should make each of them a smaller / easier unit to review.

Add abstraction for writing to a messaging system

---

sdk/v2/core/api_client.go
sdk/v2/core/api_client_test.go
sdk/v2/core/substrate.go
sdk/v2/core/substrate_test.go
v2/apiserver/internal/core/common_test.go
v2/apiserver/internal/core/kubernetes/substrate.go
v2/apiserver/internal/core/kubernetes/substrate_test.go
v2/apiserver/internal/core/rest/substrate_endpoints.go
v2/apiserver/internal/core/substrate.go
v2/apiserver/internal/core/substrate_test.go
v2/apiserver/main.go

This is another PR aimed at reducing the size of my forthcoming scheduler PR.
While hacking on the scheduler, I realized there was a good opportunity to abstract the scheduler away from the underlying substrate by adding API endpoints that can give the scheduler the insight it needs into how many workers and jobs are currently running on the substrate.
i.e. This will stop the forthcoming scheduler component from having to be Kubernetes-specific in any way.

add api endpoints and client for getting insight into the substrate

---

v2/apiserver/config.go
v2/apiserver/config_test.go
v2/apiserver/internal/authx/principals.go
v2/apiserver/internal/lib/restmachinery/authn/token_auth.go
v2/apiserver/internal/lib/restmachinery/authn/token_auth_test.go

The scheduler is a special class of user that (once authz is implemented) can do things that other users (humans or service accounts) cannot do.
This PR adds special support for authn by the scheduler in the API server's authentication filter.

allow scheduler to authenticate to api server

---

charts/brigade/templates/_helpers.tpl
charts/brigade/templates/apiserver/deployment.yaml
charts/brigade/templates/scheduler/secret.yaml

This is a follow up to #1163, which introduced a required env var for the API server. The chart was accidentally not updated to provide a value for that environment variable. This PR remedies that.

make chart set SCHEDULER_TOKEN env var on api server

---

charts/brigade/templates/apiserver/cluster-role.yaml

An oversight in #1165 is that the api server is missing permissions to create PVCs and Pods. This PR corrects that.

give api server permission to create pods and pvcs

---

charts/brigade/templates/apiserver/cluster-role.yaml

This is a follow-up to #1162
This permission for the apiserver to list k8s pods. It breaks apart the the permissions for pods and PVCs since listing pods is necessary and listing PVCs is not. Since this grows the number of sections in this file, I also reordered them alphabetically by resource type so that it doesn't become unwieldy.
A side-by-side comparison of changes might be more helpful than a line-by-line comparison.

allow apiserver to list pods

---

Makefile
brigade.js
charts/brigade/templates/scheduler/deployment.yaml
charts/brigade/templates/scheduler/service-account.yaml
charts/brigade/values.yaml
v2/scheduler/Dockerfile
v2/scheduler/config.go
v2/scheduler/config_test.go
v2/scheduler/jobs.go
v2/scheduler/jobs_test.go
v2/scheduler/main.go
v2/scheduler/projects.go
v2/scheduler/projects_test.go
v2/scheduler/scheduler.go
v2/scheduler/scheduler_test.go
v2/scheduler/workers.go
v2/scheduler/workers_test.go

This listens for queued workers and jobs and uses the API to kick them off when available system capacity permits.
But don't get _too_ excited. Any worker that gets kicked off should fail because the new worker image isn't PR'ed yet.

add scheduler component

---

sdk/v2/core/jobs.go
sdk/v2/core/jobs_test.go
sdk/v2/core/workers.go
sdk/v2/core/workers_test.go
v2/apiserver/internal/core/common_test.go
v2/apiserver/internal/core/jobs.go
v2/apiserver/internal/core/jobs_test.go
v2/apiserver/internal/core/kubernetes/substrate.go
v2/apiserver/internal/core/kubernetes/substrate_test.go
v2/apiserver/internal/core/rest/jobs_endpoints.go
v2/apiserver/internal/core/rest/workers_endpoints.go
v2/apiserver/internal/core/substrate.go
v2/apiserver/internal/core/workers.go
v2/apiserver/internal/core/workers_test.go

The observer will trigger cleanup of Kubernetes resources related to completed workers and jobs, however, it seems that in keeping with a theme, that work should be delegated to the API server instead of the observer doing it directly.
This PR adds relevant endpoints to both the API server and the SDK.

prerequisite api changes for the forthcoming observer component

---

.github/workflows/README.md
.github/workflows/merge.yaml
.github/workflows/pr.yaml
Makefile
brigade.js
charts/brigade/templates/_helpers.tpl
charts/brigade/templates/logger/cluster-role-binding.yaml
charts/brigade/templates/logger/cluster-role.yaml
charts/brigade/templates/logger/linux-daemonset.yaml
charts/brigade/templates/logger/secret.yaml
charts/brigade/templates/logger/service-account.yaml
charts/brigade/templates/logger/windows-daemonset.yaml
charts/brigade/values.yaml
v2/logger/Dockerfile.linux
v2/logger/Dockerfile.winserv-2019

This PR builds adds Docker builds of custom fluentd-based log agents for both Linux and Windows.
Why custom? In the case of Linux it's only because we bake in the necessary fluentd plugins-- which is a common thing to do. In the case of Windows, it's that _plus_ the necessity of producing an image that's compatible with Windows Server 2019. (Weirdly, fluentd's Windows image seems to be incompatible with that.)
The build of the Linux-based log agent is not much different from any of the other Docker image builds in this project.
For Windows, however, we have to resort to some shenanigans to get the image built-- we have to fall back on GitHub Actions  to accomplish it (instead of dogfooding Brigade) because "Docker-in-Docker" is not well documented for Windows and my efforts to make it …

add log agent

---

Makefile

This corrects what appears to be the result of a botched rebase somewhere along the line.

remove duplicate line from make hack target

---

v2/cli/event_commands.go
v2/cli/logs_command.go
v2/cli/project_commands.go
v2/cli/secrets_commands.go

For background on this PR, it's useful to understand that the new `brig` CLI takes a lot of inspiration from the Azure cli (`az'). All commands and subcommands utilize flags _extensively_-- in fact, no argument is _ever_ accepted from the user without being qualified by some flag. Why? Because, especially for commands that take multiple arguments, it's easier and more intuitive to use flags than to remember (or research) the correct order of positional arguments.
When dealing with any subcommand of `project`, the `--id` (or `-i`) flag qualifies _which_ project.
For instance:
```
$ brig project get -i <project id>
```
Similarly, when dealing with any subcommand of `event`, the `--id` flag qualifies _which_ event.
For instance:
```
$ brig event get -i <project id>
```
Consider an _event_ …

misc cli improvements

---

Makefile
brigade.js

This PR transitions the official builds (those used in CI and, eventually, the release pipeline) to Kaniko. The main benefit to this is it ends our dependency on the comparatively complex and less secure "Docker in Docker" pattern (less secure because DinD requires a privileged container).
A secondary benefit is we get experience with a different build pattern that I think we might want to add to our playbook. (i.e. We should probably present this as an alternative to DinD in Brigade's own documentation whenever we get around to writing 2.0 docs.)
The custom Kaniko image this uses is in my own Docker Hub repository for now, with source in my own GitHub repository, but as with other "utility" images we use, we can more that over to the `brigadecore` organization in the near future.
Builds …

transition from more complex docker-in-docker to less complex kaniko

---

v2/internal/kubernetes/common.go

As we continue to abstract brigade users farther from the underlying k8s details, the names of resources become less relevant-- especially since everything is labeled very well.
This PR shortens event secret names, job secret names, worker pod names, job pod names, and workspace PVC names.
They remain easily recognizable despite being shorter.
This doesn't solve #1195, but it's related to it.

shorten k8s resource names

---

v2/brigadier/package.json
v2/brigadier/src/events.ts
v2/brigadier/src/index.ts
v2/brigadier/src/logger.ts
v2/brigadier/src/workers.ts
v2/brigadier/test/index.ts
v2/brigadier/test/mocks.ts
v2/brigadier/yarn.lock

1. Add a logger that is exposed to `brigade.js` authors.
In 1.x, the only logger we had was entirely internal to the worker. We used it, but `brigade.js` authors could not. So although one could set worker log level when creating a project, it only ever controlled whatever logging the worker did itself behind the scenes. There was no access to a leveled logger within the script author's own code. This PR fixes that. The logger is based on the popular [winston](https://www.npmjs.com/package/winston) library.
1. Correct an oversight in the first commit of brigadier bits by adding a `logLevel` field to the `Worker` class.
1. Organize and cleanup imports.
TIL that if one module is aggregating exports from other modules, this:
```
import { Foo } from "foo"
export { Foo }
```
Is equivalent to …

misc. brigadier improvements

---

v2/observer/common.go
v2/observer/jobs.go
v2/observer/workers.go

In two cases, calls from the observer to the API server weren't setting a timeout on the context.
In two other cases where a timeout _was_ set, I've observed the timeout is too aggressive if there's a single instance of the apiserver running and its handling a lot of concurrent requests.
I don't foresee any reason to make this time out configurable-- rather it should simply be "generous." These are calls that we want to succeed even if they take a long time for whatever reason.

set and fine tune context timeout on api calls from observer

---

v2/apiserver/internal/authx/principals.go
v2/apiserver/internal/authx/roles.go
v2/apiserver/internal/core/roles.go
v2/apiserver/internal/system/roles.go

This PR introduces a variety of prerequisite types and constants that will be leveraged by several forthcoming PRs that will:
1. Define the roles belonging to "special" principals such as the root user and the scheduler and observer components.
1. Enable granting/revoking both project-level and system-level roles to/from principals such as users and service accounts.
1. Enforce authorization on all API calls.
I'm submitting these individually in an effort to keep PRs smaller and more reviewable given maintainers' limited holiday season bandwidth.

laying groundwork for authz

---

v2/apiserver/schemas/project.json

Updates the `url` definition in the project schema to allow for `@` characters, as needed to support ssh git URLs (e.g. `git@github.com:myorg/myrepo.git`
Do we have tests against our JSON schemas yet?  If so, I can add/update.

fix(project.json): allow for 'git@github.com:...' clone urls

---

v2/cli/secrets_commands.go

I found myself typing `brig project secret set ...` often, especially as the current mode of this command is to set one secret at a time.  Therefore, I thought this might be an appropriate alias to add.

feat(secrets_commands.go): add secret command alias

---

v2/apiserver/internal/core/jobs.go
v2/apiserver/internal/core/rest/jobs_endpoints.go
v2/apiserver/internal/core/rest/logs_endpoints.go
v2/apiserver/internal/core/rest/workers_endpoints.go
v2/apiserver/internal/core/workers.go
v2/apiserver/internal/lib/restmachinery/server.go
v2/worker/package.json
v2/worker/src/jobs.ts
v2/worker/yarn.lock

I was recently tooling around with creating a TS/JS Brigade 2 API client that works in both Node and any modern browser. In doing so, I stumbled across the fact that no analog to Node's `http2` library exists in the browser world. (There is no polyfill for it either.) This is not to say that browsers can't do http/2-- that would be absurd. But they _don't_ (yet?) expose any http/2 client that can be used to _programmatically_ consume a stream. This means any hypothetical TS/JS Brigade 2 API client used _within a browser_ cannot consume our log streams and status streams as they were currently implemented on the backend.
However, I learned that there's an entire [specification](https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events) for _server sent events_. …

Add support for server sent event streams

---

v2/apiserver/schemas/event.json
v2/apiserver/schemas/project.json

Adds missing `commit` and `ref` fields to the `workerSpec`'s `git` section of the project config, to match the similar config on an event.
Actually, since the two `gitConfig` definitions are now equivalent between the project and event schema, we could entertain housing common schema definitions in a sibling file that both could then pull from... thoughts?

fix(project.json): add commit and ref fields to gitConfig

---

v2/apiserver/internal/authx/named_principals.go
v2/apiserver/internal/authx/named_roles.go
v2/apiserver/internal/authx/principals.go
v2/apiserver/internal/authx/principals_test.go
v2/apiserver/internal/authx/roles.go
v2/apiserver/internal/authx/service_accounts.go
v2/apiserver/internal/authx/users.go

This PR is the first of several aimed at defining, managing, and enforcing permissions.
Emphasis in this one is on _defining_, as it introduces several well-defined system-level, project-level (and in one case, event-level) roles-- each with documented domain-specific meaning.
For context, in a subsequent PR, you can expect _use_ of these roles to look something like this:
```
// Principal is retrieved from the context and an error is returned if the principal lacks the specified role.
if err := p.authorize(ctx, authx.RoleProjectCreator()); err != nil {
return project, err
}
```

define roles

---

v2/apiserver/internal/authx/mongodb/service_accounts_store.go
v2/apiserver/internal/authx/mongodb/users_store.go
v2/apiserver/internal/core/mongodb/events_store.go
v2/apiserver/internal/core/mongodb/projects_store.go

Fixes #1171 
When listing events, they are ordered newest first. There's a possibility of multiple events being created at the exact same time, so to ensure consistent sort order, event id is used as secondary sort criteria.
#1171 occurs because we incorrectly used `bson.M` to specify sort criteria when querying MongoDB. This type does _not_ preserve the order of the criteria themselves. So, we were sometimes, by luck of the draw, sorting by creation time and _then_ id, and other times, sorting by id and _then_ creation time. This could lead to confusing, inconsistent results.... and broken pagination.
This PR redefines event sort criteria using `bson.D`, which preserves the order of our criteria, so that we always sort by creation time first, and id second.
This was the only case with …

always preserve order of sort criteria

---

.dockerignore
examples/git/github-demo.yaml
examples/javascript/dependencies-demo.yaml
examples/javascript/hello-world.yaml
examples/javascript/pipeline-demo.yaml
examples/typescript/dependencies-demo.yaml
examples/typescript/hello-world.yaml
examples/typescript/pipeline-demo.yaml
v2/apiserver/internal/core/events.go
v2/apiserver/schemas/project.json
v2/worker/Dockerfile
v2/worker/src/prestart.ts

Fixes #527
Details on each commit:
In the course of tinkering with the rest of this PR, I created a project with a name longer than 18 characters. The length of the "brigade-" prefix combined with the project name and a UUID (v4) suffix created a namespace name that exceeded the maximum length of 63 characters.
See #1195. I do not believe such stingy limits are broadly applicable.
This could have been its own PR, but it's a small change.
It never hurts to slim down the Docker build context.
This works by enhancing the pre-processing done in the prestart script. The goal is to take a `brigade.ts` and compile it down to a `brigade.js` that the rest of the Worker can then deal with as per usual. Resolving dependencies is, of course, a prerequisite for compiling a TS script. At a minimum, a …

Add experimental support for brigade.ts

---

charts/brigade/templates/logger/secret.yaml

#1223 overlooked the fact that fluentd configuration had to be updated to account for the new mongodb chart.
This PR fixes that.

fix fluentd connection to mongodb

---

charts/brigade/templates/apiserver/deployment.yaml
charts/brigade/templates/logger/secret.yaml
v2/apiserver/config.go
v2/apiserver/config_test.go

We were previously making an assumption that mongo was deployed in a replicated topology (even if the number of replicas was one).
This change makes the API server and the log agent (the only two components that talk to mongodb) tolerant of _either_ a standalone or replicated topology.

work with different mongodb deployment topologies

---

examples/javascript/dependencies-demo.yaml
examples/javascript/hello-world.yaml
examples/javascript/pipeline-demo.yaml
examples/typescript/dependencies-demo.yaml
examples/typescript/hello-world.yaml
examples/typescript/pipeline-demo.yaml

Provided you have the popular Red Hat YAML plugin for VS Code, this change provides context help when tinkering with examples.

make examples reference project schema

---

v2/apiserver/schemas/common.json
v2/apiserver/schemas/event.json
v2/apiserver/schemas/job-status.json
v2/apiserver/schemas/job.json
v2/apiserver/schemas/project.json
v2/apiserver/schemas/secret.json
v2/apiserver/schemas/service-account.json
v2/apiserver/schemas/worker-status.json

* Consolidates common/shared schema definitions in a separate schema file.
Note: here I've settled on using the full file reference when referencing this common file.  When I attempt to use a relative reference, e.g. `"common.json#/definitions/url"`, we get:
```
open /brigade/schemas/github.com/brigadecore/brigade/v2/common.json: no such file or directory
```
But I can't tell where/how the full reference is resolved as this.  I would expect it to be resolved as `/brigade/schemas/common.json`, since that's where we place all of them in the apiserver image.
For what it's worth, we _could_ use the relative reference as shown above if we added the following line to the apiserver Dockerfile:
`COPY v2/apiserver/schemas/common.json /brigade/schemas/github.com/brigadecore/brigade/v2/common.json` …

Consolidate shared schema definitions

---

sdk/v2/authn/service_accounts.go
sdk/v2/authn/sessions.go
sdk/v2/authn/users.go
sdk/v2/core/events.go
sdk/v2/core/jobs.go
sdk/v2/core/logs.go
sdk/v2/core/projects.go
sdk/v2/core/secrets.go
sdk/v2/core/substrate.go
sdk/v2/core/workers.go
sdk/v2/internal/restmachinery/client.go
sdk/v2/internal/restmachinery/client_test.go
sdk/v2/internal/restmachinery/outbound_request.go

While working on a TS equivalent of this SDK, I found some optimizations I could port over so that more boilerplate is accounted for by the client-side rest machinery.

tidy up client-side rest machinery

---

v2/apiserver/internal/core/projects.go
v2/apiserver/internal/core/projects_test.go
v2/apiserver/main.go
v2/tests/git_initializer_test.go

* Adds logic to delete all events associated with a given project when said project is deleted
Closes https://github.com/brigadecore/brigade/issues/1202

feat(projects.go): delete all project events on project delete

---

sdk/v2/core/jobs.go
v2/tests/git_initializer_test.go

* Adds finer-grained assertions (worker and job logs/terminal phases, vcs logs, etc.) for the git initializer integration tests
* Adds a test scenario around a job failure (which should provoke both job and worker terminal phases of failed)
Closes https://github.com/brigadecore/brigade/issues/1224

ref(git_initializer_test.go): add finer-grained assertions and more test scenarios

---

v2/tests/git_initializer_test.go

- Only check for project delete error if not of the ErrNotFound variety.

fix(integration tests): ignore error if of ErrNotFound variety on initial project delete

---

Makefile
brigade.js

* Bumps the kaniko image version to fix issue mentioned in https://github.com/brigadecore/kaniko/issues/1
Depends on https://github.com/brigadecore/kaniko/pull/2 (and subsequent tag/push of image)

chore(*): bump kaniko tag

---

v2/cli/event_commands.go
v2/cli/log_command.go
v2/cli/project_commands.go
v2/cli/project_role_commands.go
v2/cli/role_commands.go
v2/cli/secret_commands.go
v2/cli/service_account_commands.go
v2/cli/user_commands.go

closes #1216 
This commit adds plural aliases for the `brig` event, project, service accounts, and user commands.

Add command aliases for CLI

---

v2/tests/git_initializer_test.go

😅 This is a fix for when we check the cause of the error that results from deleting a project.  We don't want to overwrite `err` here.

fix(git_initializer_test.go): don't overwrite err when checking cause

---

Makefile

Now that we [don't track chart dependencies](https://github.com/brigadecore/brigade/pull/1269/commits/2fc9b3d4dfc17bc7210292a43378117f2cfbf679), mongodb being the only one so far, we need to run `helm dep up` to fetch them prior to deploying brigade as part of the `make hack` target.

fix(Makefile): add helm dep up to hack target

---

sdk/v2/core/jobs.go
sdk/v2/core/jobs_test.go
sdk/v2/core/workers.go
v2/apiserver/internal/core/jobs.go
v2/apiserver/internal/core/jobs_test.go
v2/apiserver/internal/core/kubernetes/substrate.go
v2/apiserver/internal/core/logs.go
v2/apiserver/internal/core/logs_test.go
v2/apiserver/internal/core/mongodb/events_store.go
v2/apiserver/internal/core/mongodb/jobs_store.go
v2/apiserver/internal/core/mongodb/jobs_store_test.go
v2/apiserver/internal/core/rest/jobs_endpoints.go
v2/apiserver/internal/core/workers.go
v2/apiserver/schemas/job.json
v2/scheduler/jobs.go
v2/scheduler/jobs_test.go
v2/worker/src/jobs.ts

Fixes #1191 
The main challenge to cascading cancelations was to do it efficiently. Transitioning from workers having a map of job names --> job to workers having an _array_ of jobs with intrinsic names (the were extrinsic before) allows us to cascade cancellations much more efficiently on the database end.
The side effect of this change is that jobs associated with a given worker are an ordered list now instead of an unordered map. I initially I had preferred the map because map semantics enforced unique job names and didn't directly imply execution order. The downside to the map, however, was that if retrieving and displaying an event multiple times, the order of the jobs appears to shift around. `watch brig event get -i <id>` was really triggering my OCD. After cutting over to an …

use array to store worker's jobs instead of map

---

v2/brigadier/package.json
v2/brigadier/src/logger.ts
v2/brigadier/yarn.lock
v2/worker/src/brigadier.ts
v2/worker/src/jobs.ts
v2/worker/src/logger.ts
v2/worker/src/prestart.ts

In preparation for the upcoming release, I did a rehearsal of publishing brigadier to npmjs.com today. It went smoothly, but when I went to _use_ it in a project, I noticed it dragged along quite a large number of third party dependencies with it. They were all transitive dependencies of winston-- the leveled logging library we're using.
This PR cuts us over to the same approach used for jobs, groups, etc. Brigadier provides a minimal (and more or less no-op) implementation with no third-party dependencies. At runtime, the _worker_ polyfills the logger with a more sophisticated winston logger.
This brings the third-party dependencies for brigadier down to zero.

simplify brigadier logger; eliminate brigadier's third-party dependendecnies

---

v2/brigadier/src/events.ts
v2/brigadier/src/jobs.ts
v2/brigadier/src/projects.ts
v2/brigadier/src/workers.ts
v2/brigadier/test/events.ts
v2/brigadier/test/groups.ts
v2/brigadier/test/jobs.ts
v2/worker/src/events.ts
v2/worker/test/events.ts
v2/worker/test/jobs.ts

Similar to a recent change in the experimental TS/JS SDK. See https://github.com/krancour/brigade-sdk-for-js/pull/3.
TS Maps don't serialize to JSON in the way one might expect. As a result, I'm pretty sure that in the current state, any sidecar containers, environment variables, host selectors, and more are missing from the JSON representation of a new job when it reaches the server's create job endpoint.
To correct this _and_ to simplify the programming model (TS Maps aren't super pleasant to work with, imho), this PR eliminates all further usage of TS Maps from brigadier, preferring objects with constrained key types instead.
I have vetted the change with a `brigade.ts` that creates some pretty complex jobs.
```
import { Container, events, Job, logger } from "@brigadecore/brigadier" …
```

brigadier-- ditch maps, prefer objects with constrained key type

---

v2/apiserver/internal/core/common_test.go
v2/apiserver/internal/core/events.go
v2/apiserver/internal/core/events_test.go
v2/apiserver/internal/core/kubernetes/substrate.go
v2/apiserver/internal/core/mongodb/events_store.go
v2/apiserver/internal/core/mongodb/events_store_test.go
v2/apiserver/internal/core/projects.go
v2/apiserver/internal/core/projects_test.go

* Updates the Cancel/DeleteMany logic for events to stream instead of accrue in memory a potentially large collection of canceled/deleted events
See https://github.com/brigadecore/brigade/pull/1262#issuecomment-773420895

feat(events): stream canceled/deleted (many) events

---

examples/git/github-demo.yaml
examples/javascript/dependencies-demo.yaml
examples/javascript/hello-world.yaml
examples/javascript/pipeline-demo.yaml
examples/typescript/dependencies-demo.yaml
examples/typescript/hello-world.yaml
examples/typescript/pipeline-demo.yaml
sdk/v2/meta/meta.go
v2/apiserver/internal/meta/meta.go
v2/apiserver/internal/meta/testing/meta.go
v2/apiserver/schemas/common.json
v2/worker/src/jobs.ts

I feel as if this CYA maneuver is in order before we cut an alpha release. This way we safeguard ourselves against anyone who may come along months from now trying to use an alpha.1 SDK or CLI with a newer API server that may have taken on breaking changes in the interim.
cc @radu-matei you'd want to account for this in your Rust SDK. I'll handle the JS/TS one.

change api version to be v2-alpha.1

---

.gitignore
Makefile
brigade.js

This is a faster, more efficient way to publish brigadier to npmjs.com without a need for any third-party tools.
This approach is _already_ employed by the 1.x brigadier.

Streamline brigadier publishing

---

v2/apiserver/internal/core/kubernetes/logs_store.go
v2/apiserver/internal/core/mongodb/logs_store.go

* Removes the tailable cursor option when streaming logs from the cool store (mongodb), as the log service will only ever fetch from this store when all logs have been persisted from workers/jobs.
* Ensure the warm logs hang up (without error) after all logs have been streamed from the pod and the pod's phase is terminal.
Closes https://github.com/brigadecore/brigade/issues/1270

ref(logs_store.go): rm tailable cursor option

---

Makefile
brig/Dockerfile
brigade-api/Dockerfile
brigade-controller/Dockerfile
brigade-cr-gateway/Dockerfile
brigade-generic-gateway/Dockerfile
brigade-vacuum/Dockerfile
brigade.js

We'e been using our official `brigadecore/go-tools` to build the `v2` branch for quite some time now.
This PR cuts 1.x in `master` over to `brigadecore/go-tools` from its less official progenitor, `krancour/go-tools`.

switch from krancour/go-tools to official brigadecore/go-tools

---

v2/cli/event_commands.go

After we switched from maps of jobs to arrays of jobs, `event get` ops in the CLI have ben showing job indices instead of job name. This PR fixes that.

fix display of job names in cli event get command

---

charts/brigade/templates/logger/secret.yaml
v2/apiserver/internal/core/common_test.go
v2/apiserver/internal/core/events.go
v2/apiserver/internal/core/events_test.go
v2/apiserver/internal/core/kubernetes/logs_store.go
v2/apiserver/internal/core/logs.go
v2/apiserver/internal/core/logs_test.go
v2/apiserver/internal/core/mongodb/logs_store.go
v2/apiserver/internal/core/projects.go
v2/apiserver/internal/core/projects_test.go
v2/apiserver/main.go

- Adds logic to delete logs from cool storage (mongo) on event and project deletion
- In doing so, converts the logs collection from capped to regular (no manual deletes/removals possible with a capped collection)
Closes https://github.com/brigadecore/brigade/issues/1271

feat(*): delete logs on event and project deletion

---

charts/brigade/templates/logger/secret.yaml

* Adds a fluentd record filter to remove trailing whitespace from worker and job logs headed for mongo
Closes https://github.com/brigadecore/brigade/issues/1261

fix(fluentd): strip tailing whitespace from worker/job logs

---

sdk/v2/core/events.go
sdk/v2/core/events_test.go
sdk/v2/core/logs_test.go
sdk/v2/internal/restmachinery/client_test.go

* Only managed to find one spot in sdk code where a nil dereference check was needed
* Added tests around other areas where function args may be nil
Closes https://github.com/brigadecore/brigade/issues/1207

Add nil pointer check; tests

---

v2/apiserver/internal/lib/restmachinery/server_test.go

@krancour @radu-matei and I have all tried to pin down the reason for this test's flakiness (https://github.com/brigadecore/brigade/issues/1137) but alas, haven't been successful.  Since it still proves to be a disruption in CI for PRs, etc, I vote we disable it for now.

chore(server_test.go): disable flaky test

---

v2/apiserver/internal/core/mongodb/projects_store.go

Hacking on a new GitHub gateway exposed this bug-- label criteria are nested like this:
```
{
...
"labels": {
"labels": {
"foo": "bar"
}
}
}
```
It's probably obvious that isn't what was intended and it is stopping us from locating projects subscribed to a particular event.
This worked at one time until that code was "simplified" (i.e. screwed up by yours truly).
Unit tests didn't catch this because the mocked out database doesn't perform actual queries.
Once our integration tests are up and running, we might consider a second set of persistence-related tests that execute against a real MongoDB instance.

fix list subscribed project

---

v2/apiserver/schemas/role-assignment.json

* Updates the event scope to allow for domain/url-like sources.
I'm assuming adding `.` and `/` chars are sufficient for our needs and we didn't need to allow for `:` or other chars for full url support.
Closes https://github.com/brigadecore/brigade/issues/1301

fix(role-assignment.json): allow for url/domain-like scopes

---

v2/apiserver/internal/lib/restmachinery/request_context_filter.go
v2/apiserver/internal/lib/restmachinery/server.go

#1304 got me thinking. There was some discussion related to that PR having to do with an infinite retry we currently have when writing new events to a queue and how that should probably just change to one of our usual exponential backoffs.
Well... that got me thinking more about how a request to do something like create an event, for instance, could run long (and still ultimately succeed) if it got into a backoff situation. And what happens if an impatient client hangs up in the meantime?
Just about everything we do throughout the whole system is currently interruptible by a canceled context... and request-bound contexts are canceled the moment the client disconnects.
Do we actually _want_ that behavior in certain cases? Suppose when creating a new event, the event is successfully written …

don't allow client disconnects to interrupt writes

---

v2/apiserver/internal/authn/mongodb/sessions_store.go
v2/apiserver/internal/system/authn/token_auth.go

* Adds an expiry index for each document in the sessions collection, to auto-cleanup per the 'expires' field
Closes https://github.com/brigadecore/brigade/issues/1146

feat(sessions_store.go): add index on 'expires' field for ttl cleanup

---

sdk/v2/internal/restmachinery/client.go

* Defines our own retry policy for our base restmachinery client so that we have finer-grained control.  In this case, https://github.com/brigadecore/brigade/issues/1255 requested to not retry on 500s, so this is what differs from the default defined by the go-retryablehttp library.
Closes https://github.com/brigadecore/brigade/issues/1255
The output as tested via the cli looks like the following when a 500 is returned:
```
$ b2 event create -p test-project
An internal server error occurred.
```
Is this acceptable?  Or do we want a follow up to try to add additional context?

feat(restmachinery/client.go): use custom retry policy to exclude 500 from retries

---

CODEOWNERS

If we agree this is an improvement, I have PRs ready to to rip for most other repos in this org.

a more elegant way of managing CODEOWNERS

---

v2/brigadier/src/index.ts
v2/brigadier/test/index.ts
v2/worker/src/brigadier.ts
v2/worker/test/brigadier.ts

Fixes #1317
While touching these files anyway, I also organized exports alphabetically, which seems cleaner and more consistent.
Note that there are two new TODOs here that I do not intend to resolve at this time. It seems that approach we used for validating something is exported as expected, which works beautifully for constants, variables, and classes, simply does NOT work for interfaces. I'm not clear on why.
I have, however, manually verified that these changes address #1317.

export Event from brigadier and worker's brigadier polyfill

---

v2/brigadier/src/workers.ts

When working on #1316 I discovered that scripts had no way of getting to commit/ref info.
This PR fixes that.
The API server already includes this information when it creates the k8s secret for an Event. The only issue was that we weren't exposing it neatly via Brigadier.

expose worker git details to brigadier-based scripts

---

Makefile
hack/kind/new-cluster.sh

As the number of contributors to v2 starts to grow, I figure it might be useful to start sharing some of the little hacks that I've kept to myself until now.
This PR adds a make target for standing up a new customized kind cluster that:
* Is integrated with a local Docker registry
* Forwards localhost:31600 to the API server
* Has NFS support pre-installed to support Brigade's "shared workspaces" feature
End-user documentation will obviously have to address what the prerequisites within a cluster are, in general, for running Brigade 2. This contribution is not aimed at end-users. It's aimed at contributors who want to rapidly set up a suitable, local environment to facilitate development.
A comprehensive guide to hacking on v2 will follow in another PR.

add script and make target for standing up a customized kind cluster

---

Makefile
brigade.js
v2/apiserver/schemas/common.json
v2/apiserver/schemas/event.json
v2/apiserver/schemas/job-status.json
v2/apiserver/schemas/job.json
v2/apiserver/schemas/project-role-assignment.json
v2/apiserver/schemas/project.json
v2/apiserver/schemas/role-assignment.json
v2/apiserver/schemas/secret.json
v2/apiserver/schemas/service-account.json
v2/apiserver/schemas/source-state.json
v2/apiserver/schemas/worker-status.json

* Adds CI for validating schema compilation and examples against these schemas
I couldn't figure out how to keep the namespaced `$id`'s (e.g. `github.com/brigadecore/brigade/v2/job.schema.json`) for each schema and have that work with both ajv (it did not like the `file://` approach we had) and runtime validation by the api server.  So, I simplified the `$id` fields, which also simplifies the `$ref`'s for accessing common definitions.  Thoughts/concerns?
Closes https://github.com/brigadecore/brigade/issues/1247
* Not sure if this helps or hurts the VS Code syntax highlighting; I recall there may have been an issue in this realm cc @krancour 

feat(ci): add schema and example validation

---

README.md
examples/01-hello-world/project.yaml
examples/02-first-event/project.yaml
examples/03-first-job/project.yaml
examples/04-simple-pipeline/project.yaml
examples/05-groups/project.yaml
examples/06-git/project.yaml
examples/07-npm/project.yaml
examples/08-yarn/project.yaml
examples/09-typescript/project.yaml
examples/10-kitchen-sink/project.yaml
sdk/v2/meta/meta.go
v2/apiserver/internal/meta/meta.go
v2/apiserver/internal/meta/testing/meta.go
v2/apiserver/schemas/common.json
v2/brigadier-polyfill/src/jobs.ts

@vdice and I previously agreed that we'd just assume breaking changes occur between _alpha_ releases, so this PR bumps everything from v2.0.0-alpha.1 to v2.0.0-alpha.2.
_By design_, this will make v2.0.0-alpha.1 clients incompatible with the v2.0.0-alpha.2 server.
I think this PR should actually just end up being the last thing we merge before we cut v2.0.0-alpha.2.

API version bump

---

v2/apiserver/internal/core/jobs.go
v2/apiserver/internal/core/jobs_test.go
v2/apiserver/internal/core/workers.go
v2/apiserver/internal/core/workers_test.go

* Disallows updating a worker's or job's status if their phase is already terminal
Closes https://github.com/brigadecore/brigade/issues/1276

fix(worker/job services): disallow transition of workers/jobs from terminal status

---

Makefile

We need to specify a commit when we do this or else we end up with a tag that points to the head of master-- even if it originally pointed elsewhere (it is deleted and re-created).

fix publish cli job

---

Makefile

This is fixes a _different_ problem than #1346...
By using the `-delete` option here, if the release exists, it is deleted and re-created. (And often the release _does_ already exist, because that's often how I create the tag that triggers the delivery pipeline.) Deleting and re-creating the release seems to include deleting and re-creating the tag itself. That's bad news because it puts us into an infinite loop here the release triggers the delivery pipeline, which triggers a new release, which...
`-delete`'s gotta go.

fix publish-cli target

---

examples/07-npm/.brigade/package-lock.json
examples/07-npm/.brigade/package.json
examples/08-yarn/.brigade/package.json
examples/08-yarn/.brigade/yarn.lock
examples/10-kitchen-sink/.brigade/package.json
examples/10-kitchen-sink/.brigade/yarn.lock

Technically this doesn't matter, because the worker will swap in its own Brigadier implementation, but it's nice to keep the examples up to date.

update examples to use latest brigadier

---

sdk/v2/authz/role_assignments.go
sdk/v2/authz/role_assignments_test.go
sdk/v2/core/project_roles_assignments_test.go
sdk/v2/lib/authz/principals.go
v2/apiserver/internal/authz/rest/role_assignments_endpoints.go
v2/apiserver/internal/authz/role_assignments.go
v2/apiserver/internal/authz/role_assignments_test.go
v2/apiserver/internal/core/project_role_assignments_test.go
v2/apiserver/internal/core/projects.go
v2/apiserver/internal/core/rest/project_role_assignments_endpoints.go
v2/apiserver/internal/lib/authz/principals.go
v2/apiserver/internal/system/authz/authorizers.go

There is some moderately extensive refactoring that is in order to address #1257. (Alpha is the time for this sort of stuff!) So this is the first of several related PRs-- I'm trying hard to keep them bite-sied.
This PR just moves the `PrincipalReference` type (on both the server side and client side) to a different package. It does this as a prelude to the next step in the refactor wherein I'll need `PrincipalReference` to exist in a package that has no significant dependencies of its own so that I can avoid dependency cycles-- and that was exactly the point of this `libAuthz` package to begin with.
To be clear-- there are no functional changes at all in this PR.

move the PrincipalReference type

---

sdk/v2/authz/role_assignments.go
sdk/v2/authz/role_assignments_test.go
sdk/v2/core/project_role_assignments.go
sdk/v2/core/project_roles_assignments_test.go
sdk/v2/lib/authz/role_assignments.go
v2/apiserver/internal/authz/mock_roles_assignments_store.go
v2/apiserver/internal/authz/mongodb/role_assignments_store.go
v2/apiserver/internal/authz/mongodb/role_assignments_store_test.go
v2/apiserver/internal/authz/rest/role_assignments_endpoints.go
v2/apiserver/internal/authz/role_assignments.go
v2/apiserver/internal/authz/role_assignments_test.go
v2/apiserver/internal/core/project_role_assignments.go
v2/apiserver/internal/core/project_role_assignments_test.go
v2/apiserver/internal/core/projects.go
v2/apiserver/internal/core/projects_test.go
v2/apiserver/internal/core/rest/project_role_assignments_endpoints.go
v2/apiserver/internal/lib/authz/role_assignments.go
v2/apiserver/internal/system/authz/authorizers.go
v2/apiserver/internal/system/authz/authorizers_test.go
v2/cli/project_role_commands.go
v2/cli/role_commands.go

Related to #1257
Builds on #1356. That should be merged first and then this needs a rebase.
Like #1356, this is a baby step as part of a larger refactor. It just moves a type to a package that has fewer dependencies to avoid dependency cycles as the refactor continues.
There are no functional changes in this PR.

move RoleAssignment type

---

v2/logger/Dockerfile.winserv-2019

- Removes option 2 (pacman update) from the `ridk install` command, which is currently failing (see https://github.com/brigadecore/brigade/issues/1345).  (The issue appears to be fixed upstream in ridk, but has yet to be released.)
Fixes https://github.com/brigadecore/brigade/issues/1345

fix(logger): fix Windows logger agent build

---

Makefile
sdk/v2/system/api_client.go
v2/apiserver/internal/system/rest/system_endpoints.go
v2/tests/integration_test.go

* adds an unversioned ping endpoint to return a raw api server version string
* re-orgs the integration tests to set up the api clients first/once (and issue a ping check) before running all of the scenarios
Closes https://github.com/brigadecore/brigade/issues/1352

feat(*): add unversioned ping endpoint

---

v2/brigadier/src/events.ts

This PR corrects two issues related to running a brigadier-based script locally in Node.
1. The default event source is currently `github.com/brigadecore/brigade/cli`, but we stopped using that value to represent the source events emitted from the command line quite some time ago, in favor of `brigade.sh/cli`. This PR corrects that.
1. We've been parsing both event source and type from the value of the `BRIGADE_EVENT` by splitting on `:`. This doesn't account for event types that contain colons. (That's allowed.) To fix this, we should split only on the first `:`. Curiously, JS/TS doesn't have an easy way to split a string on only the first n instances of the delimiter, so this PR uses a regex to do the split instead.

brigadier local run fixes

---

sdk/v2/core/events.go
sdk/v2/core/events_test.go
v2/apiserver/internal/core/common_test.go
v2/apiserver/internal/core/events.go
v2/cli/event_commands.go

This simplifies the client and service interfaces for cloning an `Event`. It was previously returning an `EventList` but cloning an `Event` can only ever produce _one_ new `Event`, so it seems simpler to return just an `Event` instead of an `EventList`.
This PR also removes an unused bit of the `MockEventStore`.

minor clone cleanup

---

sdk/v2/core/jobs.go

When status is empty on a job, create fails when called through the rest API because it's marshaled as `"status": null`, and status is not an allowed field on the job document. I have marked it as omitempty so that a nil status isn't included in the json.
```
Bad request: Request body failed JSON validation:
0. (root): Additional property status is not allowed
```
I'm not 100% sure why this is something that just I ran into implementing brigdrake. When brigade uses its own api, does it not go through the json schema validation?

Fix marshal job when status is empty

---

sdk/v2/api_client.go
sdk/v2/api_client_test.go

I noticed today that the system client was missing from the client tree. This PR adds it.

add system client to the client tree

---

sdk/v2/core/events.go
sdk/v2/core/events_test.go
v2/apiserver/internal/core/rest/events_endpoints.go

This is a small, anal retentive tweak. An event can be cloned more than once, so the endpoint for cloning should be `event/<id>/clones` (plural).

small tweak to make event cloning more restful

---

v2/cli/secret_commands.go
v2/cli/secret_commands_test.go

In the first pass at improving how secrets are parsed from a file, we could only handle the simplest substitutions from env vars.
For instance, this was ok:
```yaml
foo=${FOO}
```
But it's a safe assumption that at some point, someone will try something like the following, expecting it to work. They'd end up disappointed:
```yaml
foobar=my-${FOO}-${BAR}
```
This PR corrects this-- and adds a unit test for the function that performs these resolutions.

another improvement to how secrets are parsed from a JSON or YAML file

---

v2/cli/login_command.go

* Removes the extra space padding around the url presented in the login completion message

fix(login_command.go): remove extra spaces in login completion message

---

charts/brigade/templates/apiserver/cert-secret.yaml
charts/brigade/templates/apiserver/ingress-cert-secret.yaml
charts/brigade/templates/apiserver/service.yaml
charts/brigade/values.yaml

Before this PR, cert secrets for both the apiserver pods and apiserver ingress (if applicable) could either be auto-generated and self-signed OR specified directly by the user.
This PR adds a third possibility: that the operator elects neither of those, the chart doesn't generate the corresponding secret at all, and it's left to the operator to provide that secret through unspecified means-- which ideally is a cert manager.
I've tested these scenarios in AKS using the Nnginx ingress controller and the cert-manager, both with default configuration, and letsencrypt as the cert issuer.

improve chart work better with cert manager

---

v2/cli/client.go
v2/cli/client_test.go
v2/cli/common.go
v2/cli/config.go
v2/cli/event_commands.go
v2/cli/log_command.go
v2/cli/login_command.go
v2/cli/logout_command.go
v2/cli/main.go
v2/cli/project_commands.go
v2/cli/project_role_commands.go
v2/cli/role_commands.go
v2/cli/secret_commands.go
v2/cli/service_account_commands.go
v2/cli/user_commands.go

Fixes #1336 
I explored switching from urfave/cli to spf13/cobra and found cobra to be much more onerous and have limitations I didn't care for.
This inspired me to find a totally different solution.
We only use two global flags-- one that is similar to `curl -k` for specifying that cert errors should be ignored, and another that disables interactive prompts-- useful for people who might be scripting against the CLI (even though I wish people would script against the API instead).
For the insecure flag, it seems we could stop having that as a global flag and make it a flag specific to the login command. Then we can just remember (in a local configuration file) whether cert errors are ignored or not, the same way we remember what server you're talking to and what token you're using.
For …

cli: remediate issues related to global flags

---

sdk/v2/meta/errors.go
v2/apiserver/internal/core/logs.go
v2/apiserver/internal/core/logs_test.go
v2/apiserver/internal/meta/errors.go

* Adds a `Reason` field to the `ErrNotFound` struct for instances where further context/explanation is helpful
* Use this new field in the scenario when inherited job logs cannot be found due to the original event no longer existing
Closes https://github.com/brigadecore/brigade/issues/1403

feat(errors.go): add Reason field to ErrNotFound; use in job logs scenario

---

sdk/v2/core/jobs.go
sdk/v2/core/jobs_test.go
v2/apiserver/internal/core/jobs.go
v2/apiserver/internal/core/jobs_test.go
v2/apiserver/internal/core/kubernetes/substrate.go
v2/apiserver/internal/core/rest/jobs_endpoints.go
v2/apiserver/schemas/job.json
v2/brigadier-polyfill/src/jobs.ts
v2/brigadier-polyfill/test/jobs.ts
v2/brigadier/src/jobs.ts
v2/brigadier/test/jobs.ts
v2/internal/kubernetes/common.go
v2/observer/jobs.go
v2/observer/jobs_test.go
v2/observer/observer.go
v2/tests/integration_test.go

* Adds enforcement of timeout logic for jobs
This comprises the Job portion of https://github.com/brigadecore/brigade/issues/1378

feat(observer): enforce job timeout

---

v2/apiserver/internal/core/jobs.go
v2/apiserver/internal/core/jobs_test.go

* Add logic to re-create a job on a retried event if the configuration has changed.
There's one outstanding corner case that would remain.  Currently, this would allow multiple jobs with the same name but differing configuration to be re-created (on a retry event).  I'm wondering if we remove this possibility by putting the responsibility of ensuring there are no duplicate entries in the Worker.Jobs list to the underlying data store.  Currently, we use mongodb and utilize a [$push](https://github.com/brigadecore/brigade/blob/v2/v2/apiserver/internal/core/mongodb/jobs_store.go#L37) directive to add a job to a worker in the store (which allows duplicates).  We could instead change to [$addToSet](https://docs.mongodb.com/manual/reference/operator/update …

ref(jobs.go): re-create retry job if config differs

---

README.md
examples/01-hello-world/project.yaml
examples/02-first-event/project.yaml
examples/03-first-job/project.yaml
examples/04-simple-pipeline/project.yaml
examples/05-groups/project.yaml
examples/06-git/project.yaml
examples/07-npm/project.yaml
examples/08-yarn/project.yaml
examples/09-typescript/project.yaml
examples/10-shared-workspace/project.yaml
examples/11-kitchen-sink/project.yaml
sdk/v2/meta/meta.go
v2/apiserver/internal/meta/meta.go
v2/apiserver/internal/meta/testing/meta.go
v2/apiserver/schemas/common.json
v2/brigadier-polyfill/src/jobs.ts

These are the version bumps that precede our impromptu alpha.5 release.
There will be another round of version bumps post-release because `package.json` files cannot be made to reference the alpha.5 release of brigadier before it exists.

Pre release version bumps

---

README.md

Ever since alpha.4, the `-k` flag for tolerating SSL cert issues has only been relevant to the `login` command (and then the choice is remembered).
This PR catches the README.md up to that reality.

fix usage of -k in README.md

---

v2/observer/healthcheck.go
v2/observer/healthcheck_test.go
v2/observer/jobs.go
v2/observer/jobs_test.go
v2/observer/observer.go
v2/observer/observer_test.go
v2/observer/workers.go
v2/observer/workers_test.go
v2/scheduler/jobs.go
v2/scheduler/jobs_test.go
v2/scheduler/projects.go
v2/scheduler/projects_test.go
v2/scheduler/scheduler.go
v2/scheduler/scheduler_test.go
v2/scheduler/workers.go
v2/scheduler/workers_test.go

Follows up on #1440 to make use of the SDK's new mock clients.
This is a modest increase in LOC, but imho, improves the clarity of the scheduler and observer code quite a bit because it requires a lot less thought about the indirection that is taking place.

make scheduler and observer use new sdk mock clients

---

docs/config.toml
docs/content/_index.md
docs/content/intro/_index.md
docs/content/intro/install.md
docs/content/intro/overview.md
docs/content/intro/quickstart.md
docs/content/topics/github.md
examples/12-first-payload/project.yaml

This refreshes the quickstart and installation instructions for v2.
Affected pages:
* https://deploy-preview-1435--brigade-docs.netlify.app/
* https://deploy-preview-1435--brigade-docs.netlify.app/intro/quickstart/
* https://deploy-preview-1435--brigade-docs.netlify.app/intro/install/
This keeps the quickstart simple. We get installed, define a project, and trigger an event. There is some content commented out currently that I am going to split into a separate page that explains gateways and gets you set up.
One big change in the quickstart is that we don't link you off to another page, for example when installing brigade. QuickStarts lose people (i.e. they drop off and stop, or get lost) when they navigate to another page and then have to go back …

Refresh quickstart and installation instructions for v2

---

examples/02-first-event/project.yaml
examples/03-first-job/project.yaml
examples/04-simple-pipeline/project.yaml
examples/05-groups/project.yaml
examples/10-shared-workspace/project.yaml
examples/11-kitchen-sink/project.yaml
v2/apiserver/internal/core/events.go
v2/apiserver/internal/core/events_test.go
v2/apiserver/internal/core/projects.go
v2/apiserver/internal/core/projects_test.go
v2/cli/event_commands.go
v2/tests/integration_test.go

* Updates logic to ensure that a project only receives events according to their event subscriptions.  The main breaking change is thus: even if an event targets a particular project, it will only be delivered if that particular project is confirmed to be a subscriber.
Closes https://github.com/brigadecore/brigade/issues/1438

ref(*): projects only receive events if subscribed

---

charts/brigade/templates/observer/deployment.yaml
charts/brigade/values.yaml
v2/observer/common.go
v2/observer/common_test.go
v2/observer/jobs.go
v2/observer/jobs_test.go
v2/observer/observer.go
v2/observer/observer_test.go
v2/observer/workers.go
v2/observer/workers_test.go

* Adds the ability for Brigade operators to specify a max lifetime for workers and jobs
Last bit of work for https://github.com/brigadecore/brigade/issues/1378
~~Relies on https://github.com/brigadecore/brigade/pull/1419 and can rebase once 1419 is merged.  Meanwhile, all of the changes specific to this feature are currently in https://github.com/brigadecore/brigade/commit/d8397fa38e91d77816c302e545d8fbc08fb2aae0~~
I've added a default of 24 hours for max lifetime for both workers and jobs -- should we even have a default if left unspecified?

feat(operator):  add max worker + job lifetime configurability

---

v2/brigadier-polyfill/package.json
v2/brigadier-polyfill/src/jobs.ts
v2/brigadier-polyfill/test/jobs.ts
v2/brigadier-polyfill/yarn.lock
v2/brigadier/src/jobs.ts
v2/brigadier/test/jobs.ts
v2/worker/yarn.lock

* Updates Job.run() in brigadier-polyfill to use the [js/ts SDK](https://github.com/brigadecore/brigade-sdk-for-js)
* Had to update brigadier's `ImagePullPolicy` to match the SDK's, so that container specs could be compatible.
Fixes https://github.com/brigadecore/brigade/issues/1291
Willing to re-do the seemingly unrelated yarn.lock changes if y'all can point me how to _only_ add the brigade-sdk dependency :)  I just used `yarn install`.

ref(jobs.ts): update brigadier-polyfill's Job.run() to use sdk

---

v2/apiserver/internal/core/kubernetes/logs_store.go

fix slice index out of bounds in k8s log stream

---

v2/cli/flags.go
v2/cli/service_account_commands.go

* Adds an output format flag to the `brig service-acccount create` command.  This will be handy for automation to quickly/easily parse the returned token value.

feat(cli): add output flag to service account create cmd

---

.brigade/project.yaml

This change has already been applied using:
```console
$ brig project update -f .brigade/project.yaml
```
This PR is only so we have an up-to-date copy of the project definition available as a contingency if we ever have to rebuild our dogfood cluster.

subscribed our own brigade 2 project to push events

---

.brigade/brigade.ts

This fixes a mistake in the `brigade.ts` script. It was looking for ref `/refs/heads/v2` as evidence that the check suite was triggered by a merge to v2, but the value it _should_ be checking for is simply `v2`.

fix edge publishing

---

.github/workflows/merge.yaml
.github/workflows/pr.yaml

We set it at the job level so that the built images will have the correct org as well.

fix(.github): use action env stanza for env vars

---

.brigade/brigade.ts

This fixes an issue with our handling of `check_run:rerequested` events from the next GitHub gateway.

brigade.ts: strip project name from check run name to find job name

---

v2/apiserver/internal/lib/restmachinery/server_test.go

**Update:** thanks to @krancour's suggestion of just using different ports for the test variants in question, this is what I've done.  These 808x ports seem to always be available in a test context and the race condition of one being in use when the next test runs is thus averted.
~~* Adds allowance for "address already in use" errors to pop up in the ListenAndServe tests~~
~~I figured this would be acceptable as it doesn't commonly occur and we ensure any other type of error does fail the test. Thoughts?~~
~~We'll know when it pops up:~~
```
2021/07/08 21:29:01 API server is listening with TLS enabled on 0.0.0.0:8080
=== RUN   TestListenAndServe/TLS_enabled
2021/07/08 21:29:10 API server is listening with TLS enabled on 0.0.0.0:8080
=== RUN   TestListenAndServe/TLS_not_enabled
2021/07/08 …
```

fix(server_test.go): use different ports for ListenAndServe test variants

---

git-sidecar/Dockerfile
git-sidecar/README.md

Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>
Alpine 3.8 is EOL since 2020-05-01.
https://alpinelinux.org/releases/
So, update to the latest supported release.

Update to latest alpine because of EOL

---

sdk/v2/core/jobs.go
v2/apiserver/internal/core/jobs.go

In Kubernetes terms (since our API is heavily inspired by theirs), jobs are "synthetic resources" because they aren't their own thing than can exist independently of something else-- namely an event. This quirk means they're not composed of an `ObjectMeta` and as such were lacking a `Created` date/time stamp field. This info turns out to be useful, however, so this PR adds it.

add creation date/time stamp to jobs

---

v2/apiserver/internal/authn/github/third_party_auth_helper.go
v2/apiserver/internal/authn/github/third_party_auth_helper_test.go

Fixes #1504 
We're already running this in our dogfood cluster and it's working as expected.

3rd party authn: fix how we check for github org membership

---

README.md

Realized that because the brigade-bitbucket-gateway has a master branch (Brigade v1.x compatible) and a new v2 branch (Brigade 2 compatible) it is probably a good idea to link directly to that repo's v2 branch instead of the master branch.

update link in readme for brigade-bitbucket-gateway

---

examples/01-hello-world/project.yaml
examples/06-git/project.yaml
examples/07-npm/project.yaml
examples/08-yarn/project.yaml
examples/09-typescript/project.yaml
examples/12-first-payload/project.yaml

Follow up to #1445 
Since #1445, several examples couldn't be triggered by the CLI because they weren't subscribed to any events from the CLI.
This PR fixes that.

update examples so all subscribe to events from cli

---

docs/content/intro/install.md
docs/content/topics/operators/gateways.md

The link to the GitHub Gateway is broken.
The gateway page itself needs work in a separate PR. A lot of the links are broken because the pages are missing.

Fix link to the github gateway

---

v2/cli/init_templates.go

Fixes #1540 
Uncomments `project.yaml` and brigade script files so the files are ready to go immediately after running `brig init`.

Uncommented project.yaml and js/ts script files

---

docs/config.toml
docs/content/intro/_index.md
docs/content/intro/install.md
docs/content/intro/quickstart.md

* Fixes the 'Read Next' link in the QuickStart doc
* Swaps order of Install and QuickStart docs, so that the next page after QuickStart goes to the Read Next doc
Fixes https://github.com/brigadecore/brigade/issues/1543

fix readnext link; adjust ordering of install and quickstart docs

---

docs/content/intro/install.md

This adds some clarifying text around gateways in the install doc.  @thomastaylor312 suggested the need for this.  @radu-matei also mentioned ngrok... maybe we'll get a full doc on this approach?!
We could also remove mention of gateways from the install doc entirely and only have users see/explore these options in the Topics section(s).  Thoughts?

docs(install.md): add note around gateways

---

docs/content/intro/quickstart.md

Fixes #1547 
Adds instructions to quickstart for using `brig init` instead of downloading a sample project file.

Added brig init instructions to quickstart

---

v2/cli/init_command.go

Noticed during @willie-yao's demo yesterday that we could be more explicit about directing `brig init` users to `.brigade/NOTES.txt` for next steps.

explicitly direct user to NOTES.txt after brig init

---

sdk/v2/authn/users.go
sdk/v2/authn/users_test.go
sdk/v2/testing/authn/mock_users_client.go
v2/apiserver/internal/api/mongodb/project_role_assignments_store.go
v2/apiserver/internal/api/mongodb/project_role_assignments_store_test.go
v2/apiserver/internal/api/mongodb/role_assignments_store.go
v2/apiserver/internal/api/mongodb/role_assignments_store_test.go
v2/apiserver/internal/api/mongodb/users_store.go
v2/apiserver/internal/api/mongodb/users_store_test.go
v2/apiserver/internal/api/project_role_assignments.go
v2/apiserver/internal/api/project_role_assignments_test.go
v2/apiserver/internal/api/projects_test.go
v2/apiserver/internal/api/rest/users_endpoints.go
v2/apiserver/internal/api/role_assignments.go
v2/apiserver/internal/api/role_assignments_test.go
v2/apiserver/internal/api/users.go
v2/apiserver/internal/api/users_test.go
v2/apiserver/main.go
v2/cli/user_commands.go

Initially, there was no delete user functionality. The rationale behind that was that when third party authn is enabled, a deleted user could _still_ return and seamlessly federate. Locking users instead of deleting them seemed reasonable, but that meant users you wish you could have deleted hang around forever.
#1457 changed that. Because authn can be limited to users in particular orgs, it's easy not to ensure a deleted user _can't_ just come back and federate anew.
On top of that, #1528 cleared some technical hurdles that would have made deleting users very difficult.
So... here it is... we can delete users now.

add user delete functionality

---

docs/content/intro/quickstart.md

In the docs, there's a link to a scripting tutorial, but it points back to the intro where the user just came from. This PR points the link to the right scripting guide.

Fix wrong anchor

---

v2/brigadier-polyfill/package.json
v2/brigadier-polyfill/yarn.lock
v2/brigadier/package.json
v2/brigadier/yarn.lock
v2/worker/Dockerfile
v2/worker/package.json
v2/worker/yarn.lock

Four days ago, the latest version of TypeScript available from npm took a leap from 4.1.6 to 4.4.2.
Semantic versioning would lead one to expect there were no breaking changes between 4.1.6 and 4.4.2, but alas, that isn't the case.
Our use of `yarn install --prod` for each of brigadier, brigadier-polyfill, and the worker itself in the worker's Dockerfile meant we had to source TypeScript from elsewhere to be able to compile, so an `npm install -g typescript` appeared in the Dockerfile. As stated, this took a large leap in the last few days and started breaking things.
My solution here, for each of the three components in question, is to pin us to `typescript@4.1.6` _specifically_ (not `^4.1.6`, which would allow automatically using the latest minor release in 4.x.) _and_ to lift that out …

fix broken worker build

---

.brigade/brigade.ts
Makefile
v2/worker/Dockerfile

The version of Node we were using was pretty old. This upgrades to the latest LTS release. It also corrects the oversight that we weren't using the same Node version across the board.

chore: upgrade node

---

sdk/v2/core/events.go
sdk/v2/core/events_test.go
sdk/v2/testing/core/mock_events_client.go
v2/apiserver/internal/api/events.go
v2/apiserver/internal/api/events_test.go
v2/apiserver/internal/api/mongodb/events_store.go
v2/apiserver/internal/api/mongodb/events_store_test.go
v2/apiserver/internal/api/rest/events_endpoints.go
v2/apiserver/main.go
v2/apiserver/schemas/event-summary.json

This is a the first of a few PRs that will, in aggregate, address #1590.
This particular PR adds the summary in the API server and the Go SDK.
Once the API server supports this, I'll open a PR against the sdk-for-js.
Once that is merged, the final part will be another PR to this project, to make the worker use the latest sdk-for-js to update the event summary on success.

add event summary field

---

.brigade/brigade.ts
Makefile
docs/content/intro/install.md
docs/content/intro/quickstart.md
docs/content/topics/operators/deploy.md
v2/cli/init_templates.go

Fixes #1594 
This also includes pre-release version bumps because beta.2 was published using Helm 3.6 and is _not_ compatible with these Helm 3.7+ instructions.
i.e. We need to release beta.3 after we merge this.
While already touching quickstart and install instructions, I also switched from using "brigade2" as the release and namespace name and started using just plain "brigade."
The instructions were originally written with users who are already running brigade 1.x in mind, but as v2 marches closer to GA, we can start treating v2 as our assumption when "brigade" is discussed.

upgrade to helm 3.7.0 ga + pre-release version bumps

---

v2/tests/testcases.go

Oops, I renamed the default branch on the `empty-testbed` repo from `master` to `main` earlier today.  This updates the integration tests that use this value.

fix(integration tests): update empty-testbed branch

---

Makefile

The chart publishing process was mistakenly not updated for Helm 3.7.0, event though all docs and absolutely everything else was updated for Helm 3.7.0.

fix chart publishing issue

---

docs/content/topics/operators/security.md

* Updates the Security doc per v2
I admittedly didn't come up with a bunch of new material for this one.  Maybe someone more enthusiastic about adding new or updated text can chime in?  (Note: totally fine if commits from maintainers are pushed to this branch.)  Otherwise, we'll at least have updated the previous points per v2.
Preview: https://deploy-preview-1609--brigade-docs.netlify.app/topics/operators/security/
Closes https://github.com/brigadecore/brigade/issues/1608

docs(security.md): v2 updates

---

charts/brigade/templates/apiserver/cluster-role-binding.yaml
charts/brigade/templates/apiserver/cluster-role.yaml
charts/brigade/templates/apiserver/deployment.yaml
charts/brigade/templates/logger/cluster-role-binding.yaml
charts/brigade/templates/logger/cluster-role.yaml
charts/brigade/templates/logger/secret.yaml
charts/brigade/templates/observer/cluster-role-binding.yaml
charts/brigade/templates/observer/cluster-role.yaml
charts/brigade/templates/observer/deployment.yaml
charts/brigade/values.yaml
docs/content/topics/operators/security.md
v2/apiserver/config.go
v2/apiserver/config_test.go
v2/apiserver/internal/api/kubernetes/substrate.go
v2/apiserver/internal/api/kubernetes/substrate_test.go
v2/internal/kubernetes/common.go
v2/observer/jobs.go
v2/observer/observer.go
v2/observer/observer_test.go
v2/observer/workers.go

Fixes #1630
This PR injects a unique-to-the-cluster "Brigade ID" into the apiserver and observer. Both of those incorporate this new metadata into all labels and label selectors.
Fluentd configs also get updated so that only logs from a given Brigade instance are sent to that Brigade instance's database.

Support more than one brigade instance per cluster

---

charts/brigade/templates/_helpers.tpl
charts/brigade/templates/apiserver/ingress.yaml
charts/brigade/values.yaml

Also rewrite API version handling according to https://github.com/brigadecore/charts/pull/92.
closes #1626
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>

Add support for `ingressClassName` to v2 Helm charts

---

v2/artemis/Dockerfile

This fixes recent issues with the Artemis Docker image build.
It seems the root cause is that, annoyingly, the format of the download URL for the latest release and previous releases varies in ways beyond version number.
I've left a note to this effect in the Dockerfile so that it is easier to diagnose and repair this issue if it recurs.

fix artemis image build

---

v2/logger-linux/Dockerfile
v2/logger-windows/Dockerfile

The main point of this PR is to reduce build time for the Windows-based logger image by starting from an image that already has most of what we need. We didn't do this initially because the base image this PR uses didn't exist until relatively recently.
At the same time, I've updated various gems/fluentd plugins on the Windows-based logger image to match the versions used on the Linux-based logger image. The latter were updated fairly recently and it was an oversight that the Windows-based image didn't receive the same changes.
Last, both the Windows-based and Linux-based images now use `fluent/fluentd` images as their base instead of `fluentd`. `fluentd` trails `fluent/fluentd` by a couple major versions and also does not offer Windows-based images.

update logger Dockerfiles

---

Makefile
charts/brigade/templates/apiserver/deployment.yaml
charts/brigade/values.yaml
examples/15-windows/project.yaml
sdk/v2/core/jobs.go
v2/apiserver/config.go
v2/apiserver/config_test.go
v2/apiserver/internal/api/jobs.go
v2/apiserver/internal/api/kubernetes/substrate.go
v2/apiserver/internal/api/kubernetes/substrate_test.go

This corrects several overlooked aspects of our support for Windows-based jobs:
1. When applicable, uses node selector to request scheduling on a Windows node.
2. When applicable, uses a toleration to _tolerate_ being scheduled on a Windows node.
3. When applicable, uses Windows-based variant of git initializer component.
4. Adds a Windows example

improved windows support

---

.github/workflows/release.yaml

Noticed recently that we successfully publish images tagged "edge" and with short git SHA on ever merge to v2... but we're _not_ publishing images tagged "latest" and with the semantic version number on each release.
This is because `VERSION=xxx` is missing from the publishing commands.
This PR is a quick and dirty fix. There's probably a more elegant way to do this, but GitHub Actions isn't where I want to be spending my time.

fix release process for windows images

---

charts/brigade/Chart.lock
charts/brigade/Chart.yaml
charts/brigade/templates/NOTES.txt
charts/brigade/templates/apiserver/deployment.yaml
charts/brigade/templates/logger/secret.yaml
charts/brigade/values.yaml

This PR upgrades to the latest MongoDB subchart.
There are a lot of changes to that chart since we last upgraded it and some are "breaking-ish." (Lots of deprecated fields.)
It want to settle this now before we go RC/GA because if the subchart has changes of this magnitude in the future, we aren't going to want to take the upgrade because of how it will impact our own users who have MongoDB configuration embedded in their Brigade deployment's `values.yaml`.
Note to reviewer: Most of the changes are to `values.yaml`. The subchart's `values.yaml` was added wholesale to our own `values.yaml` and minimally modified for our purposes. (e.g. Specified creation of "`brigade` database and username/password.)
All the other changes to the chart, just adapt to those `values.yaml` changes. For …

chart: upgrade mongodb

---

v2/apiserver/schemas/event.json
v2/apiserver/schemas/project.json
v2/apiserver/schemas/source-state.json

Fixes #1736
This change is already applied to the dogfood cluster. Without it, we couldn't get anything to build because the GitHub gateway uses uppercase characters in some label and qualifier keys.

fix restrictions on allowed chars in label and qualifier keys

---

examples/15-windows/project.yaml

This PR fixes 3 issues with the Windows example:
* There is no `mcr.microsoft.com/windows/nanoserver:latest`, so we need to explicitly specify a version of Windows. `mcr.microsoft.com/windows/nanoserver:1809` works well on a Windows-based AKS node.
* Host selection was previously done incorrectly in this example.
* `echo` is not a recognized command in and of itself. We need to start the `cmd.exe` shell and execute `echo` within it.

fix windows example

---

.brigade/brigade.ts
sdk/v2/meta/meta.go
v2/apiserver/internal/meta/meta.go
v2/apiserver/internal/meta/testing/meta.go
v2/apiserver/schemas/common.json
v2/brigadier-polyfill/package.json
v2/brigadier-polyfill/yarn.lock
v2/cli/init_templates.go

In preparation for the RC.1 release, this PR transitions client and server components to using the stable API.
Note that we're not updating example yet. If we did so, no one would be able to run them until after rc.1 is released. So we'll update them later in a separate PR-- this means example validation during CI is also, temporarily, disabled.

switch to stable API

---

charts/brigade/templates/logger/windows-daemonset.yaml

mount fluentd config to the correct location in a windows-based logger agent

---

charts/brigade/templates/NOTES.txt

The notes template didn't take the recent MongoDB subchart upgrade into account. This PR fixes it.

bug: chart: fix database name in notes

---

.brigade/project.yaml

The dogfood cluster is now running a custom build from the head of the `v2` branch -- which is close to what we will release as rc.1.
This PR updates the project definition file accordingly. Updating this file doesn't really have any bearing on any of our automation, but it does impact our ability to recreate the project from this definition in the future.

switch our own builds to stable api

---

.brigade/brigade.ts

This job had temporarily been disabled at a point in time (which we are now past) where the schemas and examples didn't agree on API version.

re-enable the validate example job

---

.github/workflows/release.yaml

This PR remediates the only issue we encountered with release automation during the rc.1 release.
Correct tags were not applied to the images when they were built, so the pushes, which did use correct tags, failed.
A reminder to any reviewer... we are currently leaning on GitHub Actions only for building and publishing our very few Windows-based Docker images because it doesn't yet seem possible to build a Windows-based image inside a container (ala Docker-in-Docker) yet. So we need a Windows VM to accomplish this and that rules out doing it with Brigade itself. GitHub Actions has us covered.

release automation: fix windows image publishing

---

v2/brigadier/src/events.ts

When a worker is created, it receives the event as a JSON file that's mounted into the container. That JSON already includes qualifiers and labels, but they were not accessible in scripts because the `Event` type in the Brigadier library was mistakenly missing those fields.
I am correcting this because further work on the GitHub gateway has uncovered the fact that there are times that gateways can and should extract meaningful information from payloads, do some pre-processing, and apply corresponding values to qualifiers or labels. It would be helpful if scripts had access to that information.
A good example of the above is a `check_run` webhook from GitHub. It will contain the `check_run`'s name and that name will be of the form `<project id>:<job name>`. The gateway can parse that and …

add qualifiers and labels fields to brigadier event type

---

v2/apiserver/internal/api/rest/users_endpoints.go

`return` should have immediately followed `restmachinery.WriteAPIResponse()`. It was misplaced and was causing a return with an empty response body if the request specified a valid limit.
Removal of the redundant conditionals is incidental to the fix.

bug: fix user list endpoint

---

v2/brigadier-polyfill/src/jobs.ts
v2/brigadier/src/jobs.ts
v2/tests/integration_test.go
v2/tests/testcases_test.go

Fixes #1768
This sample project demonstrates a job that fails and a worker that succeeds regardless.
```
apiVersion: brigade.sh/v2
kind: Project
metadata:
id: experiment
description: My new Brigade project
spec:
eventSubscriptions:
- source: brigade.sh/cli
types:
- exec
workerTemplate:
logLevel: DEBUG
defaultConfigFiles:
brigade.ts: |
import { events, Job } from "@brigadecore/brigadier"
events.on("brigade.sh/cli", "exec", async event => {
let job = new Job("hello", "debian:latest", event)
job.primaryContainer.command = ["false"]
job.fallible = true
await job.run()
})
events.process()
```

brigadier: allow jobs to be marked as fallible

---

.brigade/package.json
.brigade/yarn.lock
examples/09-npm/.brigade/package-lock.json
examples/09-npm/.brigade/package.json
examples/10-yarn/.brigade/package.json
examples/10-yarn/.brigade/yarn.lock
examples/12-kitchen-sink/.brigade/package.json
examples/12-kitchen-sink/.brigade/yarn.lock
examples/gateways/example-gateway/go.mod
examples/gateways/example-gateway/go.sum

Per usual, these post-release version bumps update examples (and our own Brigade configs) so that they use the release we just cut.

post-release version bumps

---

docs/themes/techdoc-brigade/layouts/partials/header.html

Related to #1758
https://v1.docs.brigade.sh exists now. This PR just updates the header in the v2 docs to use this new address.

update v1 docs link in v2 docs banner

---

.brigade/brigade.ts

`yarn audit` failures are recently causing PRs that don't even touch any TS/JS to fail.
Those issues will be addressed, of course, but in the meantime, we don't want them creating a bottleneck, so this PR marks that job fallible in our CI pipeline.
We've already implemented this strategy on other repos and even on the `v1` branch of this repo.

ci: make yarn audit job fallible

---

sdk/v3/principals.go

This bug was introduced in #1796 and only exists in `main` and has not ever been released.
In #1796, `PrincipalReference` objects where returned as a "top level" object in an API response for the first time and to match everything else "top level" in the API, we started augmenting them with `APIVersion` and `Kind` when marshaling to JSON.
For consistency, _outbound_ `PrincipalReference` objects from the SDK got the same treatment, even though they're never used as "top level" objects on an outbound request. But the existing JSON schema used to validate inbound requests doesn't permit those fields there.
I considered updating the schema to make those fields optional for a `PrincipalReference`, but the result would be that newer clients that include this info in and outbound …

fix role/project-role grant/revoke bug

---

v2/apiserver/internal/lib/queue/amqp/writer.go

I've discovered the source of a known bug while investigating #1821.
This AMQP client connect/re-connect logic is managed by `retries.ManageRetries(...)`. The retry logic works well when refreshing a stale connection, however, if there is no connection and it attempts to dial the message server for the first time, and fails, the AMQP client is no longer nil, but _also_ is not fully initialized. On the _next_ retry, the call to `w.amqpClient.Close()` will trigger a nil pointer dereference. 😦 
We've _frequently_ seen panics related to this in API server startup logs.
The reason this hasn't been a bigger problem than it has been to date is that Artemis usually comes up faster than MongoDB. The API server ends up crashing and restarting itself several times before MongoDB is up and running, …

fix bug in message writing abstaction

---

v2/apiserver/main.go
v2/observer/main.go
v2/scheduler/main.go

Fixes #1821 
On a brand new KinD cluster (image cache not primed) on my MBP, `helm install` now succeeds in about 1 minute with no services restarting in the process.
__Edit:__ This is such a significant improvement that I'm going to plan on a v2.3.1 release to put this in people's hands as soon as possible.

Smoother startup

---

docs/content/_index.md
docs/content/intro/_index.md
docs/content/intro/readnext.md
docs/content/topics/_index.md
docs/content/topics/administrators/_index.md
docs/content/topics/administrators/authentication.md
docs/content/topics/administrators/authorization.md
docs/content/topics/contributing.md
docs/content/topics/developers.md
docs/content/topics/examples.md
docs/content/topics/operators/_index.md
docs/content/topics/operators/gateways.md
docs/content/topics/operators/security.md
docs/content/topics/operators/storage.md
docs/content/topics/project-developers/_index.md
docs/content/topics/project-developers/brig.md
docs/content/topics/project-developers/brigterm.md
docs/content/topics/project-developers/events.md
docs/content/topics/project-developers/projects.md
docs/content/topics/project-developers/secrets.md
docs/content/topics/releasing.md
docs/content/topics/scripting/_index.md
docs/content/topics/scripting/advanced.md
docs/content/topics/scripting/brigadier.md
docs/content/topics/scripting/dependencies.md
docs/content/topics/scripting/guide.md
docs/content/topics/scripting/workers.md

The main fix in this PR is that a superfluous h1 heading is removed from the top of most doc pages. Documents should have only _one_ top-level heading and Hugo automatically uses the title found in the front matter to generate an h1 heading, so in most cases, we had duplicate or near duplicate text. The stylesheet is clever about changing the stying of a _second_ h1, but it's still superfluous and afaik breaks the rules of semantic HTML.
There are other various heading-related fixes here, too, and I'll drop some comments in-line to explain wherever warranted.

docs: fix several headings

---

docs/content/intro/quickstart.md

Multiple people, including a technical writer have suggested to me that since most of the instructions in the Quickstart are not KinD-specific, we should probably remove the KinD instructions from the beginning and just leave it at something along the lines of "you need a local cluster; we suggest KinD." The overall effect is that the Quickstart is shorter and therefore less intimidating. It also doesn't unnecessarily send minikube users off on a KinD tangent.

docs: remove KinD instructions from quickstart

---

docs/config.toml
docs/content/intro/quickstart.md
docs/content/topics/administrators/authorization.md
docs/content/topics/developers.md
docs/content/topics/operators/deploy.md
docs/content/topics/operators/gateways.md
docs/content/topics/operators/storage.md
docs/content/topics/project-developers/brig.md
docs/content/topics/project-developers/brigterm.md
docs/content/topics/project-developers/projects.md
docs/content/topics/project-developers/secrets.md
docs/content/topics/scripting/advanced.md
docs/content/topics/scripting/brigadier.md
docs/content/topics/scripting/dependencies.md
docs/content/topics/scripting/guide.md
docs/content/topics/scripting/workers.md

I recently bumped the version of Hugo that we're using on Netlify to a much newer one and all doc preview deployments since have poor contrast in the code blocks.
Digging into this, the reason is that Hugo, at some point, changed the component they use internally for source code highlighting. This PR does two things:
1. Explicitly select the code syntax highlighting style that most closely resembles what Hugo previously used (pyment).
2. Updates "code fences" in all content because `console` is not a valid/supported language in the new syntax highlighter.
No other doc PRs can be merged until this one is or else we'll be deploying with the poor contrast issue.

Code highlighting fixes

---

Makefile
v2/apiserver/Dockerfile
v2/apiserver/internal/api/kubernetes/substrate.go
v2/artemis/Dockerfile
v2/git-initializer/Dockerfile
v2/logger/Dockerfile
v2/observer/Dockerfile
v2/scheduler/Dockerfile
v2/worker/Dockerfile
v2/worker/package.json
v2/worker/src/prestart.ts
v2/worker/yarn.lock

See #1864 
When scanned, alpine-based images produce more favorable results than debian-based images.
Using `gcr.io/distroless/static:nonroot` as a base image, surprisingly, is also regarded as safer than using`scratch` as a base image. (It runs as a non-root user without requiring us to do all the legwork.)

update all images to present less attackable surface

---

docs/content/intro/quickstart.md

Signed-off-by: Anurag Pathak <anuragpathak911@gmail.com>
Fixes #1544 
This PR adds a disclaimer regarding the use of root login in a production cluster on the Brigade Quickstart page.

Update quickstart.md with root login disclaimer

---

.brigade/brigade.ts
Makefile
examples/gateways/example-gateway/go.mod
examples/gateways/example-gateway/go.sum
golangci.yaml
sdk/v3/go.mod
v2/apiserver/Dockerfile
v2/git-initializer/Dockerfile
v2/go.mod
v2/observer/Dockerfile
v2/scheduler/Dockerfile

This PR upgrades us to Go 1.18 across the board. Even though the SDK is build with Go 1.18, we're not using any Go 1.18-specific features because we don't want to force SDK users to upgrade to Go 1.18 yet if they're not ready.
We'll start taking advantage of generics (server side) in a follow-up to avoid this simple PR becoming unnecessarily bloated.

upgrade to go-tools v0.8.0 -- includes go 1.18

---

.brigade/brigade.ts

Although this script doesn't have a discrepancy like the one from https://github.com/brigadecore/brigade-github-gateway/pull/97, this change will help reduce the possibility of such a discrepancy in the future.

ci: minor improvement to PublishSBOMJob class

---

.brigade/brigade.ts

This should have been included in #1883 
We use `ghr` for publishing and that isn't in the go-tools image prior to v0.3.0.

upgrade docker-tools to v0.3.0

---

v2/apiserver/internal/api/projects.go
v2/apiserver/internal/api/projects_test.go

Signed-off-by: Anurag Pathak <anuragpathak911@gmail.com>
Fixes #1750 
When a project delete request is sent, instead of directly checking for PROJECT_ADMIN role we'll now be checking if the project exists first so that we can avoid getting unauthorized error when the project doesn't exist.

Fix deleting a non-existing project tells you're unauthorized

---

v2/worker/Dockerfile

This runs the first stage of the worker build only on the native architecture, which should dramatically improve build time.

run first stage of worker build only on native architecture

---

.brigade/brigade.ts

Noticed nightly cleanup has been failing since #1892. The job wasn't yanking down source so it couldn't execute the new cleanup script that #1892 introduced.
This PR fixes that.
My apologies for not catching this in review.

make nightly cleanup job use source

---

v2/apiserver/internal/api/secrets.go
v2/apiserver/internal/api/secrets_test.go

@AnuragThePathak PR'ed a nice improvement to the `SecretService` in #1900, and discovered that tests for that service were completely missing.
This PR adds them.
Let's get this merged before #1900 so that he can make the incremental test changes that validate the service changes he's made.

api server: add tests for secrets service

---

v2/apiserver/internal/api/secrets.go
v2/apiserver/internal/api/secrets_test.go

Signed-off-by: Anurag Pathak <anuragpathak911@gmail.com>
Fixes #1893 
While setting a secret, instead of directly checking for PROJECT_ADMIN role we'll now be checking if the user is a READER followed by checking if the project exists so that we can avoid getting unauthorized error when the project doesn't exist.

Fix setting secrets on a non-existing project tells you're unauthorized

---

docs/content/intro/quickstart.md

Fixes #1781 
This PR just reorders some existing quickstart content so it flows a bit more smoothly. (See #1781 for further qualification.)
Also, with some sections already moving around, thus impacting the tree, I did change some of those links and their corresponding section headings to keep them in a more consistent voice. It was, for instance, strange to have some section headings use imperative language like "Install Brigade," while others did not, e.g. "Trying It Out."

docs: improve flow through the quickstart

---

v2/cli/event_commands.go

Fixes #1824
All that was needed was for the flags to be added to the command. Everything else was already in place.

cli: add source and type filters to event list command

---

v2/apiserver/internal/api/events.go
v2/apiserver/internal/api/events_test.go
v2/apiserver/internal/api/kubernetes/secrets_store.go
v2/apiserver/internal/api/kubernetes/secrets_store_test.go
v2/apiserver/internal/api/mongodb/events_store.go
v2/apiserver/internal/api/mongodb/events_store_test.go
v2/apiserver/internal/api/mongodb/project_role_assignments_store.go
v2/apiserver/internal/api/mongodb/project_role_assignments_store_test.go
v2/apiserver/internal/api/mongodb/projects_store.go
v2/apiserver/internal/api/mongodb/projects_store_test.go
v2/apiserver/internal/api/mongodb/role_assignments_store.go
v2/apiserver/internal/api/mongodb/role_assignments_store_test.go
v2/apiserver/internal/api/mongodb/service_accounts_store.go
v2/apiserver/internal/api/mongodb/service_accounts_store_test.go
v2/apiserver/internal/api/mongodb/users_store.go
v2/apiserver/internal/api/mongodb/users_store_test.go
v2/apiserver/internal/api/project_role_assignments.go
v2/apiserver/internal/api/project_role_assignments_test.go
v2/apiserver/internal/api/projects.go
v2/apiserver/internal/api/projects_test.go
v2/apiserver/internal/api/role_assignments.go
v2/apiserver/internal/api/role_assignments_test.go
v2/apiserver/internal/api/secrets.go
v2/apiserver/internal/api/secrets_test.go
v2/apiserver/internal/api/service_accounts.go
v2/apiserver/internal/api/service_accounts_test.go
v2/apiserver/internal/api/users.go
v2/apiserver/internal/api/users_test.go
v2/apiserver/internal/meta/list.go
v2/apiserver/internal/meta/list_test.go

Follow up to #1808 
Starts to make use of generics.
This PR is decomposed into the following commits:
* Add generic list type
* Remove non-generic list types
* Transition all API server code from non-generic list types to the generic list type
* Resolving conflicts that arose after #1903 added new units tests
There are no functional changes in this PR.
Additionally, I've proactively commented in-line on the very, very few changes wherein the reason for them might not be immediately evident without explanation.

add generic List type to API server and use throughout

---

v2/apiserver/Dockerfile
v2/git-initializer/Dockerfile
v2/observer/Dockerfile
v2/scheduler/Dockerfile

This PR makes image builds that include binaries built with Go a little bit faster when they're done repeatedly (e.g. during dev). It does this by caching the results of dependency resolution in a separate layer of each image.

Dockerfiles: cache go mods in their own layer

---

charts/brigade/Chart.yaml
charts/brigade/templates/NOTES.txt
charts/brigade/templates/deployments.yaml
charts/brigade/templates/logger/secret.yaml
charts/brigade/values.yaml
v2/apiserver/config.go
v2/apiserver/config_test.go

Fixes #1876
cc @emilwangaa
__EDIT:__
I pre-built docker images so anyone can try this.
⚠️ You need to check out this branch because the chart itself has modifications.
```console
$ export DOCKER_ORG=krancour
$ export TAG=14ff4f1
$ export MONGODB_CONNECTION_STRING=mongodb://<whatever>
$ export MONGODB_DATABASE_NAME=<whatever>
$ helm dep up charts/brigade
$ kubectl create namespace brigade
$ helm install brigade charts/brigade \
--namespace brigade \
--set artemis.image.repository=$DOCKER_ORG/brigade2-artemis \
--set artemis.image.tag=$TAG \
--set apiserver.image.repository=$DOCKER_ORG/brigade2-apiserver \
--set apiserver.image.tag=$TAG \
--set scheduler.image.repository=$DOCKER_ORG/brigade2-scheduler \
--set scheduler.image.tag=$TAG \
--set …
```

support externally hosted mongodb

---

charts/brigade/templates/deployments.yaml

A while ago, we introduced behavior in the chart where certain secret values are generated randomly on initial install, but on subsequent `helm upgrade` operations, existing values are retrieved and reused. This has led to a more stable upgrade process.
This falls apart, however, in cases where there's no cluster to connect to to find existing secrets _and_ you need the secrets to have stable, unchanging values. Namely this can happen when using Tilt (see #1910) at dev time since Tilt never does `helm install` or `helm upgrade`, but rather only does `helm template` and then applies the returned YAML.
i.e. We want this ability if we want to limit  unnecessary refreshes of components at dev time just because some token got a new random value every time the chart is rendered.
Note that I did …

chart: add ability to hard-config API tokens at dev time

---

charts/brigade/templates/deployments.yaml

This is a very minor and non-breaking chart change.
What it does is prevents the apiserver from having a dependencies on secrets that "owned" by the observer and the scheduler.
This isn't usually a problem, but #1910 will move us to using Tilt to facilitate a tighter, faster "inner-loop" during dev and Tilt has an interesting feature that k8s itself lacks -- the ability to understand dependencies between components in your microservice architecure. We can use this to improve devx a tiny bit further by preventing the apiserver from starting before the database and queue are ready, and we can likewise prevent the observer and scheduler from starting before the apiserver is ready.
If, however, the apiserver depends on secrets "owned" by the observer and scheduler, we create a dependency …

chart: don't share secrets across components

---

sdk/v3/jobs.go
v2/apiserver/internal/api/jobs.go
v2/apiserver/schemas/job.json

Since #1772 we've allowed jobs to be marked as allowed to fail without impacting the overall success or failure of the worker.
Until now, the worker has kept this information to itself.
This is the first of a few related PRs that will get the worker to start sharing this information with the API server when it creates new jobs.
The API server won't do anything directly with this information, however, having this information available makes it possible to share with gateways that monitor event/job status and report that status upstream. For a perfect example, see https://github.com/brigadecore/brigade-github-gateway/issues/93

Fallible jobs pt2

---

Makefile
hack/kind/cluster.yaml

This PR creates a less hacky alternative `make hack-new-kind-cluster` script.
This PR does not remove the old way of doing things. We can revisit after #1908 is amended appropriately and merged.

devx: use ctlptl as alternative to hacky kind script

---

CONTRIBUTING.md

I toyed with deleting this file completely and linking to the new docs from the `README.md`, but I believe the presence of a `CONTRIBUTING.md` file has become a _de facto_ convention.

update CONTRIBUTING.md to point to docs

---

Makefile

Only production dependencies make it into the image, so I'm counting it as noise when `yarn audit` finds issues with dependencies that are only used during development.

Makefile: only include production dependencies in yarn audits

---

docs/content/topics/contributor-guide/_index.md
docs/content/topics/contributor-guide/ladder.md

This new contributor ladder tentatively expands, revises, and replaces https://github.com/brigadecore/community/blob/main/governance.md
This is based heavily on work @carolynvs has done in TAG Contributor Strategy, and revised a good deal to suit the needs of the project.
Note that it was a deliberate choice to refrain from quantifying phrases like "several contributions" or "regularly contributing." I felt that at this stage of the project, leaving these subjective gives the project maintainers and core maintainers greater latitude and discretion in moving contributors up and down the ladder. There is no reason that cannot be revised in the future as the community grows and its needs change.
If this is somewhat lacking on details relating to code review processes, that is because those …

add contributor ladder

---

.brigade/brigade.ts
docs/content/topics/project-developers/projects.md
v2/git-initializer/main.go
v2/tests/testcases_test.go

On Slack, @emilwangaa wrote:
> in v1 we could set a github token + HTTPS cloneUrl in our project definitions to access private git repositories. In v2 it looks like only SSH keys and git+ssh urls are supported for private repos. Is this a deliberate design decision? Or am I just missing something? (and sorry that I keep bugging you with questions).
This PR addresses this issue.
The feature prompted several modifications to the docs on creating/managing projects, so that section ended up with a comprehensive overhaul. I _think_ they cover the new details well and are more succinct with no real loss of detail.
I will publish a custom build of this branch shortly so @emilwangaa can take this for a test drive.

feature: support basic auth for private repos

---

.github/PULL_REQUEST_TEMPLATE.md

The PR template was getting a bit stale. The contributing docs have moved since it was written, it was still referencing the MS code of conduct instead of the CNCF one, and it was also written before draft PRs were a thing.
This PR should bring everything up to date.

chore: update the PR template

---

v2/apiserver/schemas/common.json

I'm not sure why we ever limited the length of qualifiers and labels so aggressively. These are never applied to labels on any k8s resources, so that's not the reason. In all probability, we modeled it after _limitations_ of k8s labels and annotations just in case.
Now there's a good reason to accept longer qualifer and label values -- namely CloudEvents can have very long values in the source field. This is a _different_ source field than the source field on a Brigade event. The CloudEvents gateway always take the value of the CloudEvent's source field and preserves it by popping it into a Brigade event qualifier.
So bottom line is we need this change in order to get the CloudEvents gateway to go GA.
You can already see this works here:
https://dashboard.brigade2.io/projects/acr-demo …

allow longer event qualifier and label values

---

v2/brigadier-polyfill/package.json
v2/brigadier-polyfill/yarn.lock
v2/worker/yarn.lock

Bumping to sdk-for-js v2.4.1 allows the transitive dependency on eventsource to be bumped to v2.0.2 as recommended.

upgrade sdk-for-js to address CVE-2022-1650

---

charts/brigade/Chart.yaml

Bitnami seems to have dropped v10.29.2 from their repo sometime in the last 24 hours.

upgrade to mongodb v10.31.5

---

README.md
docs/content/topics/operators/gateways.md

The ACR gateway was archived a week or two ago (without ever having reached GA) because the CloudEvents gateway provides sufficient integration with ACR.
This PR removes mention of the ACR gateway from the docs.

remove mention of acr gateway

---

charts/brigade/values.yaml

These config options are accidental remnants from an early prototype of Brigade 2 and are completely unused.

remove unused sections of values.yaml

---

charts/brigade/Chart.lock

The `Chart.lock` file was out of sync with `Chart.yaml`. This PR fixes it.

fix Chart.lock file
