brigadecore/brigade

README.md, docs/topics/developers.md
after [running into problems](https://github.com/Azure/brigade/issues/66) following the README for building brig, i added improvements to the developer guide and a tip in the README.
=> update brig cli build docs and dev guide

docs/topics/storage.md
This explains how Brigade uses storage.
Closes #14
=> docs(topics): add storage document

brigade-client/cmd/brig/commands/run.go, brigade-controller/cmd/brigade-controller/controller/controller_test.go, brigade-controller/cmd/brigade-controller/controller/handler.go, brigade-worker/prestart.js
This makes the acid.js an optional parameter of the event secret.
If it is not specified, the worker will attempt to get the file out of
an attached VCS repo.
(Migrated from old repo)
=> feat(controller,worker): acid.js not required

pkg/version/version.go
=> fix(version): add doc block

docs/topics/index.md, docs/topics/install.md, docs/topics/projects.md
Document configuring projects.
=> docs(topics): add projects.md document

brigade-client/cmd/brig/commands/run.go
Also, increase wait time to 5 seconds.
=> fix(brig): increase timeout for log streaming

brigade-controller/cmd/brigade-controller/controller/handler.go
`s/brgiade-worker/brigade-worker/`
=> fix(controller): fix typo in image name

brigade-controller/cmd/brigade-controller/controller/controller.go, brigade-controller/cmd/brigade-controller/controller/controller_test.go, brigade-controller/cmd/brigade-controller/controller/handler.go, brigade-controller/cmd/brigade-controller/controller/informer.go, brigade-controller/cmd/brigade-controller/main.go, chart/brigade/templates/controller-deployment.yaml, chart/brigade/values.yaml
Why this pr:
Now worker setting (image, pull policy) is hard-coded in controller, hope moving this to values will be more configurable.
=> move worker related setting to values

brigade-client/README.md, brigade-client/cmd/brig/commands/app.go
This removes the last of the `lsd` references.
=> docs(brig): update Brig help text

brigade-worker/Dockerfile
Why this pr:
This is proposed for better developing and ci/cd experience. If there is no special concern on node image version.
=> change node:8 -> node:8-alpine

brigade.js
changed `glide` to `dep` in project's brigade.js
=> fix brigade.js for dep

Makefile
fix https://github.com/Azure/brigade/issues/113
=> fix(makefile): add CGO_ENABLED=0  for build-docker-bin

docs/topics/install.md
The example command had the boolean wrong.
=> Update rbac instructions

brig/README.md, docs/topics/developers.md
=> Update documents with Client-only build instructions

docs/topics/developers.md
Updating some paths to find from the base of the project
=> Update demo paths in docs

git-sidecar/rootfs/clone.sh
Initial fix for checking out pull requests.
Fixes: #111
=> fix(git-sidecar): fetch remote SHA before checkout

docs/intro/install.md
See https://github.com/Azure/brigade/blob/db6d0f4e51182d6865320fd523bfc1e24ff64d5a/chart/brigade/templates/_helpers.tpl#L19
=> fix reference to brigade-server-brigade-gw

Makefile, tests/cmd/generate.go, tests/tests_test.go
Add an integration build tag to simplify running go unit tests
=> ref(Makefile): add build tag to integration tests

brigade-worker/src/k8s.ts
=> fix(worker): wrong default image name.

charts/brigade-project/templates/secret.yaml
=> fix(chart): fix if-checks and add if wrappers to all optional values

brigade-worker/src/events.ts, brigade-worker/src/job.ts, brigade-worker/src/k8s.ts, brigade-worker/test/k8s.ts, charts/brigade-project/templates/secret.yaml, charts/brigade-project/values.yaml, docs/topics/scripting.md
...but disable this feature by default as it poses a security risk. This is configurable through the project's configuration.
NOTE: first time doing a major contribution, so I might've broke something. Will take a look at how I can properly test this locally.
=> allow host-mounted docker sockets in jobs

brig/cmd/brig/commands/run.go
This makes Brig much smarter about waiting for a pod to start before
querying the log. It watches the pod stream for the build to go into
Running or Succeeded state. Then it goes on to the logs.
Closes #162
=> fix(brig): wait for pod to start

brigade-api/cmd/brigade-api/main.go, brigade-controller/cmd/brigade-controller/main.go, brigade-gateway/cmd/brigade-gateway/server.go
Set sane defaults so binaries do not error when running without any
flags set.
=> ref(*): set flag defaults

pkg/storage/kube/build.go
This massively improves the performance of requests that fetch
lists of build data. It pre-fetches both secrets and pods for the
build data.
=> fix(api): improve performance of fetching builds

brigade-api/cmd/brigade-api/main.go, brigade-gateway/cmd/brigade-gateway/server.go, charts/brigade/templates/gateway-deployment.yaml, charts/brigade/values.yaml, pkg/webhook/github.go, pkg/webhook/github_test.go
Makes building pull requests from forked repos optional.  Disabled by
default.
=> feat(gateway): make forked pull-request builds optional

pkg/webhook/github.go
=> fix: delete the dead link in the Github status payload

brigade-worker/src/job.ts, brigade-worker/test/job.ts, docs/topics/javascript.md
This validates job name much earlier.
Closes #176
=> fix(worker): add regexp to validate job name

pkg/webhook/github.go
Remove dead code and possible race condition.
=> fix(webhook): do not set ssh key in environment

docs/topics/javascript.md
=> docs(javascript): document the JS api for enabling docker socket

brigade-api/Dockerfile, brigade-controller/Dockerfile, brigade-cr-gateway/Dockerfile, brigade-gateway/Dockerfile, git-sidecar/Dockerfile
=> fix(*): use alpine:3.7

charts/brigade/templates/gateway-cr-service.yaml
=> fix the fix for gateway selectors

docs/intro/install.md
=> Spelling mistake

README.md
I guess actually hitting "Create pull request" would help.
cc: @squillace
=> docs(readme) Add link to Kashti.

pkg/webhook/github.go, pkg/webhook/github_test.go
Fixes a possible security issue if repo has automated labeling.  For
example a CLA bot.
/cc @technosophos
=> fix(gateway): enforce build policy for forks

brigade-worker/package.json, brigade-worker/prestart.js, brigade-worker/src/app.ts, brigade-worker/src/brigadier.ts, brigade-worker/src/events.ts, brigade-worker/src/group.ts, brigade-worker/src/index.ts, brigade-worker/src/job.ts, brigade-worker/src/k8s.ts, brigade-worker/src/require.ts, brigade-worker/tsconfig.json, brigade-worker/yarn.lock
- add formatter for consistent ts code
- prevent tests from compiling into ./dist
=> chore(build-tools): add ts formatter and refactor build setup

brigade-worker/package.json, brigade-worker/src/app.ts, brigade-worker/src/brigadier.ts, brigade-worker/src/index.ts, brigade-worker/src/job.ts, brigade-worker/src/k8s.ts, brigade-worker/src/require.ts, brigade-worker/yarn.lock
Add verbose error logging and fix errors not being throw.
=> feat(worker): add verbose error logging

README.md
I figure everyone else who gets as far as the github repo is going to want to click through to see Kashti screenshots too.
Doubt it's worth me signing a CLA for this one character fix, so please close + fix separately if required by your process.
=> Fix markdown for Kashti link

charts/brigade-project/values.yaml
The secrets are contained in the second argument (project), not the first (brigade_event).
=> Correct brigade_project#values.yml secrets

brigade-worker/src/k8s.ts, brigade-worker/test/k8s.ts
=> fix(worker): make cache name downcased

docs/topics/examples/simple-event/cron/Dockerfile, docs/topics/examples/simple-event/cron/cron-event.sh, docs/topics/examples/simple-event/cron/cron.yaml, docs/topics/examples/simple-event/simple-event.sh, docs/topics/gateways.md, docs/topics/index.md, scripts/functional-test-secret.sh
=> docs(gateways): add doc on creating Brigade gateways

brig/cmd/brig/commands/run.go
This allows you to specify a commit/branch/tag from the Brig
commandline.
=> feat(brig): add -c/--commit flag to brig run

brigade-worker/src/k8s.ts, brigade-worker/test/k8s.ts
=> fix(worker): fix the PVC name requested by the job

git-sidecar/.dockerignore, git-sidecar/rootfs/clone.sh, git-sidecar/test/test.sh
Lookup revision in remote repository to get SHA
fixes #228
=> fix(git-sidecar): support branch names and tags

docs/topics/developers.md
Additional commentary to help with #254
=> docs(brig): note to checkout a stable tag

brigade-vacuum/cmd/brigade-vacuum/commands/app.go, charts/brigade/templates/vacuum-cronjob.yaml
This fixes the logic for reading kubernetes config data in-cluster.
Closes #266
=> fix(vacuum): read the correct kube config

docs/intro/tutorial04.md
Fixed Python 3 compatibility in app_tests.py and test-runner job paths per previous documentation
=> Docs: Fixed compatibility to Python 3

charts/brigade/templates/api-deployment.yaml, charts/brigade/values.yaml
=> feat(chart): Configurable liveness/readiness probes for api

brigade-worker/src/app.ts, brigade-worker/src/events.ts, brigade-worker/src/k8s.ts, brigade-worker/test/k8s.ts, brigade-worker/test/mock.ts, charts/brigade-project/templates/secret.yaml, charts/brigade-project/values.yaml, docs/topics/javascript.md, docs/topics/projects.md, docs/topics/scripting.md, docs/topics/values.md, git-sidecar/rootfs/clone.sh, pkg/brigade/project.go, pkg/storage/kube/project.go, pkg/webhook/dockerhub_test.go
The Build Shared Storage Space is now user configurable through the brigade project file. The default value is 50Mi
Resolves: https://github.com/Azure/brigade/issues/220
=> Configurable Build Storage ; Initialize Submodules

brigade-worker/src/events.ts, brigade-worker/src/k8s.ts, brigade-worker/test/k8s.ts, charts/brigade-project/templates/secret.yaml, charts/brigade-project/values.yaml
=> feat(worker): make storage class for cache and build configurable

charts/brigade/templates/api-deployment.yaml
thanks to @brandon-bethke-neudesic for the [good catch](https://github.com/mumoshu/brigade/commit/3895928893cabcb6588784d371ba5b63a73b66ef#commitcomment-27134568)
=> Fix typo in one of brigade chart templates

charts/brigade/templates/_helpers.tpl, charts/brigade/templates/vacuum-cronjob.yaml, charts/brigade/templates/vacuum-role.yaml
This adds a service account, role, and role binding for vacuum.
=> fix(chart): add rbac for vacuum

brigade-controller/cmd/brigade-controller/controller/informer.go
The refactor caused unit-tests to panic.
=> fix(tests): revert list watcher changes

charts/brigade-project/templates/secret.yaml, charts/brigade-project/values.yaml, pkg/brigade/project.go, pkg/storage/kube/project.go, pkg/storage/kube/project_test.go, pkg/webhook/dockerhub.go, pkg/webhook/dockerhub_test.go, pkg/webhook/github.go, pkg/webhook/github_test.go
=> feat(gateway): add support for default brigade script

charts/brigade/templates/api-ingress.yaml, charts/brigade/values.yaml
=> added ingress for api service

docs/topics/gateways.md
=> Fix small typo

charts/brigade-project/templates/secret.yaml
Fix a syntax bug introduced in a recent change.
=> fix(chart): fix broken for loop in brigade-project chart.

docs/topics/developers.md, docs/topics/install.md
This updates the installation docs to (a) make the install docs more
reliable, and (b) make the developer docs clearer.
=> docs(install,developer): update installation info

brigade-worker/src/k8s.ts
This causes the worker to fail if a Job's image cannot be fetched by
Kubernetes.
Closes #193
=> fix(worker): die on non-existent job image

charts/brigade/templates/vacuum-role.yaml, charts/brigade/templates/worker-role.yaml
=> charts/brigade: fix RBAC for use with admin cluster role

Makefile
- remove unused dependencies from bootstrap
- automagically vendor when missing
=> chore(Makefile): remove unused dependencies from bootstrap

README.md
Add build status badge.
This just points to a very simple badge service that polls the GitHub status.
=> docs(README): add build status image

charts/brigade/templates/api-role.yaml, charts/brigade/templates/gateway-cr-role.yaml, charts/brigade/templates/gateway-cr-service.yaml, charts/brigade/templates/gateway-github-role.yaml
Fixes #336 
**NOTE** I noticed that RBAC resources are created for each service  too, even when the service is disabled as well. I could add a check for that to this PR quickly if needed.
=> Only create service & RBAC for components when enabled

brigade-worker/src/k8s.ts, brigade-worker/test/k8s.ts, docs/topics/examples/simple-event/cron/cron-event.sh, docs/topics/examples/simple-event/simple-event.sh, docs/topics/gateways.md, pkg/storage/kube/build.go, pkg/storage/kube/build_test.go, scripts/functional-test-secret.sh
This is unused and can be confusing.
=> ref(*): remove label for commit_id

docs/topics/examples/workers/Dockerfile, docs/topics/examples/workers/brigade.js, docs/topics/examples/workers/mylib.js, docs/topics/workers.md
This adds documentation explaining how to write and use custom worker
images with custom JavaScript libraries.
=> docs(topics): Add document on customizing workers

Gopkg.lock, brig/cmd/brig/commands/run.go
=> fix(brig): Error fast if the project does not exist

Makefile, brig/cmd/brig/commands/build_get.go, brig/cmd/brig/commands/build_list.go, brig/cmd/brig/commands/project_get.go, brig/cmd/brig/commands/project_list.go, brig/cmd/brig/commands/proxy.go, brigade-cr-gateway/cmd/brigade-cr-gateway/server.go, brigade-github-gateway/cmd/brigade-github-gateway/server.go, brigade-worker/src/k8s.ts, gometalinter.json, pkg/brigade/worker_config.go, pkg/storage/kube/store.go, pkg/webhook/dockerhub.go, pkg/webhook/dockerhub_test.go, pkg/webhook/github.go, pkg/webhook/github_test.go
Refactor lint and format targets and fix issues.
=> chore(Makefile): refactor lint and format

brigade.js
The script needed an update on the commit ID.
=> fix(brigade.js): update to use event.revision.commit

brigade-worker/src/job.ts, brigade-worker/src/k8s.ts, brigade-worker/test/job.ts, brigade-worker/test/k8s.ts
This adds label-based node selectors to jobs.
Closes #325
=> feat(worker): Allow jobs to pin to particular nodes by label

README.md
Adds Related Project links to the readme for:
* [Kashti](https://github.com/Azure/kashti)
* [Brigadeterm](https://github.com/slok/brigadeterm)
=> Update README with related projects (kashti, brigadeterm)

.gitignore, pkg/webhook/github.go
=> Add 'closed' as pull_request event

brigade.js
This fixes the brig build/upload and adds a new event handler for
'brig-release'.
=> fix(brigade.js): fix the brig build

pkg/brigade/build.go
=> fix(api): prevent omitted api fields

charts/brigade/templates/gateway-cr-service.yaml
Simple update for standard property names
[403](https://github.com/Azure/brigade/issues/403)
=> consistent gateway service namespace for properties

README.md
Adds:
- BitBucket gateway
- Trello gateway
- k8s gateway
=> docs(README): added a few other gateways

docs/topics/scripting.md
Just added a missing parenthesis
=> Minor fix to script example

pkg/api/build.go
(My guess is a copy/paste gone awry)
=> Fix code comment in api/build.go

brigade.js
This adds a new target that builds and releases to a Docker registry.
Wait to merge until after #409
=>  feat(brigade.js): build docker images on tag event.

brig/cmd/brig/commands/app.go, brig/cmd/brig/commands/run.go, pkg/decolorizer/writer.go, pkg/decolorizer/writer_test.go
=> feat(brig): Added decolorizer and --no-color for brig run

git-sidecar/rootfs/clone.sh, pkg/webhook/github.go, pkg/webhook/github_test.go
=> fix(git-sidecar): when commit-ref is missing, use commit-id

docs/topics/javascript.md
Looks like this didn't get added with #425
=> Add Job Annotations to Documentation

brigade.js
Fixes #460 
@technosophos can you test this out?
=> Remove az extension add for ACR build

brigade.js
=> fix(brig): add exe extension to Windows binary

brigade-controller/cmd/brigade-controller/controller/controller_test.go, brigade-controller/cmd/brigade-controller/controller/handler.go
=> fix(controller): add an accepted label to builds after sync

Gopkg.lock, Gopkg.toml, brig/cmd/brig/commands/project_delete.go, pkg/storage/kube/project.go, pkg/storage/kube/project_test.go, pkg/storage/mock/storage.go, pkg/storage/mock/storage_test.go, pkg/storage/storage.go
This adds a command to delete a project.
=> feat(brig): add brig project delete

pkg/storage/kube/apicache/secrets.go
This adds a sort by CreationTimestamp for #511
=> api(sorting): builds/jobs sort order

brig/cmd/brig/commands/run.go
The -b flag lets 'brig run' submit an event and then exit, leaving the
event to run "in the background".
Closes #530
=> feat(brig): add -b/--background flag to brig run

Gopkg.lock, brig/cmd/brig/commands/build_list.go, brigade.js
This adds the AGE header with fuzzy durations to the `brig build list`
command.
=> feat(brig): Add AGE to brig build list

docs/topics/scripting.md
This explains how tasks are executed in a shell, and how to set a custom
shell for a Job.
Closes #476
=> docs(scripting): explain how tasks work in a shell

brig/cmd/brig/commands/build_list.go
=> fix(brig): fix stack trace on build list

brigade-api/cmd/brigade-api/main.go
this feature flag enables more verbose logging of incoming http requests to the brigade API.
=> add --verbose flag

brigade-worker/package.json, brigade-worker/src/job.ts, brigade-worker/src/k8s.ts, brigade-worker/yarn.lock
=> use watch in worker for efficiency #592

brigade-controller/cmd/brigade-controller/controller/controller_test.go, brigade-controller/cmd/brigade-controller/controller/handler.go, brigade-worker/prestart.js, charts/brigade-project/values.yaml
=> fix(*): add project default script to worker

brig/cmd/brig/commands/run.go
(parity with docker and kubectl)
=> fix: add brig exec as alias for brig run

brigade-worker/prestart.js
closes #627
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>
=> add missing comma

docs/topics/developers.md
This should fix the broken code block in https://azure.github.io/brigade/topics/developers.html:
=> fix(doc): broken code block in the topics/developers doc

charts/brigade-project/values.yaml
=> fix(chart/project): do not override default in values.yaml

brigade-worker/src/k8s.ts
feat(worker): handle transient faults (#625)
fix(worker): handle JSON.parse exception caused by transient faults in
watch
feat(worker): support KUBECONFIG (feedback from #596)
=> fix(worker): handle transient faults (#625)

docs/intro/tutorial01.md, docs/intro/tutorial04.md
* Add Python 3 note
* rm redundant `git add .`
* adjust test function name
* e.commit -> e.revision.commit
=> docs(tutorial): misc fixes

docs/topics/scripting_advanced.md
Fix `brig run` file flag. I believe `-e` flag is for providing event name
=> Fix brig run file flag

docs/intro/tutorial04.md, docs/topics/javascript.md
=> fix(docs): add correct key for commit sha value

charts/brigade/templates/api-deployment.yaml, charts/brigade/templates/api-ingress.yaml, charts/brigade/templates/api-role.yaml, charts/brigade/templates/api-service.yaml, charts/brigade/templates/controller-deployment.yaml, charts/brigade/templates/controller-role.yaml, charts/brigade/templates/gateway-cr-deployment.yaml, charts/brigade/templates/gateway-cr-role.yaml, charts/brigade/templates/gateway-cr-service.yaml, charts/brigade/templates/gateway-github-deployment.yaml, charts/brigade/templates/gateway-github-role.yaml, charts/brigade/templates/gateway-github-service.yaml, charts/brigade/templates/ingress.yaml, charts/brigade/templates/vacuum-cronjob.yaml, charts/brigade/templates/vacuum-role.yaml, charts/brigade/templates/worker-role.yaml
I've updated all chart labels according to the new convention specified here: https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md.
=> Update chart labels to follow the new convention

charts/brigade/templates/controller-deployment.yaml, charts/brigade/templates/controller-role.yaml, charts/brigade/values.yaml
Related to #662 
It adds an option to disable controller. By default, controller is enabled.
Please let me know your thoughts on this.
=> feat(chart/controller): add enabled option for controller (enabled by default)

brigade-controller/cmd/brigade-controller/controller/controller.go, brigade-controller/cmd/brigade-controller/controller/controller_test.go, brigade-controller/cmd/brigade-controller/controller/handler.go, brigade-controller/cmd/brigade-controller/controller/handler_test.go, brigade-controller/cmd/brigade-controller/main.go, brigade-worker/src/events.ts, brigade-worker/src/k8s.ts, brigade-worker/test/k8s.ts, charts/brigade-project/Chart.yaml, charts/brigade-project/templates/secret.yaml, charts/brigade-project/values.yaml, charts/brigade/Chart.yaml, charts/brigade/templates/controller-deployment.yaml, charts/brigade/values.yaml
Implements #701 
Adds flags for the controller to set the worker container resources.
Adds project configuration to set the init-container vcs-sidecar resources.
=> Add resources to worker and jobs

charts/brigade/values.yaml, docs/topics/install.md, docs/topics/security.md
Implements https://github.com/Azure/brigade/issues/713
=> ref(charts): enable RBAC by default

git-sidecar/rootfs/clone.sh
Fix for #668 
Stole some code from [here](https://unix.stackexchange.com/a/137639), modified arithmetic expressions to work with Bourne shell
=> added retry logic to sidecar

docs/intro/tutorial04.md
=> Remove confusing green checkmark from getting started doc

README.md
=> Add a support & feedback section to the readme

brig/cmd/brig/commands/app.go
This PR adds the ability to set a default Brigade namespace for `brig` through the BRIGADE_NAMESPACE environment variable. 
If passed, the `--namespace` flag takes precedence over the environment variable.
closes #741
=> brig: Add default namespace 

README.md
=> Add link to Azure DevOps / VSTS gateway

Makefile, brigade-worker/package.json, brigade-worker/test/mock.ts, brigade-worker/yarn.lock
=> Update TypeScript to 3.2.2 and add build target in CI

brig/cmd/brig/commands/project_create.go, brigade-controller/cmd/brigade-controller/controller/handler.go, docs/topics/projects.md, pkg/brigade/project.go, pkg/storage/kube/project.go
Provides an option during `brig project create` to specify a custom Brigade.js location
Closes #765
=> added option to specify brigade.js path on project creation

README.md, docs/index.md
'Modernized' Brigade quickstart. Closes #595, partially #748  
For easy viewing, check here: https://github.com/dgkanatsios/brigade/blob/quickstart/README.md#quickstart
=> quickstart enhancement

Gopkg.lock, Gopkg.toml, brig/cmd/brig/commands/main_test.go
* add version constraints to Gopkg.toml
* fix ENV pollution in unit tests
=> fix(deps): add version constraints to Gopkg.toml

docs/topics/design.md, docs/topics/developers.md, docs/topics/dockerhub.md, docs/topics/gateways.md, docs/topics/github.md, docs/topics/index.md, docs/topics/javascript.md, docs/topics/projects.md, docs/topics/scripting.md, docs/topics/scripting_advanced.md, docs/topics/secrets.md, docs/topics/security.md, docs/topics/storage.md, docs/topics/workers.md
Contributes to implementation/closing out of https://github.com/Azure/brigade/issues/747
=> docs(topics): add navigation links

docs/topics/index.md, docs/topics/javascript.md, docs/topics/testing.md
Adds Brigade testing examples per https://github.com/Azure/brigade/issues/451
=> docs(topics): add testing doc

brigade-worker/src/index.ts
=> fix regex matching on the service account

README.md
Addresses #799 
Not closing, as we should create a new one.
(The rest of the changes are empty spaces at the end of lines -- `    "files.trimTrailingWhitespace": true` is doing its job well)
=> Temporarily comment the ASCII Cinema URL as it is archived

docs/content/intro/_index.md, docs/content/topics/_index.md, docs/content/topics/projects.md
=> [docs] fix internal doc links on index pages

CODEOWNERS
This adds @lukepatrick as a core maintainer! (Luke was elected to this position earlier this week)
=> docs: add lukepatrick as a code owner

docs/content/intro/install.md, docs/content/intro/overview.md, docs/content/intro/readnext.md, docs/content/intro/tutorial01.md, docs/content/intro/tutorial02.md, docs/content/intro/tutorial03.md, docs/content/intro/tutorial04.md, docs/content/intro/writing-efficient-pipelines.md, docs/content/topics/design.md, docs/content/topics/developers.md, docs/content/topics/dockerhub.md, docs/content/topics/gateways.md, docs/content/topics/genericgateway.md, docs/content/topics/github.md, docs/content/topics/javascript.md, docs/content/topics/projects.md, docs/content/topics/scripting.md, docs/content/topics/scripting_advanced.md, docs/content/topics/secrets.md, docs/content/topics/security.md, docs/content/topics/storage.md, docs/content/topics/workers.md
Fixes #827
As per #827, this PR removes the custom navigation from docs since this will be added automatically via the work being done in #814
=> removing custom navigation from docs (#827)

brigade-worker/package.json
=> Update package.json version for Brigade worker

brigade.js
As part of the migration of Brigade to this brigadcore CNCF org, I propose we remove publishing of Docker images to ACR (which is managed on an internal Microsoft subscription). 
Images would therefore solely be published to the [brigadecore DockerHub org](https://hub.docker.com/u/brigadecore), which aligns with all of the registry/image defaults in documentation and [charts](https://github.com/brigadecore/charts).
=> ref(brigade.js): remove acr publishing

CONTRIBUTING.md, README.md
Ref https://github.com/brigadecore/brigade/issues/853
=> docs(CONTRIBUTING.md): add contributing doc; link from README

README.md, docs/content/topics/developers.md, docs/content/topics/projects.md, docs/content/topics/releasing.md
Updates release strings in anticipation of the v1.0.0 release.
=> docs(*): bump version in docs to latest v1.0.0 release

docs/config.toml, docs/themes/techdoc-brigade/layouts/partials/menu.html, docs/themes/techdoc-brigade/layouts/partials/sidebar.html
Replaces the current menu, which auto-sorts content alphabetically with a custom one. 
This allows us to re-order the content to our own preference.
---
Related to discussion in #851 (but not a blocker for that PR).
Closes issue #859.
=> [docs] adds custom menu for docs

docs/content/intro/tutorial01.md
Missing `[` in image link in tutorial
♥ 
PS: sorry about the (whitespace?) change at the last line; GitHub online editor did that somehow?
=> Missing [ in image link

docs/config.toml, docs/content/contributing.md
Addresses [brigadecore/brigade-www](https://github.com/brigadecore/brigade-www/issues/11) issue #11.
=> copy contributing info into docs/content and add nav link

README.md
Addresses #862 
This is a WIP badge for CII.
=> Add In-Progress CII badge

code-of-conduct.md
=> Add CNCF Community Code of Conduct

docs/content/topics/ingress.md
=> docs(ingress.md): fix manifest indent

brig/cmd/brig/commands/project_create.go, brigade-controller/cmd/brigade-controller/controller/controller.go, brigade-controller/cmd/brigade-controller/controller/handler.go, brigade-controller/cmd/brigade-controller/main.go, pkg/brigade/project.go
=> make worker command configurable globally with a controller flag

brigade-controller/cmd/brigade-controller/controller/controller.go, brigade-controller/cmd/brigade-controller/controller/controller_test.go, brigade-controller/cmd/brigade-controller/controller/handler.go, brigade-controller/cmd/brigade-controller/main.go, brigade-worker/src/index.ts, brigade-worker/src/k8s.ts, brigade-worker/test/k8s.ts
=> allow global configuration of default storage classes

brigade.js
=> make runSuite() fail build when any job fails

brigade-worker/node_modules/progress/README.md, brigade-worker/src/k8s.ts, node_modules/.yarn-integrity
tiny PR that correlates with this -> https://github.com/brigadecore/brigadier/pull/15
It emphasizes that Job timeout is in milliseconds
=> emphasizing that job timeout is in milliseconds

brigade.js
Updates this project's Brigade pipeline with handling for Issue Comment events, as well as individual (re-)requested Check Runs
Closes https://github.com/brigadecore/brigade/issues/926
=> feat(brigade.js): add handlers for issue_comment and check_run:rerequested events

brigade.js, brigade.json
The goal of https://github.com/brigadecore/brigade-utils is to encapsulate frequently used jobs into a reusable library, and the GitHub logic for handling the Checks API is part of it.
This PR updates `brigade.js` to use the library.
=> Initial test with the GitHub library from brigade-utils

docs/content/topics/workers.md
Fiexes #886 
Note to reviewers-- probably don't try to look at the diffs here; rather look at the revised page as a whole.
=> more thorough custom worker documentation

brig/cmd/brig/commands/project_create.go
=> project_create.go： help message word correction

brigade-controller/cmd/brigade-controller/controller/handler.go, brigade-vacuum/cmd/brigade-vacuum/commands/app.go, pkg/storage/kube/project.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> Cleanup: fix some typos in code comment

brigade-api/cmd/brigade-api/main.go, brigade-worker/package.json, docs/content/intro/quickstart.md, docs/content/topics/developers.md, docs/content/topics/releasing.md, docs/content/topics/workers.md
Doc and version updates per the [1.2.1](https://github.com/brigadecore/brigade/milestone/3) release.
=> chore(*): updates per v1.2.1 release

brig/cmd/brig/commands/build_get.go, brig/cmd/brig/commands/build_list.go, brig/cmd/brig/commands/build_list_test.go, brig/cmd/brig/commands/project_get.go, brig/cmd/brig/commands/project_list.go
closes #993
```
$ brig build list --output json
[
{
"id": "01dqxcgfdjeffj97rm2sqqck72",
"project_id": "brigade-b9f6da279ec59af95d121d1e1e502ecf056504e267f2f7dfc747eb",
"type": "exec",
"provider": "brigade-cli",
"clone_url": "",
"revision": {
"commit": "",
"ref": "master"
},
"payload": "",
"script": "Y29uc3QgeyBldmVudHMsIEpvYiB9ID0gcmVxdWlyZSgiQGJyaWdhZGVjb3JlL2JyaWdhZGllciIpOwoKZXZlbnRzLm9uKCJleGVjIiwgKCkgPT4gewogICAgdmFyIGpvYiA9IG5ldyBKb2IoImRvLW5vdGhpbmciLCAiYWxwaW5lIik7CiAgICBqb2IudGFza3MgPSBbCiAgICAgICAgImVjaG8gSGVsbG8iLAogICAgICAgICJlY2hvIFdvcmxkIgogICAgXTsKCiAgICBqb2IucnVuKCk7Cn0pOwoKZXZlbnRzLm9uKCJjdXN0b20tZXZlbnQiLCAoKSA9PiB7CiAgICB2YXIgam9iID0gbmV3IEpvYigiY3VzdG9tLWpvYi1oYW5kbGVyIiwgImFscGluZSIpOwogICAgam9iLnRhc2tzID0gW2BlY2hvICJJIGFtIGRvaW5nIHZlcnkgaW1wb3J0YW50IHdvcmsiYF07CgogICA …
```
=> Add JSON output for brig X get and list commands

brigade-generic-gateway/README.md
This is a simple fix to link to the gateway documentation.
=> Fix link to gateway documentation

brigade.js
Fixes https://github.com/brigadecore/brigade/issues/1003
N/A
=> fix(brigade.js): supply details URL to new Check(..)

README.md
Updates the build badge URL.
Closes https://github.com/brigadecore/brigade/issues/877
=> fix(README.md): update build badge URL

docs/content/topics/scripting_advanced.md
Document using Docker-in-Docker
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>
=> document docker-in-docker

brig/cmd/brig/commands/build_list_test.go, brig/cmd/brig/commands/rerun.go, brig/cmd/brig/commands/rerun_test.go, brig/cmd/brig/commands/run.go, brigade-worker/prestart.js, brigade-worker/test/prestart.ts, docs/content/topics/brig.md, docs/content/topics/dependencies.md, docs/content/topics/workers.md, pkg/brigade/build.go, pkg/script/delegated_runner.go, pkg/storage/kube/build.go
Enables passing a local `brigade.json` file to  a `brig run` command, overriding the version found in the project repo, if exists.
Closes https://github.com/brigadecore/brigade/issues/928
=> feat(*): enable passing brigade.json via brig run

docs/content/topics/ingress.md
Updates the cert-manager install instructions in the ingress doc.
=> docs(ingress.md): update cert-manager install instructions/manifests

brig/cmd/brig/commands/check.go, brig/cmd/brig/commands/check_test.go
Signed-off-by: Anthony Foster <AnthonyFoster85@gmail.com>
Closes #916 
This is a nice to have item, requested in #916, to have a nicer UI around checking brig status
I'm very green with Go, K8s, and Brigade. Please double check my logic around what are successful and error statuses.
=> Added emoji's on brig check, unit tests

brigade-worker/package.json
Fixes `yarn audit` for brigade-worker
=> chore(brigade-worker): fix yarn audit

brigade-worker/Dockerfile
=> docker node upgrade

brig/cmd/brig/commands/run.go
Closes #774 - supports adding an inline payload for events in brig run
NA
=> feat(brig): accept inline payload in brig run

docs/content/topics/javascript.md
Adds the nodeSelector functionality of `JobHost` class in the
documentation. Gives an example of how you could set it.
Ideally I believe we should add similar info to `scripting.md` but I need your opinion before I do this.
=> Resolves #1105.

draft.toml
This project has been archived.
=> remove draft.toml

charts/brigade/templates/apiserver/cluster-role.yaml, v2/apiserver/internal/authx/mongodb/users_store.go, v2/apiserver/internal/core/kubernetes/secrets_store.go, v2/apiserver/internal/core/kubernetes/secrets_store_test.go, v2/apiserver/internal/core/kubernetes/substrate_test.go, v2/apiserver/internal/core/mongodb/projects_store.go, v2/apiserver/internal/core/rest/secrets_endpoints.go, v2/apiserver/internal/core/secrets.go, v2/apiserver/main.go, v2/apiserver/schemas/secret.json, v2/cli/flags.go, v2/cli/project_commands.go, v2/cli/secrets_commands.go
=> secret management features

sdk/v2/internal/restmachinery/client.go
=> make SDK's API client set HTTP Accept header

v2/apiserver/internal/authx/mongodb/common.go, v2/apiserver/internal/authx/mongodb/sessions_store.go, v2/apiserver/internal/authx/mongodb/users_store.go, v2/apiserver/internal/core/mongodb/common.go, v2/apiserver/internal/core/mongodb/events_store.go, v2/apiserver/internal/core/mongodb/projects_store.go, v2/apiserver/main.go
=> add indices to mongodb collections where needed

v2/apiserver/internal/core/common_test.go, v2/apiserver/internal/core/events.go, v2/apiserver/internal/core/events_test.go, v2/apiserver/internal/core/kubernetes/substrate.go, v2/apiserver/internal/core/kubernetes/substrate_test.go, v2/apiserver/internal/core/substrate.go, v2/apiserver/main.go, v2/internal/kubernetes/common.go
This builds on top of #1152, which must be merged first.
=> on event creation, use queue to schedule worker execution

sdk/v2/core/jobs.go, sdk/v2/core/workers.go, v2/apiserver/internal/core/jobs.go, v2/apiserver/internal/core/workers.go, v2/internal/os/os.go, v2/internal/os/os_test.go, v2/internal/retries/retries.go, v2/scheduler/internal/lib/queue/amqp/reader.go, v2/scheduler/internal/lib/queue/amqp/reader_test.go
This PR contains a variety of small fixes and features, some of which a larger, forthcoming PR will be dependent upon.
This is an attempt to keep PRs more manageable.
=> Small fixes

charts/brigade/templates/apiserver/deployment.yaml, charts/brigade/values.yaml, v2/apiserver/config.go, v2/apiserver/config_test.go, v2/apiserver/internal/core/common_test.go, v2/apiserver/internal/core/jobs.go, v2/apiserver/internal/core/jobs_test.go, v2/apiserver/internal/core/kubernetes/substrate.go, v2/apiserver/internal/core/kubernetes/substrate_test.go, v2/apiserver/internal/core/rest/jobs_endpoints.go, v2/apiserver/internal/core/rest/workers_endpoints.go, v2/apiserver/internal/core/substrate.go, v2/apiserver/internal/core/workers.go, v2/apiserver/internal/core/workers_test.go, v2/apiserver/main.go, v2/internal/kubernetes/common.go
Another PR that provides a fragment of scheduler functionality to avoid a much larger PR. This PR provides the API server endpoints and implementations for starting a worker or job (when requested to do so by the scheduler-- which comes in the next PR).
Note to reviewer: Don't be scurred. Most of the code is just test cases.
=> api additions needed by scheduler

v2/apiserver/internal/lib/restmachinery/server.go, v2/go.mod, v2/go.sum
Students at BYU are working on code that invokes the API from within a browser and alerted me to the fact that CORS wasn't currently supported by our API server.
This PR adds support for CORS using a popular library.
=> add support for CORS

Makefile, brigade.js, charts/brigade/templates/_helpers.tpl, charts/brigade/templates/apiserver/deployment.yaml, charts/brigade/templates/observer/cluster-role-binding.yaml, charts/brigade/templates/observer/cluster-role.yaml, charts/brigade/templates/observer/deployment.yaml, charts/brigade/templates/observer/secret.yaml, charts/brigade/templates/observer/service-account.yaml, charts/brigade/values.yaml, v2/apiserver/config.go, v2/apiserver/config_test.go, v2/apiserver/internal/authx/principals.go, v2/apiserver/internal/core/kubernetes/substrate.go, v2/apiserver/internal/lib/restmachinery/authn/token_auth.go, v2/apiserver/internal/lib/restmachinery/authn/token_auth_test.go, v2/go.sum, v2/internal/kubernetes/common.go, v2/observer/Dockerfile, v2/observer/common.go, v2/observer/common_test.go, v2/observer/config.go, v2/observer/config_test.go, v2/observer/jobs.go, v2/observer/jobs_test.go, v2/observer/main.go, v2/observer/observer.go, v2/observer/observer_test.go, v2/observer/workers.go, v2/observer/workers_test.go
This component watches worker and job pods in Kubernetes and reports their status via the Brigade API.
=> add observer component

Makefile
Looks like this was a merge issue.
=> remove errant line from Makefile

sdk/v2/core/jobs.go, sdk/v2/core/workers.go, v2/apiserver/internal/core/jobs.go, v2/apiserver/internal/core/jobs_test.go, v2/apiserver/internal/core/mongodb/events_store.go, v2/apiserver/internal/core/workers.go, v2/apiserver/internal/core/workers_test.go, v2/apiserver/schemas/job-status.json, v2/apiserver/schemas/worker-status.json, v2/cli/event_commands.go, v2/cli/flags.go
=> add support for new worker/job STARTING phase

Makefile, charts/brigade/values.yaml
=> incorporate major version into image/repo name

v2/apiserver/internal/authx/principals.go, v2/apiserver/internal/core/common_test.go, v2/apiserver/internal/core/events.go, v2/apiserver/internal/core/events_test.go, v2/apiserver/internal/core/jobs.go, v2/apiserver/internal/core/jobs_test.go, v2/apiserver/internal/core/kubernetes/substrate.go, v2/apiserver/internal/core/kubernetes/substrate_test.go, v2/apiserver/internal/core/mongodb/events_store.go, v2/apiserver/internal/core/mongodb/events_store_test.go, v2/apiserver/internal/core/mongodb/jobs_store.go, v2/apiserver/internal/core/mongodb/jobs_store_test.go, v2/apiserver/internal/core/rest/jobs_endpoints.go, v2/apiserver/internal/core/rest/workers_endpoints.go, v2/apiserver/internal/core/substrate.go, v2/apiserver/internal/core/workers.go, v2/apiserver/internal/core/workers_test.go, v2/apiserver/internal/lib/restmachinery/authn/token_auth.go, v2/apiserver/internal/lib/restmachinery/authn/token_auth_test.go, v2/apiserver/main.go, v2/apiserver/schemas/job.json
This PR adds endpoints that the workers will use for creating jobs.
The worker code itself is not included in this PR. That will be PR'ed shortly.
=> worker api changes

Makefile, brigade.js, v2/apiserver/Dockerfile, v2/observer/Dockerfile, v2/scheduler/Dockerfile
=> use new, official dev images

v2/apiserver/internal/core/common_test.go, v2/apiserver/internal/core/jobs.go, v2/apiserver/internal/core/jobs_test.go, v2/apiserver/internal/core/kubernetes/substrate.go, v2/apiserver/internal/core/kubernetes/substrate_test.go, v2/apiserver/internal/core/substrate.go
=> secure job environment storage

v2/tests/git_initializer_test.go
Updates the auth pkg name in the git initializer int tests
=> fix(git_initializer_test.go): s/authx/authn

v2/apiserver/internal/authz/mock_roles_assignments_store.go, v2/apiserver/internal/authz/mongodb/role_assignments_store.go, v2/apiserver/internal/authz/mongodb/role_assignments_store_test.go, v2/apiserver/internal/authz/role_assignments.go, v2/apiserver/internal/core/projects.go, v2/apiserver/internal/core/projects_test.go
=> on project delete, revoke all associated role assignments

docs/content/intro/install.md
**What this PR does / why we need it**: Updates the installation command in the Intro documentation to Helm 3, because Helm 3 is the recommended version for people to use, and the syntaxes are different
**Special notes for your reviewer**: None
=> Update installation command to Helm 3

README.md
* Adds a note mentioning the v2.0.0-alpha.1 release and a link for getting started with Brigade 2.0
=> docs(README.md): add mention of the v2.0.0-alpha.1 release

v2/git-initializer/main.go
* Adds retry logic around pertinent git operations for feature parity with the v1 vcs sidecar
Closes https://github.com/brigadecore/brigade/issues/1235
The happy path here is tested via the usual `make test-integration` target.  Was hesitant to refactor tests to add in temporary git remote url "blackouts" to actually test the retries e2e.  Plus, the `retries` library itself has a nice suite of unit tests and our use is fairly vanilla.  Thoughts otherwise?
=> feat(git-initializer): add retries

sdk/README.md
* I was perusing the sdk directory in anticipation of working on a separate ticket and noticed that the README could use some updates.
=> docs(sdk/README.md): update to reflect current state

Makefile, brigade.js, brigade.json
* Adds the test-integration job to CI
* Shuffles around some make targets to facilitate
Ref associated PR bumping kind image/KindJob in https://github.com/brigadecore/brigade-utils/pull/51
=> feat(ci): add test-integration job

charts/brigade/templates/apiserver/deployment.yaml, charts/brigade/values.yaml, v2/apiserver/config.go, v2/apiserver/config_test.go, v2/apiserver/internal/authn/sessions.go
* Adds configurable root/user session TTL
Closes https://github.com/brigadecore/brigade/issues/1251
=> Configurable session TTL

examples/javascript/groups-demo.yaml, examples/typescript/groups-demo.yaml, sdk/v2/internal/restmachinery/client.go, v2/brigadier/src/events.ts, v2/brigadier/src/groups.ts, v2/brigadier/src/index.ts, v2/brigadier/src/jobs.ts, v2/brigadier/src/logger.ts, v2/brigadier/src/projects.ts, v2/brigadier/src/runnables.ts, v2/brigadier/src/workers.ts, v2/brigadier/test/groups.ts, v2/brigadier/test/index.ts, v2/worker/src/brigadier.ts, v2/worker/test/brigadier.ts
This is a possible alternative to what is proposed by #1290.
I'm not seeking to get this merged at this time.
This is to fuel discussion, particularly with @itowlson.
=> better groups in brigadier / worker + docs

Makefile, brigade.js, v2/worker/Dockerfile, v2/worker/src/prestart.ts
Fixes #1310.
Also bumps us to the latest Node version that has LTS.
=> npm support

sdk/v2/core/events_test.go
Fixes a flaky test that snuck in with #1324
=> fix flaky test

sdk/README.md
Help people find the go doc quickly and link it in a few places so they are more likely to ... read the docs.
hello world
=> Link to SDK godoc

sdk/v2/core/events.go, sdk/v2/core/events_test.go, v2/apiserver/internal/core/common_test.go, v2/apiserver/internal/core/events.go, v2/apiserver/internal/core/events_test.go, v2/apiserver/internal/core/rest/events_endpoints.go, v2/cli/event_commands.go
- Adds the `brig event clone` command per https://github.com/brigadecore/brigade/issues/1196
Closes https://github.com/brigadecore/brigade/issues/1196
=> feat(event_commands.go): add clone command

v2/apiserver/schemas/project-role-assignment.json, v2/apiserver/schemas/role-assignment.json
Fix schema bugs that snuck in with recent refactoring.
=> small schema fixes

sdk/v2/authn/sessions.go, sdk/v2/authn/sessions_test.go, v2/apiserver/internal/authn/rest/sessions_endpoints.go, v2/apiserver/internal/authn/sessions.go, v2/apiserver/internal/authn/sessions_test.go, v2/apiserver/internal/lib/restmachinery/endpoints.go, v2/cli/login_command.go
=> allow user-defined oidc success redirect

sdk/v2/authz/role_assignments.go, sdk/v2/authz/role_assignments_test.go, sdk/v2/core/project_role_assignments.go, sdk/v2/core/project_roles_assignments_test.go, sdk/v2/lib/authz/role_assignments.go, sdk/v2/lib/authz/role_assignments_test.go, v2/apiserver/internal/authz/mock_roles_assignments_store.go, v2/apiserver/internal/authz/mongodb/role_assignments_store.go, v2/apiserver/internal/authz/mongodb/role_assignments_store_test.go, v2/apiserver/internal/authz/rest/role_assignments_endpoints.go, v2/apiserver/internal/authz/role_assignments.go, v2/apiserver/internal/authz/role_assignments_test.go, v2/apiserver/internal/core/mongodb/project_role_assignments_store.go, v2/apiserver/internal/core/mongodb/project_role_assignments_store_test.go, v2/apiserver/internal/core/project_role_assignments.go, v2/apiserver/internal/core/project_role_assignments_test.go, v2/apiserver/internal/core/rest/project_role_assignments_endpoints.go, v2/apiserver/internal/lib/authz/role_assignments.go, v2/apiserver/internal/lib/authz/role_assignments_test.go, v2/apiserver/main.go, v2/cli/flags.go, v2/cli/project_role_commands.go, v2/cli/role_commands.go
Fixes #1257 
As usual, I've broken my PR into discrete commits for API changes and corresponding SDK changes and CLI changes. The easiest way to review might be to review each of those as a unit.
~~Built on top of #1369, which should be merged first.~~ Done.
=> implement list role assignments & list project role assignments

v2/cli/event_commands.go
=> reword event clone command help

v2/apiserver/internal/core/kubernetes/logs_store.go, v2/apiserver/internal/core/logs.go, v2/cli/event_commands.go, v2/cli/log_command.go
Fixes #1329 and (incidentally) #1371
=> add --follow flag to cli event create command

v2/cli/project_role_commands.go, v2/cli/role_commands.go
=> add role grant/revoke ack messages to cli

v2/worker/src/prestart.ts
=> more flexible options for building/running scripts

brigade.js, v2/tests/integration_test.go
* Adds a private repo test case to the integration test suite
Close https://github.com/brigadecore/brigade/issues/1233
=> ci(integration): add private repo test case

examples/11-kitchen-sink/project.yaml
This PR fixes an incorrect path in the project definition.
=> fix kitchen sink example

charts/brigade/templates/scheduler/deployment.yaml, charts/brigade/values.yaml
=> make max concurrent workers and jobs configurable during install

charts/brigade/templates/apiserver/deployment.yaml, charts/brigade/values.yaml, sdk/v2/core/named_roles.go, sdk/v2/system/named_roles.go, v2/apiserver/config.go, v2/apiserver/internal/authn/sessions.go, v2/apiserver/internal/authn/sessions_test.go, v2/apiserver/internal/core/events.go, v2/apiserver/internal/core/named_roles.go, v2/apiserver/internal/core/projects.go, v2/apiserver/internal/system/authn/named_principals.go, v2/apiserver/internal/system/named_roles.go, v2/apiserver/main.go, v2/cli/role_commands.go, v2/internal/os/os.go, v2/internal/os/os_test.go
=> streamline first-time login for admins 

v2/cli/secret_commands.go
Working on an unrelated issue on another project late on Friday-- an issue having to do with parsing key/val pairs from a file-- I came to realize how naive our approach to that same problem was here in the Brigade 2 CLI.
What we had in place prior to this PR probably works great for the majority of cases, but if someone were to enclose a value in double or singles quotes, we're definitely not handling that correctly. We'd be counting the quotes as part of the value instead of treating them as characters that disambiguate the boundaries of the value-- something people may do without even thinking twice if a value contained spaces, for instance.
(We actually can handle spaces no problem, but it's the quotes we aren't handling well.)
I started to think about the rules for parsing things …
=> improve parsing of secrets from a file

README.md
* Adds mention of the GitHub authn option
=> docs(README); add GitHub OAuth note

README.md
* Adds the GH App gateway to the list
=> docs(README): add GitHub App gateway

examples/07-npm/.brigade/package-lock.json, examples/07-npm/.brigade/package.json, examples/08-yarn/.brigade/package.json, examples/08-yarn/.brigade/yarn.lock, examples/11-kitchen-sink/.brigade/package.json, examples/11-kitchen-sink/.brigade/yarn.lock
Update examples to use the brigadier we just cut.
=> update examples to use latest brigadier

v2/apiserver/internal/core/logs.go, v2/apiserver/internal/core/logs_test.go, v2/apiserver/main.go
=> Log access fix

Makefile, brigade.js
Signed-off-by: willie-yao <t-williamyao@microsoft.com>
Added a job to `brigade.js` to run `yarn audit` in order to scan npm dependencies for security vulnerabilities on the v2 branch.
=> Added yarn audit job and make target

charts/brigade/templates/apiserver/deployment.yaml, charts/brigade/values.yaml, v2/apiserver/config.go, v2/apiserver/internal/authn/github/third_party_auth_helper.go
=> Limit authn by org

v2/internal/os/os.go
Randomly noticed some missing godocs and did something about it.
=> add godocs to os package

v2/apiserver/config_test.go
Temporary measure to unblock other progress.
See #1460
=> disable failing third party auth test

v2/apiserver/internal/authn/sessions.go
=> fix session ttl

.brigade/brigade.ts
=> validate examples as part of ci

.github/workflows/merge.yaml, .github/workflows/pr.yaml, Makefile
* Adds/updates CI/CD for the Windows logger agent
Closes https://github.com/brigadecore/brigade/issues/1277
=> ci(logger-windows): add CD

.github/workflows/merge.yaml
Quick fix/follow-up for https://github.com/brigadecore/brigade/pull/1472
Fixes failure seen in https://github.com/brigadecore/brigade/runs/2966940164
=> fix(.github): set docker registry on push of windows logger image

v2/observer/jobs.go
=> fix nil pointer dereference in observer

v2/apiserver/config_test.go
* Updates the ThirdPartyAuthHelper tests to hit a test server instead of an external provider
Closes https://github.com/brigadecore/brigade/issues/1460
=> fix(config_test.go): update ThirdPartyAuthHelper tests to hit test server

docs/content/topics/releasing.md
=> document v2 release procedures

v2/apiserver/schemas/common.json
=> fix schema for git clone urls

docs/content/intro/overview.md
* Updates the overview doc per v2
I ran with the existing structure, but also open to changing it up if others feel strongly.  I am slightly worried that I got too 'wordy' for the existing bulleted-list format... WDYT?
=> docs(overview.md): update for v2

v2/apiserver/internal/authn/sessions.go
=> track creation dts for user

v2/observer/common.go, v2/observer/common_test.go, v2/observer/jobs.go, v2/observer/jobs_test.go, v2/observer/observer.go, v2/observer/observer_test.go, v2/observer/workers.go, v2/observer/workers_test.go
=> force cleanup for manually deleted worker and job pods

docs/content/topics/developers.md
* Updates the developers guide per v2
Closes https://github.com/brigadecore/brigade/issues/1520
=> docs(developers.md): v2 updates

docs/content/intro/quickstart.md
=> fix cleanup command in quickstart

v2/brigadier-polyfill/package.json, v2/brigadier-polyfill/yarn.lock, v2/worker/yarn.lock
This PR remediates an issue found by yarn audit. Other CI runs are going to fail until this is merged.
=> address known vulnerabilities in npm packages

v2/cli/init_templates.go
Removes any mention of commented-out code from init template files
=> Removed mention of commented out code in init template files

.brigade/brigade.ts, Makefile, scripts/build-cli.sh, v2/apiserver/Dockerfile, v2/git-initializer/Dockerfile, v2/observer/Dockerfile, v2/scheduler/Dockerfile
=> build cli for arm64

v2/git-initializer/Dockerfile, v2/git-initializer/main.go
=> add startup message to git initializer

docs/content/topics/developers.md, hack/kind/new-cluster.sh
=> fix(kind/new-cluster): prevent error when kind cluster already exists

v2/apiserver/internal/api/events.go, v2/apiserver/internal/api/events_test.go, v2/apiserver/internal/api/mongodb/events_store.go, v2/apiserver/internal/api/mongodb/events_store_test.go, v2/apiserver/internal/api/projects.go, v2/apiserver/internal/api/projects_test.go
=> fix: delete all associated events on project delete

sdk/v2/authn/service_accounts.go, sdk/v2/authn/service_accounts_test.go, sdk/v2/testing/authn/mock_service_accounts_client.go, v2/apiserver/internal/api/mongodb/service_accounts_store.go, v2/apiserver/internal/api/mongodb/service_accounts_store_test.go, v2/apiserver/internal/api/rest/service_account_endpoints.go, v2/apiserver/internal/api/service_accounts.go, v2/apiserver/internal/api/service_accounts_test.go, v2/apiserver/main.go, v2/cli/service_account_commands.go
Builds on top of #1566 and needs to be rebased after that is merged.
=> add service account delete functionality

docs/content/topics/administrators/authentication.md, docs/content/topics/operators/deploy.md
* Adds authentication doc
Preview: https://deploy-preview-1571--brigade-docs.netlify.app/topics/administrators/authentication/
Closes https://github.com/brigadecore/brigade/issues/1570
=> docs(authentication.md): add authentication doc

docs/content/intro/install.md, docs/content/intro/quickstart.md, docs/content/topics/operators/deploy.md, v2/cli/init_templates.go
This PR bumps everything that _can_ be bumped pre-release.
There will be a post-release PR to bump dependencies for examples and such.
=> pre-release version bumps

.brigade/package.json, .brigade/yarn.lock, examples/07-npm/.brigade/package-lock.json, examples/07-npm/.brigade/package.json, examples/08-yarn/.brigade/package.json, examples/08-yarn/.brigade/yarn.lock, examples/11-kitchen-sink/.brigade/package.json, examples/11-kitchen-sink/.brigade/yarn.lock, examples/gateways/example-gateway/go.mod, examples/gateways/example-gateway/go.sum
Updates examples to use latest Brigadier and SDK for Go.
=> post-release version bumps

docs/content/topics/administrators/authorization.md
* Adds the Authorization doc
Admittedly it's fairly no-frills as written -- please advise if there are areas where more elaboration or context would be favored @krancour.
Closes https://github.com/brigadecore/brigade/issues/1575
=> docs(authorization.md): add authorization doc

docs/content/topics/operators/storage.md
* Updates the storage doc per v2
Preview: https://deploy-preview-1586--brigade-docs.netlify.app/topics/operators/storage/
Closes https://github.com/brigadecore/brigade/issues/1579
=> docs(storage.md): v2 updates

examples/02-first-event/project.yaml, v2/brigadier-polyfill/package.json, v2/brigadier-polyfill/src/events.ts, v2/brigadier-polyfill/yarn.lock, v2/brigadier/src/events.ts
Follows up on #1593 
Fixes #1590
=> add worker support for event summary field, pt2

docs/content/topics/project-developers/secrets.md
* Updates the secrets doc per v2
Preview: https://deploy-preview-1599--brigade-docs.netlify.app/topics/project-developers/secrets/
Closes https://github.com/brigadecore/brigade/issues/1598
=> docs(secrets.md): updates per v2

.brigade/brigade.ts
This corrects an issue that prevents our artemis image from being pushed correctly on merge to v2.
=> brigade.ts: fix push-artemis job

.brigade/package.json, .brigade/yarn.lock, examples/07-npm/.brigade/package-lock.json, examples/07-npm/.brigade/package.json, examples/08-yarn/.brigade/package.json, examples/08-yarn/.brigade/yarn.lock, examples/11-kitchen-sink/.brigade/package.json, examples/11-kitchen-sink/.brigade/yarn.lock, examples/gateways/example-gateway/go.mod, examples/gateways/example-gateway/go.sum
Updates all examples to use latest brigadier (script examples) or SDK (gateway example).
=> post release version bumps

docs/content/topics/project-developers/brig.md
* Adds the brig doc
Wasn't sure what else we wanted to cover; currently, it's fairly brief.  Thoughts?
Preview: https://deploy-preview-1604--brigade-docs.netlify.app/topics/project-developers/brig/
Closes https://github.com/brigadecore/brigade/issues/1600
=> docs(brig.md): add brig doc

docs/content/topics/operators/gateways.md, docs/content/topics/project-developers/events.md
* Adds Events doc
Preview: https://deploy-preview-1596--brigade-docs.netlify.app/topics/project-developers/events/
Closes https://github.com/brigadecore/brigade/issues/1587
=> docs(events.md): add Events doc

brigade-worker/src/k8s.ts
=> worker: git sidecar gets pull policy from job config

README.md
cc @vdice @karenhchu 
If we're happy with the wording and where this links to, I'll add this to all of our active repos.
=> mention code of conduct in readme

v2/cli/user_commands.go
=> cli: fix format of user "first seen" column

v2/brigadier/README.md
* Adds a README for the brigadier library
Closes https://github.com/brigadecore/brigade/issues/1631
=> docs(brigadier): add README.md

.github/workflows/README.md, .github/workflows/merge.yaml, .github/workflows/pr.yaml, Makefile, v2/git-initializer-windows/Dockerfile
First of at least two PRs collectively aimed at addressing #1713 
A follow-up will make chart and code changes so that the windows variant of this image is applied as necessary.
This PR is only focused on getting the image to build.
=> build windows git initializer

sdk/v2/core/workers.go, v2/apiserver/internal/api/workers.go
=> add missing phases to WorkerPhasesAll()

charts/brigade/templates/NOTES.txt
This PR updates post-install notes with info on how to access DB passwords.
=> chart: update notes

.github/workflows/release.yaml
Well somebody (me) forgot that this workflow used PowerShell and not POSIX.
=> fix windows image release process

v2/worker/yarn.lock
This should have been included in #1741
=> update worker's yarn.lock

docs/config.toml
=> Link to Brigade blog in website header

.brigade/package.json, .brigade/yarn.lock, examples/09-npm/.brigade/package-lock.json, examples/09-npm/.brigade/package.json, examples/10-yarn/.brigade/package.json, examples/10-yarn/.brigade/yarn.lock, examples/12-kitchen-sink/.brigade/package.json, examples/12-kitchen-sink/.brigade/yarn.lock
These bumps were mistakenly absent from #1756
=> more post-release version bumps

.brigade/brigade.ts, v2/apiserver/internal/api/events.go
=> fix permissions requirments for creating events

v2/cli/client.go, v2/cli/client_test.go, v2/cli/event_commands.go, v2/cli/log_command.go, v2/cli/logout_command.go, v2/cli/project_commands.go, v2/cli/project_role_commands.go, v2/cli/role_commands.go, v2/cli/secret_commands.go, v2/cli/service_account_commands.go, v2/cli/term_command.go, v2/cli/user_commands.go, v2/cli/version_command.go
=> cli: test connection to api server before returning to caller

sdk/v3/core/common.go, sdk/v3/core/jobs.go, sdk/v3/core/jobs_test.go, sdk/v3/core/logs.go, sdk/v3/core/projects.go, sdk/v3/core/projects_test.go, sdk/v3/core/workers.go, sdk/v3/core/workers_test.go, v2/apiserver/internal/api/projects.go, v2/apiserver/internal/api/projects_test.go, v2/apiserver/internal/api/rest/projects_endpoints.go, v2/cli/flags.go, v2/cli/project_commands.go
=> Support option to create non-existing project on update

charts/brigade/templates/deployments.yaml, charts/brigade/values.yaml, v2/apiserver/config.go, v2/apiserver/config_test.go, v2/apiserver/internal/api/sessions.go, v2/apiserver/internal/api/sessions_test.go
=> Add option to automatically grant read-only permissions on first login

sdk/v3/project_role_assignments.go, sdk/v3/project_roles_assignments_test.go, sdk/v3/testing/mock_project_role_assignments_client.go, v2/apiserver/internal/api/mongodb/project_role_assignments_store.go, v2/apiserver/internal/api/project_role_assignments.go, v2/apiserver/internal/api/rest/project_role_assignments_endpoints.go, v2/cli/project_role_commands.go
Fixes #1804 
Builds on #1805 and should be rebased after that is merged.
=> New project role assignments endpoint

v2/brigadier-polyfill/package.json, v2/brigadier-polyfill/yarn.lock, v2/brigadier/yarn.lock, v2/worker/yarn.lock
This is the results of a `yarn upgrade --deep`, which upgrades dependencies of dependencies.
=> remediate known js package vulnerabilties

.brigade/brigade.ts, .brigade/project.yaml
This leverages the new cron event source to trigger nightly cleanup of our unstable image repository.
=> nightly cleanup

netlify.toml
=> remove 'settings' section

README.md, netlify.toml
=> Updates README.md with cron-event-source and added "Noisy Neighbor" the the list

hack/kind/new-cluster.sh
Within the last few days, my workflow completely broke down. After running `make hack-new-kind-cluster`, other commands like `make hack` started failing. The specific issue was an inability to push images to `localhost:5000` where the
registry that's connected to our kind cluster should be listening.
I'm chalking this recent breakdown up to a recent Docker Desktop upgrade I took.
After many `docker system prune -af`, many reboots (just to be sure), and lots of experimentation, I discovered that the inability to push to `localhost:5000` only starts _after_ the registry is connected to kind's own bridge network. Disconnect the registry from that network and _::poof::_, you can push to `localhost:5000` again. I cannot spot what is special about that network that is causing this issue.
So I …
=> improve hack/new-cluster.sh script

docs/assets/scss/brigade.scss, docs/layouts/partials/content-footer.html
=> docs: add copyright notice to footer

.tiltignore, Tiltfile
This PR adds everything we need to use Tilt for improved devx, but it does _not_ remove our hack make targets yet. I am holding off on that until #1908 is ready to go.
i.e. The old and documented way of doing things will still work for now.
=> use tilt for faster feedback loop during development

sdk/v3/validations.go, sdk/v3/validations_test.go, v2/apiserver/schemas/common.json
=> apiserver: schema: relax regex for git URLs

docs/content/topics/contributor-guide/_index.md, docs/content/topics/contributor-guide/reviewing.md
In addition to @vdice, cc @carolynvs for some feedback.
=> add a reviewing guide

v2/apiserver/internal/api/projects.go, v2/apiserver/internal/api/projects_test.go
Signed-off-by: Anurag Pathak <anuragpathak911@gmail.com>
Fixes #1947 
**What this PR does / why we need it**: It solves the issue of brig update receiving authorization error when project doesn't exist and not logged in as root.
**Special notes for your reviewer**:  I've removed checking of project not found error in the project update function after the update attempt using Project Store because I feel it is no longer relevant now as we already did that earlier part of that function.
I have also modified the unit test just that all test cases pass. However they may be rearranged now to match the change in the update function (I can do that as well if required).
Moreover when -c flag is used we create a project which is requested to be updated but in logs we inform the project to be …
=> fix project update failure if project doesn't exist and not logged in as root

v2/apiserver/internal/api/sessions.go
=> make username comparisons case insensitive on initial authn

docs/content/intro/readnext.md, docs/content/topics/contributor-guide/_index.md
Fixes #1968 
Signed-off-by: Jorge Arteiro <jorgearteiro@hotmail.com>
Update Readnext page bad links
=> fixing readnext bad links

docs/content/topics/_index.md, docs/content/topics/contributor-guide/_index.md
Fixes #1970 
Signed-off-by: Jorge Arteiro <jorgearteiro@hotmail.com>
=> fix developers link on topics index page

README.md
- Contributes to #1983
- Preview: https://github.com/chalin/brigade/blob/patch-1/README.md
=> README: add an archived-status "banner"

docs/assets/scss/brigade.scss, docs/layouts/partials/head.html, docs/layouts/partials/site-header.html
- Contributes to #1983
- Preview: https://deploy-preview-1985--brigade-docs.netlify.app/
> <img width="668" alt="Screen Shot 2022-09-22 at 15 18 44" src="https://user-images.githubusercontent.com/4140793/191833777-e3afbd28-727c-4532-ba22-fe99bc42369b.png">
> <img width="378" alt="Screen Shot 2022-09-22 at 15 10 42" src="https://user-images.githubusercontent.com/4140793/191833879-c9d1fe03-822e-4a63-83d7-e3178a94ba41.png">
/cc @caniszczyk
=> Add archive message to docs banner
